### ISSUE TITLE
Slow JsonRpcServer test server setup leads to random test failures

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10284]
```
 INFO ide_ci::program::command: sbtℹ️ [info] org.enso.languageserver.websocket.json.ContextRegistryTest *** ABORTED *** (6 seconds, 420 milliseconds)
 INFO ide_ci::program::command: sbtℹ️ [info]   java.util.concurrent.TimeoutException: Future timed out after [3 seconds]
 INFO ide_ci::program::command: sbtℹ️ [info]   at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
 INFO ide_ci::program::command: sbtℹ️ [info]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
 INFO ide_ci::program::command: sbtℹ️ [info]   at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
 INFO ide_ci::program::command: sbtℹ️ [info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
 INFO ide_ci::program::command: sbtℹ️ [info]   at scala.concurrent.Await$.result(package.scala:124)
 INFO ide_ci::program::command: sbtℹ️ [info]   at org.enso.jsonrpc.test.JsonRpcServerTestKit.beforeEach(JsonRpcServerTestKit.scala:70)
 INFO ide_ci::program::command: sbtℹ️ [info]   at org.enso.languageserver.websocket.json.BaseServerTest.org$enso$testkit$WithTemporaryDirectory$$super$beforeEach(BaseServerTest.scala:81)
 INFO ide_ci::program::command: sbtℹ️ [info]   at org.enso.testkit.WithTemporaryDirectory.beforeEach(WithTemporaryDirectory.scala:20)
 INFO ide_ci::program::command: sbtℹ️ [info]   at org.enso.testkit.WithTemporaryDirectory.beforeEach$(WithTemporaryDirectory.scala:18)
 INFO ide_ci::program::command: sbtℹ️ [info]   at org.enso.languageserver.websocket.json.BaseServerTest.beforeEach(BaseServerTest.scala:81)
 INFO ide_ci::program::command: sbtℹ️ [info]   ...
 ```
https://github.com/enso-org/enso/actions/runs/9502538791/job/26190767148?pr=10272#step:7:2676

**Comment by JaroslavTulach** [comment]
Are these failures still happening?
