### ISSUE TITLE
Random failure in dropdown selection test

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10285]
```
 INFO ide_ci::program::command: npmℹ️   1) widgets.spec.ts:149:1 › Selection widgets in Data.read node ───────────────────────────────────
 INFO ide_ci::program::command: npmℹ️ 
 INFO ide_ci::program::command: npmℹ️     Error: Timed out 5000ms waiting for expect(locator).toBeVisible()
 INFO ide_ci::program::command: npmℹ️ 
 INFO ide_ci::program::command: npmℹ️     Locator: locator('.DropdownWidget:not([data-transitioning])')
 INFO ide_ci::program::command: npmℹ️     Expected: visible
 INFO ide_ci::program::command: npmℹ️     Received: hidden
 INFO ide_ci::program::command: npmℹ️     Call log:
 INFO ide_ci::program::command: npmℹ️       - expect.toBeVisible with timeout 5000ms
 INFO ide_ci::program::command: npmℹ️       - waiting for locator('.DropdownWidget:not([data-transitioning])')
 INFO ide_ci::program::command: npmℹ️ 
 INFO ide_ci::program::command: npmℹ️ 
 INFO ide_ci::program::command: npmℹ️       34 |
 INFO ide_ci::program::command: npmℹ️       35 |   async expectVisible(): Promise<void> {
 INFO ide_ci::program::command: npmℹ️     > 36 |     await expect(this.dropDown).toBeVisible()
 INFO ide_ci::program::command: npmℹ️          |                                 ^
 INFO ide_ci::program::command: npmℹ️       37 |   }
 INFO ide_ci::program::command: npmℹ️       38 |
 INFO ide_ci::program::command: npmℹ️       39 |   async expectNotVisible(): Promise<void> {
 INFO ide_ci::program::command: npmℹ️ 
 INFO ide_ci::program::command: npmℹ️         at DropDownLocator.expectVisible (/runner/_work/enso/enso/app/gui2/e2e/widgets.spec.ts:36:33)
 INFO ide_ci::program::command: npmℹ️         at DropDownLocator.expectVisibleWithOptions (/runner/_work/enso/enso/app/gui2/e2e/widgets.spec.ts:24:16)
 INFO ide_ci::program::command: npmℹ️         at /runner/_work/enso/enso/app/gui2/e2e/widgets.spec.ts:165:28
 ```
https://github.com/enso-org/enso/actions/runs/9502538790/job/26190765084?pr=10272#step:7:815

**Comment by farmaazon** [comment]
We don't have traces and no such issue was spotted since a while. Closing now.

@hubertp if you spot this again, please reopen this issue and attach the playwright reports downloaded from `summary` tab of GH action (before re-running job - otherwise they will be removed!)
