### ISSUE TITLE
Unexpected stop leads to cryptic exceptions

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10441]
As reported internally:
```
[WARN] [2024-07-03T13:35:20.147] [org.enso.languageserver.requesthandler.executioncontext.CreateHandler] Failed to receive a [CreateContextRequest(JsonSession(3acbad4c-6757-4b8b-9798-12e9ba1c9369,Actor[akka://language-server/user/json-connection-controller-86078554-0cd6-42d8-8280-678e9869cf70#-1389541243]),Some(e5114c91-083a-4b80-ab2b-912aa18a9f5c))] response in [10 seconds]. Retrying.
[ERROR] [2024-07-03T13:35:25.052] [org.enso.languageserver.requesthandler.monitoring.PingHandler] Health check timed out. Only 3/4 subsystems replied on time.
[INFO] [2024-07-03T13:35:25.062] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerSupervisor] Server is unresponsive. Restarting [LanguageServerConnectionInfo(127.0.0.1,51843,None,56569,None)].
[INFO] [2024-07-03T13:35:25.064] [org.enso.runner.LanguageServerApp] Stopping Language Server: stopped by the user
java.lang.NoClassDefFoundError: org/enso/languageserver/runtime/RuntimeKiller$ShutDownRuntime$
        at org.enso.IsolatedClassLoader//org.enso.languageserver.boot.LanguageServerComponent.terminateTruffle(LanguageServerComponent.scala:172)
        at org.enso.IsolatedClassLoader//org.enso.languageserver.boot.LanguageServerComponent.$anonfun$stop$1(LanguageServerComponent.scala:134)
        at org.enso.IsolatedClassLoader//scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
...
Caused by: java.lang.ClassNotFoundException: org.enso.languageserver.runtime.RuntimeKiller$ShutDownRuntime$
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:429)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at org.enso.runtime/org.enso.EngineRunnerBootLoader$IsolatedClassLoader.loadClass(EngineRunnerBootLoader.java:73)
        ... 9 more
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:935)
        at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:946)
        at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:463)
        at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:175)
        at java.base/jdk.internal.loader.Resource.getBytes(Resource.java:126)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getBytes(URLClassPath.java:862)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:519)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
        ... 15 more
```

**Comment by hubertp** [comment]
I've seen this on and off still. But I doubt we could do much here in the short term. Closing.
