### ISSUE TITLE
Sporadic `No_Such_Method` failure when executing `Base_Tests`

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10750]
The sporadic failure happens mostly on MacOS although it did appear for other OS as well.
```
JAVA_OPTS="-enableassertions" "/bin/bash" "/Users/runner/work/enso/enso/built-distribution/enso-engine-2024.4.1-dev-macos-amd64/enso-2024.4.1-dev/bin/enso" "--no-ir-caches" "--run" "/Users/runner/work/enso/enso/test/Base_Tests"
```

Will simply return a non-zero code and a simple `No_Such_Method` message, without any context.
The issue is not new and by looking at the past CI builds it has happened for the first time in https://github.com/enso-org/enso/actions/runs/9686658267/job/26729584788 (#10377 merge, unrelated).

**Comment by radeusgd** [comment]
Encountered it yet again in https://github.com/enso-org/enso/actions/runs/10245645438/job/28392624237?pr=10733#step:7:2072 run

<blockquote><img src="https://opengraph.githubassets.com/cf968dc5c675e561662bcd48e4cd82720a0dc9ae2043d1c9c72bb30df12651e5/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Initial Tableau Reading Support · enso-org/enso@872384f</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by hubertp** [comment]
[This](https://github.com/enso-org/enso/actions/runs/10262829302/job/28393327668#step:7:2115) is confusing. It seems to suggest that the problem is with the test that should be pending?

**Comment by radeusgd** [comment]
> [This](https://github.com/enso-org/enso/actions/runs/10262829302/job/28393327668#step:7:2115) is confusing. It seems to suggest that the problem is with the test that should be pending?

What do you mean?

Do you mean the 
```
 INFO ide_ci::program::command: bash ℹ️ Java FFI: [6/6, 17ms]
 INFO ide_ci::program::command: bash ℹ️     - [PENDING] should report missing method error on Java Arrays
 INFO ide_ci::program::command: bash ℹ️         Reason: Failing due to #6609
```
above?

That is most likely not it - the test summary is written _after_ each group has _finished_ executing. So the Java FFI pending test has finished and is now summarized.

Now the failure most likely is happening in the next group that is being executed. We could try to do a debug run which prints which group is started to try to locate the cause - but I'm not sure if that'll help.

**Comment by Akirathan** [comment]
Another interesting instance of this error is at https://github.com/enso-org/enso/actions/runs/10264320295/job/28398095736?pr=10555#step:7:2118 . This time, there is mention of `java.io.IOException`:
```
INFO ide_ci::program::command: bash ℹ️ java.io.IOException: No_Such_Method
```

<blockquote><img src="https://opengraph.githubassets.com/d385509ef36d0cb1d4a02c885f3e183af15253f31f167e8b7960bb30dd85ca3c/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">WithWarnings uses EnsoHashMap to speed things up · enso-org/enso@a5878b2</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by hubertp** [comment]
Finally.
It could be one of `missing`, `sample`, `foobar`, `baz`, `nope`, `into`, or `==`. Although the exception is printed after `==`.
```
NFO ide_ci::program::command: enso ⚠️ java.lang.RuntimeException: #10750 ==
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.runtime.builtin.Error.makeNoSuchMethod(Error.java:162)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.node.callable.InvokeMethodNode.methodNotFound(InvokeMethodNode.java:286)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.node.callable.InvokeMethodNode.doFunctionalDispatchUncachedSymbol(InvokeMethodNode.java:219)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.node.callable.InvokeMethodNodeGen.execute(InvokeMethodNodeGen.java:226)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.node.callable.InvokeCallableNode.invokeDynamicSymbol(InvokeCallableNode.java:276)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.node.callable.InvokeCallableNodeGen.execute(InvokeCallableNodeGen.java:194)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.node.callable.ApplicationNode.executeGeneric(ApplicationNode.java:97)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric(AssignmentNodeGen.java:51)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:52)
 INFO ide_ci::program::command: enso ⚠️ 	at org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
 ```
https://github.com/enso-org/enso/actions/runs/10348083887/job/28657599636?pr=10769#step:7:10627

<blockquote><img src="https://opengraph.githubassets.com/f8a7400884fae17649b6b1b7b7048bcce3859a548fc560cc942fc0934bf772e8/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">[do no merge or review] Testing · enso-org/enso@0e3d1c1</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by hubertp** [comment]
https://github.com/enso-org/enso/actions/runs/10358080199/job/28690409691?pr=10769#step:7:9333

Looks like this time it was `==` method of `Error.type`

**Comment by jdunkerley** [comment]
Reviewed the No_Such_Method. It has the `to_display_text` properly set up.
I'm guessing it is an issue in `engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java` as to why the Java Exception is not showing the display text.

It looks like `computeMessage` will attempt to call the to_display_text via the InteropLibrary and fall back to the type name if it doesn't exist.

**Comment by hubertp** [comment]
In my [PR](https://github.com/enso-org/enso/pull/10769) I've been experimenting with one revert (https://github.com/enso-org/enso/pull/10769/commits/7bab8b89baac33a4496e17369c22b8570151e39b). While previously on that PR I would get sporadic failures, after applying the revert I had seen none. 
Note: I don't think this change is the sole culprit of this bug. I would say that it unmasks some deeper problem, like specialization order which is triggered non-deterministically.

**Comment by JaroslavTulach** [comment]
Hubert haven't seen this one for a while. Let's consider it fixed.

**Comment by hubertp** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDEyeXF4dXM3NngxdmNoNDBoOXZrNGR2YzZjYjZqMDV5eGk0aXkybCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l0HlVJmZTI3Tn94c0/giphy.gif)

https://github.com/enso-org/enso/actions/runs/10682796071/job/29609456166?pr=10960#step:7:3772

<blockquote><img src="https://opengraph.githubassets.com/b74e2427403f7783d91b071a7ddd9439dfddd1dc5a8862a0b0d0b9de5dce9a48/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Re-enable IR caching in Language Server · enso-org/enso@975aa2a</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by hubertp** [comment]
And another https://github.com/enso-org/enso/actions/runs/10791389410/job/29928689658?pr=11032#step:7:1255

<blockquote><img src="https://opengraph.githubassets.com/713ec50939759fcf7978e62398404e0c18c630415d58d1b15f9dcb34b0f46317/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Re-compile module if IdMap is present · enso-org/enso@f8b666b</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by hubertp** [comment]
Haven't seen this in a while. Closing.
