### ISSUE TITLE
RuntimeManagementTest is not shutting down Threads properly

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10804]
As revealed in [the investigation](https://github.com/enso-org/enso/pull/10793#issue-2459116470) related to memory leaks.

Seems like every time [`RuntimeManagementTest`](https://github.com/enso-org/enso/blob/develop/engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala) is run, we keep two threads up and running:
![Screenshot from 2024-08-12 16-29-09](https://github.com/user-attachments/assets/3f36475f-abb3-428a-8c16-da478d2a13da)

Not sure if this is caused by the bug in a test or in the implementation (finalizers) of ManagedResource.

**Comment by JaroslavTulach** [comment]
One possible culprit:
```
"pool-1-thread-1-ScalaTest-running-RuntimeManagementTest"
	at java.lang.Thread.genThreadName(Thread.java:1118)
	at java.lang.Thread.<init>(Thread.java:736)
	at java.lang.Thread.<init>(Thread.java:1165)
	at org.graalvm.polyglot.Engine$APIAccessImpl.newEngine(Engine.java:890)
	at com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:374)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:756)
	at org.graalvm.polyglot.Context$Builder.build(Context.java:1925)
	at org.enso.interpreter.test.InterpreterContext.ctx(InterpreterTest.scala:146)
	at org.enso.interpreter.test.semantic.RuntimeManagementTest.$anonfun$specify$1(RuntimeManagementTest.scala:18)
	at org.enso.interpreter.test.semantic.RuntimeManagementTest$$Lambda/0x00000007c0222190.apply$mcV$sp
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.wordspec.AnyWordSpec.withFixture(AnyWordSpec.scala:1880)
	at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1238)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1250)
	at org.scalatest.wordspec.AnyWordSpecLike$$Lambda/0x00000007c0290000.apply
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1250)
	at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1232)
	at org.scalatest.wordspec.AnyWordSpec.runTest(AnyWordSpec.scala:1880)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1309)
	at org.scalatest.wordspec.AnyWordSpecLike$$Lambda/0x00000007c0285c08.apply
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at org.scalatest.SuperEngine$$Lambda/0x00000007c02861b0.apply
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at org.scalatest.SuperEngine$$Lambda/0x00000007c02861b0.apply
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at org.scalatest.SuperEngine$$Lambda/0x00000007c02861b0.apply
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1309)
	at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1308)
	at org.scalatest.wordspec.AnyWordSpec.runTests(AnyWordSpec.scala:1880)
	at org.scalatest.Suite.run(Suite.scala:1114)
	at org.scalatest.Suite.run$(Suite.scala:1096)
	at org.scalatest.wordspec.AnyWordSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(AnyWordSpec.scala:1880)
	at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1354)
	at org.scalatest.wordspec.AnyWordSpecLike$$Lambda/0x00000007c0280f60.apply
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1354)
	at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1352)
	at org.scalatest.wordspec.AnyWordSpec.run(AnyWordSpec.scala:1880)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:321)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:517)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:414)
	at sbt.ForkMain$Run$$Lambda/0x00000007c02057e0.call
	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(Thread.java:1596)
	at java.lang.Thread.run(Thread.java:1583)
```

**Comment by JaroslavTulach** [comment]
Possible fix to give unnamed threads some name doesn't help as [this test isn't leaking the threads](https://github.com/enso-org/enso/issues/10804#issuecomment-2308141651):
```diff
$ git diff
diff --git engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala
index 876b42ab20..7f3b018f3a 100644
--- engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala
+++ engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala
@@ -47,7 +47,7 @@ class RuntimeManagementTest extends InterpreterTest {
       }
 
       def runTest(n: Int = 5): Unit = {
-        val threads = 0.until(n).map(_ => new Thread(runnable))
+        val threads = 0.until(n).map(_ => new Thread(runnable, "RuntimeManagementTest-Thread"))
         threads.foreach(_.start())
         var reportedCount = 0
         while (reportedCount < n) {
```
that names one of the testing threads.

**Comment by JaroslavTulach** [comment]
> Seems like every time [RuntimeManagementTest](https://github.com/enso-org/enso/blob/develop/engine/runtime-integration-tests/src/test/scala/org/enso/interpreter/test/semantic/RuntimeManagementTest.scala) is run, we keep two threads up and running:

What do you mean. "Every time" it is run? I can:
```
sbt:runtime-integration-tests> testOnly *RuntimeManagementTest
```
however that runs the test **only once**. How do I reproduce "every time"?

**Comment by JaroslavTulach** [comment]
Taking heap dump shows the _Thread-144_ hanging there after `RuntimeManagementTest` gets executed in a sequence of tests started by
```
sbt:runtime-integration-tests> test
```
is a `LanguageSystemThread`:

![language system thread #2](https://github.com/user-attachments/assets/92da9836-f47d-4603-8b3b-78a8a964f0ec)

The _Thread-143_ is also `LanguageSystemThread`. Nobody has references to them. They point to the same instance of `PolyglotImpl` via the `polyglot` field. And to two different instances of `PolyglotContextImpl` via the `polyglotContext` field.

**Comment by JaroslavTulach** [comment]
There are four tests in `RuntimeManagementTest` and only the last three are leaving the threads behind. The first one creates new suspicious threads:
```
[info] RuntimeManagementTest:
[info] Enso Code Execution
[info]   when Context is Cached
SLF4J: Attempting to load provider "org.enso.logger.TestLogProvider" specified via "slf4j.provider" system property
[info]   - should Interrupt threads through Thread#interrupt() (1 second, 812 milliseconds)
[info]   - should Automatically free managed resources !!! IGNORED !!!
[info]   - should Automatically free managed resources amongst manual closure of other managed resources !!! IGNORED !!!
[info]   - should Automatically free managed resources amongst manual takeover of other managed resources !!! IGNORED !!!
[info] Enso Code Execution
[info]   when Context is Uncached
[info]   - should Interrupt threads through Thread#interrupt() (326 milliseconds)
[info]   - should Automatically free managed resources !!! IGNORED !!!
[info]   - should Automatically free managed resources amongst manual closure of other managed resources !!! IGNORED !!!
[info]   - should Automatically free managed resources amongst manual takeover of other managed resources !!! IGNORED !!!
Found 0 suspicious threads
[info] Test run org.enso.interpreter.test.instrument.RuntimeManagementCleanupTest finished: 0 failed, 0 ignored, 1 total, 1.057s
```

**Comment by JaroslavTulach** [comment]
**Culprit**: `RuntimeManagementTest` doesn't close the `EnsoContext`!

**Comment by JaroslavTulach** [comment]
> **Culprit**: `RuntimeManagementTest` doesn't close the `EnsoContext`!

At the end 
- #10890 

fixes the problem by finishing the threads when they become idle.
