### ISSUE TITLE
Engine (Oracle GraalVM) CI check fails

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#10895]
Nightly CI checks on [Oracle GraalVM](https://github.com/enso-org/enso/actions/runs/10570955872/job/29286267825#step:7:1029) are currently failing:
```
 Error: Module jdk.compiler.graal not found
 java.lang.module.FindException: Module jdk.compiler.graal not found
 	at java.base/java.lang.module.Resolver.findFail(Resolver.java:892)
 	at java.base/java.lang.module.Resolver.resolve(Resolver.java:129)
 	at java.base/java.lang.module.Configuration.resolve(Configuration.java:420)
 	at java.base/java.lang.module.Configuration.resolve(Configuration.java:254)
 	at jdk.jlink/jdk.tools.jlink.internal.Jlink$JlinkConfiguration.resolve(Jlink.java:217)
 	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImageProvider(JlinkTask.java:523)
 	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.createImage(JlinkTask.java:411)
 	at jdk.jlink/jdk.tools.jlink.internal.JlinkTask.run(JlinkTask.java:286)
 	at jdk.jlink/jdk.tools.jlink.internal.Main.run(Main.java:56)
 	at jdk.jlink/jdk.tools.jlink.internal.Main.main(Main.java:34)
```

**Comment by JaroslavTulach** [comment]
Hubert says it might be an `sbt` issue.

**Comment by hubertp** [comment]
Looks like builds starting failing with this commit https://github.com/enso-org/enso/commit/5c06535c46d2a20d9eef70af415575c34ddb3f78

**Comment by JaroslavTulach** [comment]
Thank you Hubert for identifying source of the problem.

**Comment by hubertp** [comment]
It's fine, I still think it's `sbt` so you can leave it to me :)

**Comment by hubertp** [comment]
I've been trying to figure where `jdk.compiler.graal` is coming from and I couldn't find it in GraalVM distribution (neither community nor enterprise one). So I just removed it and things worked. So I guess that's a valid enough solution?

**Comment by JaroslavTulach** [comment]
If things work, then it is a fix!

FYI: There was a discussion about [jdk.compiler.graal at GraalVM Slack](https://graalvm.slack.com/archives/CN9KSFB40/p1715145259768559?thread_ts=1715083564.880179&cid=CN9KSFB40).
