### ISSUE TITLE
Don't swallow nested exceptions when logging them

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#10908]
Can we improve logging when error during `buildEngineDistribution` happens? What happens right now is:
```
[ERROR] [2024-08-28T09:01:46.440] [org.enso.runner.Main] Unexpected internal error
org.graalvm.polyglot.PolyglotException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "org.enso.compiler.context.FramePointer.parentLevel()" because "obj" is null
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.enso.runtime/org.enso.interpreter.runtime.scope.TopLevelScope$InvokeMember.compile(TopLevelScope.java:178)
        at org.enso.runtime/org.enso.interpreter.runtime.scope.TopLevelScope$InvokeMember.doInvoke(TopLevelScope.java:203)
        at org.enso.runtime/org.enso.interpreter.runtime.scope.TopLevelScopeGen$InteropLibraryExports$Cached.invokeMember(TopLevelScopeGen.java:83)
```
that's fine, but useless. Because I need to know the location of the `NullPointerException` and that's not printed. It is there (stored as `RuntimeException.getCause().getCause()`) but it is not printed by our logging system. Following change prints the exception for me:
```diff
$ git diff engine/runner
diff --git engine/runner/src/main/java/org/enso/runner/Main.java engine/runner/src/main/java/org/enso/runner/Main.java
index ea2365f38a..752d0da070 100644
--- engine/runner/src/main/java/org/enso/runner/Main.java
+++ engine/runner/src/main/java/org/enso/runner/Main.java
@@ -642,6 +642,7 @@ public class Main {
       topScope.compile(shouldCompileDependencies);
       throw exitSuccess();
     } catch (Throwable t) {
+      t.printStackTrace();
       logger.error("Unexpected internal error", t);
       throw exitFail();
     } finally {
```
can we **reconfigure our logging system** to print whole chain of `getCause()` nested exceptions?

**Comment by JaroslavTulach** [comment]
If we don't want to fix any other case than `TopLevelScope.compile`, then we may be fine with [this change](https://github.com/enso-org/enso/pull/10906/files#r1741729216).
