### ISSUE TITLE
`Widgets.get_widget_json` can only get the extension methods in scope in the Widgets.enso file

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#11021]
Add `"Hello World"`
Add a parse_to_table function.

The pattern widget will not be generated.

**Currently has a workaround in to bring all extensions in scope.**: https://github.com/enso-org/enso/commit/7b4b635fa899bf09605c1b83ff5c740d88b0f7cb#diff-f54687734368c5b3a22c04535c79fbd9731ed95e2d6846fc46c18dc1f59b9ec7R4

**Comment by jdunkerley** [comment]
Current Repro:
Remove the `from Standard.Geo import all` from distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
The column selector widget will then be unavailable on a `Table.geo_distance` function.

**Comment by JaroslavTulach** [comment]
When I use `geo_distance` on I see `2025.2.1-nightly.2025.6.18`:

![some drop down](https://github.com/user-attachments/assets/c1cd51e2-0aa4-4ca4-add7-a20e90e74b1e)

When I apply following change:
```diff
enso$ git diff
diff --git distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
index ad0ee6f99c..fc23169a46 100644
--- distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
+++ distribution/lib/Standard/Visualization/0.0.0-dev/src/Widgets.enso
@@ -8,8 +8,6 @@ from Standard.Table import all
 
 from Standard.Database import all
 
-from Standard.Geo import all
-
 ## PRIVATE
    Basic preprocessor for widgets metadata visualization.
 
```
then the drop down changes to:

![Image](https://github.com/user-attachments/assets/3b327ca7-1810-40cd-ac8d-221e4a6c6948)

1. @jdunkerley, I assume that's the problem to address, right? 
2. I haven't found a unit test that would fail when `from Standard.Geo import all` is commented out
3. This [could be a test](https://github.com/enso-org/enso/commit/05119d6e3fca03801cd706c438f02068c03583df) - but it isn't influenced by `from Standard.Geo import all` being commented out

**Comment by JaroslavTulach** [comment]
With a little bit of more logging, we can find out:
```diff
enso$ git diff
diff --git engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
index 0369856d5d..c7fe60aa82 100644
--- engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
+++ engine/runtime-instrument-common/src/main/java/org/enso/interpreter/service/ExecutionService.java
@@ -71,6 +71,7 @@ import org.slf4j.LoggerFactory;
  * language.
  */
 public final class ExecutionService {
+  private static final Logger LOGGER = LoggerFactory.getLogger(ExecutionService.class);
   private static final String MAIN_METHOD = "main";
   private final EnsoContext context;
   private final Optional<IdExecutionService> idExecutionInstrument;
@@ -136,10 +137,9 @@ public final class ExecutionService {
     if (connectedLockManager != null) {
       connectedLockManager.connect(endpoint);
     } else {
-      LoggerFactory.getLogger(ExecutionService.class)
-          .warn(
-              "ConnectedLockManager was not initialized, even though a Language Server connection"
-                  + " has been established. This may result in synchronization errors.");
+      LOGGER.warn(
+          "ConnectedLockManager was not initialized, even though a Language Server connection"
+              + " has been established. This may result in synchronization errors.");
     }
   }
 
@@ -306,6 +306,7 @@ public final class ExecutionService {
    * @return a result of evaluation
    */
   public Object evaluateExpression(Module module, String expression) {
+    LOGGER.info("evaluateExpression in {} code: {}", module.getName(), expression);
     var future =
         submitExecution(
             () -> {
```
that the `UpsertVisualizationJob` is requesting evaluation of `.geo_distance` argument in wrong module:
```
evaluateExpression in Standard.Visualization.Helpers code: a -> a.default_visualization.to_js_object.to_json
evaluateExpression in Standard.Visualization.Preprocessor code: default_preprocessor
evaluateExpression in Standard.Visualization.Table.Visualization code: prepare_visualization
evaluateExpression in Standard.Visualization.Table.Visualization code: 1000
evaluateExpression in Standard.Visualization.Widgets code: .geo_distance
evaluateExpression in Standard.Visualization.Widgets code: ['lat1', 'long1', 'lat2', 'long2']
evaluateExpression in Standard.Visualization.Widgets code: '{}'
```
The argument shouldn't be evaluated in `Standard.Visualization.Widgets`... thus the error isn't in engine, but rather the language server or the IDE.

**Comment by JaroslavTulach** [comment]
Who's providing the wrong module? There is `module` and `expressionModule` at `evaluateModuleExpression(UpsertVisualizationJob.scala:437)` and both modules are set to `Standard.Visualization.Widgets` already:
```
"prioritized-job-pool-2"
	at org.enso.interpreter.service.ExecutionService.evaluateExpression(ExecutionService.java:309)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateArgumentExpression$1(UpsertVisualizationJob.scala:302)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$$$Lambda/0x000079910fc46ee8.apply
	at scala.util.Try$.apply(Try.scala:217)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.evaluateArgumentExpression(UpsertVisualizationJob.scala:302)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateArgumentExpressions$2(UpsertVisualizationJob.scala:282)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$$$Lambda/0x000079910fc46b08.apply
	at scala.util.Either.flatMap(Either.scala:360)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateArgumentExpressions$1(UpsertVisualizationJob.scala:281)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$$$Lambda/0x000079910fbd11c0.apply
	at scala.collection.IterableOnceOps.foldLeft(IterableOnce.scala:687)
	at scala.collection.IterableOnceOps.foldLeft$(IterableOnce.scala:721)
	at scala.collection.AbstractIterable.foldLeft(Iterable.scala:935)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.evaluateArgumentExpressions(UpsertVisualizationJob.scala:279)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateModuleExpression$1(UpsertVisualizationJob.scala:442)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$$$Lambda/0x000079910fbd0de0.apply
	at scala.util.Either.flatMap(Either.scala:360)
```

![Image](https://github.com/user-attachments/assets/a0d043f4-e612-4dee-8c2b-2d18dd990ea3)

```
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.evaluateModuleExpression(UpsertVisualizationJob.scala:437)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateVisualizationExpression$2(UpsertVisualizationJob.scala:465)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$$$Lambda/0x000079910fb7ee40.apply
	at scala.util.Either.flatMap(Either.scala:360)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateVisualizationExpression$1(UpsertVisualizationJob.scala:464)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$$$Lambda/0x000079910fb7ea60.apply
	at scala.util.Either.flatMap(Either.scala:360)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.org$enso$interpreter$instrument$job$UpsertVisualizationJob$$evaluateVisualizationExpression(UpsertVisualizationJob.scala:463)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob.$anonfun$runImpl$1(UpsertVisualizationJob.scala:71)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$$Lambda/0x000079910fa97d08.call
	at org.enso.interpreter.instrument.execution.ReentrantLocking.withContextLock(ReentrantLocking.scala:207)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob.runImpl(UpsertVisualizationJob.scala:69)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob.runImpl(UpsertVisualizationJob.scala:43)
	at org.enso.interpreter.instrument.job.Job.run(Job.scala:38)
	at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:237)
	at org.enso.interpreter.instrument.execution.JobExecutionEngine$$Lambda/0x000079910f8e7108.call
	at java.util.concurrent.FutureTask.run(FutureTask.java:328)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
	at java.lang.Thread.runWith(Thread.java:1460)
	at java.lang.Thread.run(Thread.java:1447)
```
