### ISSUE TITLE
Occasional `IOException`/`InterruptedException` during startup

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11084]
![Screenshot from 2024-09-16 11-58-16](https://github.com/user-attachments/assets/40e81bc7-bd0a-416e-aca2-b6243a261953)
![Screenshot from 2024-09-16 11-59-31](https://github.com/user-attachments/assets/8604fcf4-49bb-4e58-843c-c5aa6fc04b17)

Our execution can be interrupted but it should only happen when there is another one in the queue scheduled.

**Comment by JaroslavTulach** [comment]
I was just playing with the [FIS project](https://github.com/otulach/SCMrozdeleni) and I am seeing the exception on every second run - execute `enso --run src/Download.enso`.

**Comment by JaroslavTulach** [comment]
I tried to test my project on `2024.5.1-nightly.2024.10.2` yesterday few times...

> I was just playing with the [FIS project](https://github.com/otulach/SCMrozdeleni) and I am seeing the exception on every second run - execute `enso --run src/Download.enso`.

...and I have never seen the `InterruptedException`. Maybe it was mitigated somehow?

Anyway, I cannot run the whole project's download process anymore. I had to [apply a bugfix](https://github.com/otulach/SCMrozdeleni/commit/4ad7af374e25fbf095a7829c8785531e16c8512d) to
- because `enso_project.data / 'FISResults'+season+'.csv'` no longer works
- because `Table.from_union operator93079 Match_Columns.By_Name Boolean.True` no longer works

even with that I am getting:
```
$ enso --run src/Download.enso
Competition Done fetching https://www.fis-ski.com/DB/general/results.html?sectorcode=SB&raceid=21610
Competition https://www.fis-ski.com/DB/general/results.html?sectorcode=SB&raceid=21610 stored in (Error: (Time_Error.Error 'Text \'\' could not be parsed at index 0 (Expected date/time format: MMM d, yyyy)' java.time.format.DateTimeParseException: Text '' could not be parsed at index 0))
Finished (Error: (Map_Error.Error 0 (Time_Error.Error 'Text \'\' could not be parsed at index 0 (Expected date/time format: MMM d, yyyy)' java.time.format.DateTimeParseException: Text '' could not be parsed at index 0)))
```
don't you know, @jdunkerley what could be the fix?

**Comment by hubertp** [comment]
Another example of interrupts interfering with the execution where we get temporary `Could not find a conversion from `sleep interrupted` to `Table`.`:
```
[TRACE] [2024-10-03T15:27:39.166] [enso.org.enso.interpreter.service.ExecutionService] Executing visualization [0b5d2afc-d8f6-403d-85f0-44be1f08321f] on expression [9e840d3f-32bb-44f6-99bc-c2f410990c22] of [java.lang.InterruptedException]...
org.enso.interpreter.runtime.control.ThreadInterruptedException
	at org.enso.runtime/org.enso.interpreter.runtime.ThreadManager$1.perform(ThreadManager.java:78)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.performTLAction(LanguageAccessor.java:565)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThreadLocalActions$AsyncEvent.acceptImpl(PolyglotThreadLocalActions.java:649)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThreadLocalActions$AbstractTLHandshake.accept(PolyglotThreadLocalActions.java:601)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThreadLocalActions$AbstractTLHandshake.accept(PolyglotThreadLocalActions.java:546)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.ThreadLocalHandshake$Handshake.perform(ThreadLocalHandshake.java:219)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.ThreadLocalHandshake$TruffleSafepointImpl.processHandshakes(ThreadLocalHandshake.java:368)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.ThreadLocalHandshake.processHandshake(ThreadLocalHandshake.java:159)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.hotspot.HotSpotThreadLocalHandshake.poll(HotSpotThreadLocalHandshake.java:79)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleSafepoint.poll(TruffleSafepoint.java:155)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode$RepeatedCallNode.executeRepeating(LoopingCallOptimiserNode.java:263)
	at org.graalvm.truffle/com.oracle.truffle.api.nodes.RepeatingNode.executeRepeatingWithValue(RepeatingNode.java:112)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedOSRLoopNode.profilingLoop(OptimizedOSRLoopNode.java:169)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedOSRLoopNode.execute(OptimizedOSRLoopNode.java:120)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode.dispatch(LoopingCallOptimiserNode.java:95)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode.cachedDispatch(LoopingCallOptimiserNode.java:69)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNodeGen.executeDispatch(LoopingCallOptimiserNodeGen.java:87)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCall(IndirectCurryNode.java:134)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCurry(IndirectCurryNode.java:78)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.IndirectCurryNodeGen.execute(IndirectCurryNodeGen.java:78)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeUncached(InvokeFunctionNode.java:209)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:92)
	at org.enso.runtime/org.enso.interpreter.node.callable.InteropApplicationNode.callCached(InteropApplicationNode.java:84)
	at org.enso.runtime/org.enso.interpreter.node.callable.InteropApplicationNodeGen.execute(InteropApplicationNodeGen.java:79)
	at org.enso.runtime/org.enso.interpreter.node.callable.FunctionCallInstrumentationNode$FunctionCall$Execute.callCached(FunctionCallInstrumentationNode.java:103)
	at org.enso.runtime/org.enso.interpreter.node.callable.FunctionCallGen$InteropLibraryExports$Cached.execute(FunctionCallGen.java:97)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7952)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionService$CallRootNode.execute(ExecutionService.java:588)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:519)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:500)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionService.callFunctionWithInstrument(ExecutionService.java:394)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.makeCall$1(ProgramExecutionSupport.scala:590)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$executeVisualization$5(ProgramExecutionSupport.scala:606)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.RuntimeCache.runQuery(RuntimeCache.java:197)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$executeVisualization$1(ProgramExecutionSupport.scala:606)
	at scala.library@2.13.11/scala.util.Try$.apply(Try.scala:210)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeVisualization(ProgramExecutionSupport.scala:569)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeAndSendVisualizationUpdate(ProgramExecutionSupport.scala:706)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$sendVisualizationUpdates$1(ProgramExecutionSupport.scala:549)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$sendVisualizationUpdates$1$adapted(ProgramExecutionSupport.scala:542)
	at scala.library@2.13.11/scala.collection.immutable.List.foreach(List.scala:333)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.sendVisualizationUpdates(ProgramExecutionSupport.scala:542)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$executeProgram$3(ProgramExecutionSupport.scala:98)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionCallbacks.callOnComputedCallback(ExecutionCallbacks.java:146)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionCallbacks.updateCachedResult(ExecutionCallbacks.java:117)
	at org.enso.runtime.instrument.id.execution/org.enso.interpreter.instrument.id.execution.IdExecutionInstrument$IdEventNodeFactory$IdExecutionEventNode.onReturnValue(IdExecutionInstrument.java:252)
	at org.enso.runtime.instrument.id.execution/org.enso.interpreter.instrument.id.execution.IdExecutionInstrument$IdEventNodeFactory$IdExecutionEventNode.onReturnExceptional(IdExecutionInstrument.java:267)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventProviderChainNode.innerOnReturnExceptional(ProbeNode.java:1504)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onReturnExceptional(ProbeNode.java:1090)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode.onReturnExceptionalOrUnwind(ProbeNode.java:313)
	at org.enso.runtime/org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:48)
	at org.enso.runtime/org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric(AssignmentNodeGen.java:51)
	at org.enso.runtime/org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:43)
	at org.enso.runtime/org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:59)
	at org.enso.runtime/org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:43)
	at org.enso.runtime/org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:61)
	at org.enso.runtime/org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:61)
	at org.enso.runtime/org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:519)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedIndirectCallNode.call(OptimizedIndirectCallNode.java:67)
	at org.enso.runtime/org.enso.interpreter.node.callable.ExecuteCallNode.callIndirect(ExecuteCallNode.java:128)
	at org.enso.runtime/org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:95)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode$RepeatedCallNode.executeRepeating(LoopingCallOptimiserNode.java:270)
	at org.graalvm.truffle/com.oracle.truffle.api.nodes.RepeatingNode.executeRepeatingWithValue(RepeatingNode.java:112)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedOSRLoopNode.profilingLoop(OptimizedOSRLoopNode.java:169)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedOSRLoopNode.execute(OptimizedOSRLoopNode.java:120)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode.dispatch(LoopingCallOptimiserNode.java:95)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode.cachedDispatch(LoopingCallOptimiserNode.java:69)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNodeGen.executeDispatch(LoopingCallOptimiserNodeGen.java:87)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCall(IndirectCurryNode.java:134)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCurry(IndirectCurryNode.java:78)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.IndirectCurryNodeGen.execute(IndirectCurryNodeGen.java:78)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeUncached(InvokeFunctionNode.java:209)
	at org.enso.runtime/org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:92)
	at org.enso.runtime/org.enso.interpreter.node.callable.InteropApplicationNode.callCached(InteropApplicationNode.java:84)
	at org.enso.runtime/org.enso.interpreter.node.callable.InteropApplicationNodeGen.execute(InteropApplicationNodeGen.java:79)
	at org.enso.runtime/org.enso.interpreter.node.callable.FunctionCallInstrumentationNode$FunctionCall$Execute.callCached(FunctionCallInstrumentationNode.java:103)
	at org.enso.runtime/org.enso.interpreter.node.callable.FunctionCallGen$InteropLibraryExports$Cached.execute(FunctionCallGen.java:97)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7952)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionService$ExecuteRootNode.execute(ExecutionService.java:567)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:519)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:500)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:205)
	at org.enso.runtime.instrument.common/org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:250)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeProgram(ProgramExecutionSupport.scala:148)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$3(ProgramExecutionSupport.scala:274)
	at scala.library@2.13.11/scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.library@2.13.11/scala.util.Try$.apply(Try.scala:210)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$2(ProgramExecutionSupport.scala:274)
	at scala.library@2.13.11/scala.util.Either.flatMap(Either.scala:352)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ProgramExecutionSupport$.runProgram(ProgramExecutionSupport.scala:269)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.$anonfun$runImpl$2(ExecuteJob.scala:80)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.$anonfun$runImpl$2$adapted(ExecuteJob.scala:70)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.execution.ReentrantLocking.withReadCompilationLock(ReentrantLocking.scala:140)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.$anonfun$runImpl$1(ExecuteJob.scala:70)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.$anonfun$runImpl$1$adapted(ExecuteJob.scala:67)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.execution.ReentrantLocking.withContextLock(ReentrantLocking.scala:217)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.runImpl(ExecuteJob.scala:67)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:33)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:17)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:145)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:106)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:140)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:131)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:519)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:500)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:102)
[TRACE] [2024-10-03T15:27:39.173] [enso.org.enso.interpreter.service.ExecutionService] ON_COMPUTED df483367-1b85-4e57-89d7-712df65667fc
[DEBUG] [2024-10-03T15:27:39.173] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((df483367-1b85-4e57-89d7-712df65667fc,Some(Standard.Base.Nothing.Nothing)))]
[TRACE] [2024-10-03T15:27:39.173] [org.enso.languageserver.runtime.ContextRegistry] received handled ExpressionUpdates(4f4f849b-994c-43cb-bb5b-1a2221124c81,Set(ExpressionUpdate(df483367-1b85-4e57-89d7-712df65667fc,Some(Standard.Base.Nothing.Nothing),None,Vector(ExecutionTime(552744765)),false,false,Value(None,None)))) from Actor[akka://language-server/deadLetters]
[TRACE] [2024-10-03T15:27:39.174] [enso.org.enso.interpreter.service.ExecutionService] ON_COMPUTED a2df3a1f-7be6-458c-8709-783b412a3c46
[DEBUG] [2024-10-03T15:27:39.174] [enso.org.enso.interpreter.service.ExecutionService] computation of expression has been interrupted
[TRACE] [2024-10-03T15:27:39.174] [enso.org.enso.interpreter.service.ExecutionService] ON_COMPUTED 2b551a49-18cd-4b92-a817-8c7071019597
[DEBUG] [2024-10-03T15:27:39.174] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((2b551a49-18cd-4b92-a817-8c7071019597,Some(Standard.Table.Table.Table.type)))]
[TRACE] [2024-10-03T15:27:39.174] [enso.org.enso.interpreter.service.ExecutionService] ON_COMPUTED 7ccf842b-13c5-4a45-8eb1-ffc3b520b7ab
[TRACE] [2024-10-03T15:27:39.174] [org.enso.languageserver.runtime.ContextRegistry] received handled ExpressionUpdates(4f4f849b-994c-43cb-bb5b-1a2221124c81,Set(ExpressionUpdate(2b551a49-18cd-4b92-a817-8c7071019597,Some(Standard.Table.Table.Table.type),None,Vector(ExecutionTime(699)),false,false,Value(None,None)))) from Actor[akka://language-server/deadLetters]
[DEBUG] [2024-10-03T15:27:39.174] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((7ccf842b-13c5-4a45-8eb1-ffc3b520b7ab,Some(Standard.Builtins.Main.Unresolved_Symbol)))]
[TRACE] [2024-10-03T15:27:39.174] [org.enso.languageserver.runtime.ContextRegistry] received handled ExpressionUpdates(4f4f849b-994c-43cb-bb5b-1a2221124c81,Set(ExpressionUpdate(7ccf842b-13c5-4a45-8eb1-ffc3b520b7ab,Some(Standard.Builtins.Main.Unresolved_Symbol),None,Vector(ExecutionTime(628)),false,false,Value(None,None)))) from Actor[akka://language-server/deadLetters]
[TRACE] [2024-10-03T15:27:39.177] [enso.org.enso.interpreter.service.ExecutionService] ON_COMPUTED a44a0570-8842-4799-88dd-d497354517bf
[DEBUG] [2024-10-03T15:27:39.184] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((a44a0570-8842-4799-88dd-d497354517bf,Some(Standard.Base.Panic.Panic)))]
[TRACE] [2024-10-03T15:27:39.184] [org.enso.languageserver.runtime.ContextRegistry] received handled ExpressionUpdates(4f4f849b-994c-43cb-bb5b-1a2221124c81,Set(ExpressionUpdate(a44a0570-8842-4799-88dd-d497354517bf,Some(Standard.Base.Panic.Panic),Some(MethodCall(MethodPointer(Standard.Base.Any,Standard.Base.Any.Any,to),Vector())),Vector(ExecutionTime(2830800)),false,true,Panic(Could not find a conversion from `sleep interrupted` to `Table`.,List(a44a0570-8842-4799-88dd-d497354517bf))))) from Actor[akka://language-server/deadLetters]
[TRACE] [2024-10-03T15:27:39.185] [enso.org.enso.interpreter.service.ExecutionService] ON_COMPUTED 1d7022cd-ddaf-49ff-a5d7-be43b4204cbc
[DEBUG] [2024-10-03T15:27:39.185] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((1d7022cd-ddaf-49ff-a5d7-be43b4204cbc,Some(Standard.Base.Nothing.Nothing)))]
[TRACE] [2024-10-03T15:27:39.185] [org.enso.languageserver.runtime.ContextRegistry] received handled ExpressionUpdates(4f4f849b-994c-43cb-bb5b-1a2221124c81,Set(ExpressionUpdate(1d7022cd-ddaf-49ff-a5d7-be43b4204cbc,Some(Standard.Base.Nothing.Nothing),None,Vector(ExecutionTime(11234723)),false,false,Value(None,None)))) from Actor[akka://language-server/deadLetters]
[TRACE] [2024-10-03T15:27:39.186] [enso.org.enso.interpreter.service.ExecutionService] ON_COMPUTED 665475e2-f1ad-4254-bd68-88f52e023f53
[DEBUG] [2024-10-03T15:27:39.186] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((665475e2-f1ad-4254-bd68-88f52e023f53,Some(Standard.Base.Panic.Panic)))]
[TRACE] [2024-10-03T15:27:39.186] [org.enso.languageserver.runtime.ContextRegistry] received handled ExpressionUpdates(4f4f849b-994c-43cb-bb5b-1a2221124c81,Set(ExpressionUpdate(665475e2-f1ad-4254-bd68-88f52e023f53,Some(Standard.Base.Panic.Panic),None,Vector(ExecutionTime(54201)),false,true,Panic(Could not find a conversion from `sleep interrupted` to `Table`.,List(a44a0570-8842-4799-88dd-d497354517bf))))) from Actor[akka://language-server/deadLetters]
[TRACE] [2024-10-03T15:27:39.187] [enso.org.enso.interpreter.service.ExecutionService] ON_COMPUTED 5ac928f6-4b2e-4bce-aa33-dc2da43df995
```
