### ISSUE TITLE
Parser NPE

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11104]
Separated from #11088 because @JaroslavTulach thinks they are two different tasks.

```
[ERROR] [2024-09-16T13:09:44.410] [enso.org.enso.compiler.Compiler] Encountered a critical failure while parsing module
java.nio.BufferUnderflowException: null
        at java.base/java.nio.Buffer.nextGetIndex(Buffer.java:721)
        at java.base/java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:753)
        at org.enso.syntax/org.enso.syntax2.Message.get32(Message.java:24)
        at org.enso.syntax/org.enso.syntax2.Warning.deserialize(Warning.java:34)
        at org.enso.syntax/org.enso.syntax2.Tree.deserialize(Tree.java:85)
        at org.enso.syntax/org.enso.syntax2.Parser.parse(Parser.java:134)
        at org.enso.runtime/org.enso.compiler.core.EnsoParser.parse(EnsoParser.java:38)
        at org.enso.runtime/org.enso.compiler.Compiler.uncachedParseModule(Compiler.scala:602)
        at org.enso.runtime/org.enso.compiler.Compiler.parseModule(Compiler.scala:568)
        at org.enso.runtime/org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$1(Compiler.scala:247)
        at org.enso.runtime/org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$1$adapted(Compiler.scala:245)
        at org.enso.runtime/scala.collection.immutable.List.foreach(List.scala:333)
        at org.enso.runtime/org.enso.compiler.Compiler.runCompilerPipeline(Compiler.scala:245)
        at org.enso.runtime/org.enso.compiler.Compiler.go$1(Compiler.scala:229)
        at org.enso.runtime/org.enso.compiler.Compiler.runInternal(Compiler.scala:236)
        at org.enso.runtime/org.enso.compiler.Compiler.run(Compiler.scala:127)
```

Not sure if related but here is another one that has been encountered on the same project:
![image](https://github.com/user-attachments/assets/d9f9c991-01e4-42f7-9526-48c1dcd4423b)

**Comment by farmaazon** [comment]
Do you know the exact code parsed which gives this exception? It would be extremely helpful in debugging

**Comment by hubertp** [comment]
> Do you know the exact code parsed which gives this exception? It would be extremely helpful in debugging

No. @jdunkerley was fiddling with widgets so it might have been related to that. But he was unable to reproduce consistently.

**Comment by JaroslavTulach** [comment]
> Do you know the exact code parsed which gives this exception? 

@hubertp, can the `org.enso.runtime/org.enso.compiler.core.EnsoParser.parse(EnsoParser.java:38)` code catch the exception and log the code that's being parsed into the log file?

> It would be extremely helpful in debugging

+1

**Comment by hubertp** [comment]
> > Do you know the exact code parsed which gives this exception?
> 
> @hubertp, can the `org.enso.runtime/org.enso.compiler.core.EnsoParser.parse(EnsoParser.java:38)` code catch the exception and log the code that's being parsed into the log file?

https://github.com/enso-org/enso/pull/11092 Ahead of you.

**Comment by kazcw** [comment]
This seems to have the same root cause as #11121.
