### ISSUE TITLE
`Error executing ExecuteJob` in local project

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#11100]
(In Enso 2024.4.1-rc7)

```
[ERROR] [2024-09-16T16:07:44.529] [enso.org.enso.interpreter.service.ExecutionService] Error executing ExecuteJob(contextId=35da8c7f-a15d-41c2-b7a3-7e38de445562)
java.lang.NullPointerException: Cannot invoke "String.length()" because "x" is null
        at org.enso.runtime/com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeVal(JsonWriter.scala:440)
        at org.enso.runtime/org.enso.polyglot.runtime.serde.ApiSerde$$anon$1.e113(ApiSerde.scala:21)
        at org.enso.runtime/org.enso.polyglot.runtime.serde.ApiSerde$$anon$1.e111(ApiSerde.scala:21)
        at org.enso.runtime/org.enso.polyglot.runtime.serde.ApiSerde$$anon$1.e110(ApiSerde.scala:21)
```
[NewProject1.tgz](https://github.com/user-attachments/files/17019532/NewProject1.tgz)

[enso-project-manager-2024-09-16.0.log](https://github.com/user-attachments/files/17019476/enso-project-manager-2024-09-16.0.log)
[2024-09-16T20-07-32.005Z-ide-2024.4.1-rc7.log](https://github.com/user-attachments/files/17019478/2024-09-16T20-07-32.005Z-ide-2024.4.1-rc7.log)

**Comment by hubertp** [comment]
Looks like my PR did it.
