### ISSUE TITLE
Race condition during shutdown

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11232]
Fairly regularly one can see backend complaing during shutdown suggesting some kind of a race condition for services' shutdown:
```
[DEBUG] [2024-10-02T11:09:10.317] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((20b85fb1-5293-4b61-ad36-f4875bb8da30,Some(Standard.Base.Nothing.Nothing)))]
[DEBUG] [2024-10-02T11:09:10.318] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((f0b97114-3fa9-4a89-ad45-7466109716c8,Some(Standard.Base.Nothing.Nothing)))]
[DEBUG] [2024-10-02T11:09:10.320] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((21e49ea9-dcb5-4271-9205-bd04e1d641e8,Some(Standard.Base.Nothing.Nothing)))]
[DEBUG] [2024-10-02T11:09:10.320] [org.enso.languageserver.search.SuggestionsHandler] Received expression updates [Set((8ee3a617-1510-410e-b902-4a2de4f2ceb2,Some(Standard.Base.Nothing.Nothing)))]
[DEBUG] [2024-10-02T11:09:10.334] [enso.org.enso.interpreter.service.ExecutionService] Job ExecuteJob(contextId=63ecb781-9ed2-4039-b795-c60b0c3c93b6) finished in 106 ms.
[DEBUG] [2024-10-02T11:09:10.334] [enso.org.enso.interpreter.service.ExecutionService] Command AttachVisualizationCmd(visualizationId: 681c36eb-bf82-4ac1-8d81-af0212e298e9,expressionId=88fc5a48-5a88-4abb-b9f8-a6714ae5ae7a) finished.
[DEBUG] [2024-10-02T11:09:17.369] [org.enso.jsonrpc.MessageHandlerSupervisor] started (org.enso.jsonrpc.MessageHandlerSupervisor@3ea5f766)
[DEBUG] [2024-10-02T11:09:17.369] [org.enso.jsonrpc.MessageHandlerSupervisor] now supervising Actor[akka://language-server/user/message-handler-supervisor-4c0a8c95-569d-4b10-8c32-853319a12aa8/message-handler-94655703-6e0c-4e64-af02-b2c1f2b7dacc#-315288198]
[DEBUG] [2024-10-02T11:09:17.369] [org.enso.jsonrpc.MessageHandler] started (org.enso.jsonrpc.MessageHandler@64a69fe0)
[DEBUG] [2024-10-02T11:09:17.370] [org.enso.languageserver.protocol.json.JsonConnectionController] started (org.enso.languageserver.protocol.json.JsonConnectionController@6f81bc49)
[DEBUG] [2024-10-02T11:09:17.371] [org.enso.languageserver.protocol.json.JsonConnectionController] now watched by Actor[akka://language-server/system/eventStreamUnsubscriber-1#1522466027]
[DEBUG] [2024-10-02T11:09:17.381] [org.enso.jsonrpc.MessageHandlerSupervisor] now watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$O#-1934203730]
[DEBUG] [2024-10-02T11:09:17.386] [org.enso.languageserver.protocol.json.JsonConnectionController] now supervising Actor[akka://language-server/user/json-connection-controller-94655703-6e0c-4e64-af02-b2c1f2b7dacc/$a#34293558]
[DEBUG] [2024-10-02T11:09:17.386] [org.enso.languageserver.requesthandler.monitoring.PingHandler] started (org.enso.languageserver.requesthandler.monitoring.PingHandler@21a8b08d)
[DEBUG] [2024-10-02T11:09:17.387] [org.enso.languageserver.requesthandler.monitoring.PingHandler] stopped
[DEBUG] [2024-10-02T11:09:17.389] [org.enso.jsonrpc.MessageHandler] stopped
[DEBUG] [2024-10-02T11:09:17.389] [org.enso.languageserver.protocol.json.JsonConnectionController] stopped
[DEBUG] [2024-10-02T11:09:17.391] [org.enso.jsonrpc.MessageHandlerSupervisor] no longer watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$O#-1934203730]
[DEBUG] [2024-10-02T11:09:32.366] [org.enso.jsonrpc.MessageHandlerSupervisor] started (org.enso.jsonrpc.MessageHandlerSupervisor@31670f38)
[DEBUG] [2024-10-02T11:09:32.366] [org.enso.jsonrpc.MessageHandler] started (org.enso.jsonrpc.MessageHandler@2b58dc68)
[DEBUG] [2024-10-02T11:09:32.367] [org.enso.jsonrpc.MessageHandlerSupervisor] now supervising Actor[akka://language-server/user/message-handler-supervisor-59dad8c6-3d51-424e-a047-08b67ae766b5/message-handler-ac0248b6-d86d-41aa-a7a2-d9140b0d7ae9#-1827629686]
[DEBUG] [2024-10-02T11:09:32.368] [org.enso.languageserver.protocol.json.JsonConnectionController] started (org.enso.languageserver.protocol.json.JsonConnectionController@3fcac49a)
[DEBUG] [2024-10-02T11:09:32.368] [org.enso.languageserver.protocol.json.JsonConnectionController] now watched by Actor[akka://language-server/system/eventStreamUnsubscriber-1#1522466027]
[DEBUG] [2024-10-02T11:09:32.375] [org.enso.jsonrpc.MessageHandlerSupervisor] now watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$R#19498854]
[DEBUG] [2024-10-02T11:09:32.380] [org.enso.languageserver.protocol.json.JsonConnectionController] now supervising Actor[akka://language-server/user/json-connection-controller-ac0248b6-d86d-41aa-a7a2-d9140b0d7ae9/$a#1342199026]
[DEBUG] [2024-10-02T11:09:32.380] [org.enso.languageserver.requesthandler.monitoring.PingHandler] started (org.enso.languageserver.requesthandler.monitoring.PingHandler@7759e395)
[DEBUG] [2024-10-02T11:09:32.380] [org.enso.languageserver.requesthandler.monitoring.PingHandler] stopped
[DEBUG] [2024-10-02T11:09:32.384] [org.enso.jsonrpc.MessageHandlerSupervisor] no longer watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$R#19498854]
[DEBUG] [2024-10-02T11:09:32.384] [org.enso.jsonrpc.MessageHandler] stopped
[DEBUG] [2024-10-02T11:09:32.384] [org.enso.languageserver.protocol.json.JsonConnectionController] stopped
[INFO] [2024-10-02T11:09:41.091] [org.enso.languageserver.boot.LanguageServerApp] Stopping Language Server: stopped by the user
[DEBUG] [2024-10-02T11:09:41.092] [org.enso.jsonrpc.MessageHandlerSupervisor] no longer watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$p#1820090680]
[INFO] [2024-10-02T11:09:41.093] [org.enso.languageserver.protocol.json.JsonConnectionController] Session terminated [55a5052e-532a-4b13-bcc4-df593130359b].
[DEBUG] [2024-10-02T11:09:41.094] [org.enso.jsonrpc.MessageHandler] stopped
[DEBUG] [2024-10-02T11:09:41.094] [org.enso.jsonrpc.MessageHandlerSupervisor] no longer watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$r#-495164438]
[DEBUG] [2024-10-02T11:09:41.094] [org.enso.jsonrpc.MessageHandler] stopped
[DEBUG] [2024-10-02T11:09:41.103] [org.enso.languageserver.runtime.RuntimeKiller] Shutting down the runtime server [Actor[akka://language-server/user/runtime-connector#-704117288]]
[DEBUG] [2024-10-02T11:09:41.106] [org.enso.languageserver.protocol.json.JsonConnectionController] stopped
[DEBUG] [2024-10-02T11:09:41.106] [org.enso.languageserver.protocol.json.JsonConnectionController] stopped
[INFO] [2024-10-02T11:09:41.110] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Connection closed [127.0.0.1:35646].
[DEBUG] [2024-10-02T11:09:41.117] [org.enso.languageserver.protocol.binary.BinaryConnectionController] no longer watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$z#-1504895422]
[DEBUG] [2024-10-02T11:09:41.117] [org.enso.languageserver.filemanager.PathWatcher] stopped
[DEBUG] [2024-10-02T11:09:41.117] [org.enso.languageserver.text.CollaborativeBuffer] stopped
[DEBUG] [2024-10-02T11:09:41.117] [org.enso.languageserver.protocol.binary.BinaryConnectionController] stopped
[DEBUG] [2024-10-02T11:09:41.119] [org.enso.jsonrpc.MessageHandlerSupervisor] no longer watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$t#1741665916]
[DEBUG] [2024-10-02T11:09:41.121] [org.enso.jsonrpc.MessageHandlerSupervisor] no longer watched by Actor[akka://language-server/system/Materializers/StreamSupervisor-0/$$w#-2039876140]
[DEBUG] [2024-10-02T11:09:41.121] [org.enso.jsonrpc.MessageHandler] stopped
[INFO] [2024-10-02T11:09:41.121] [org.enso.languageserver.protocol.json.JsonConnectionController] Session terminated [119073c4-fcae-44ee-bd20-3bae867616ca].
[DEBUG] [2024-10-02T11:09:41.121] [org.enso.jsonrpc.MessageHandler] stopped
[DEBUG] [2024-10-02T11:09:41.121] [org.enso.languageserver.protocol.json.JsonConnectionController] stopped
[DEBUG] [2024-10-02T11:09:41.121] [org.enso.languageserver.filemanager.PathWatcher] stopped
[DEBUG] [2024-10-02T11:09:41.126] [org.enso.languageserver.protocol.json.JsonConnectionController] stopped
[DEBUG] [2024-10-02T11:09:41.131] [org.enso.languageserver.runtime.handler.DestroyContextHandler] started (org.enso.languageserver.runtime.handler.DestroyContextHandler@e91c49e)
[DEBUG] [2024-10-02T11:09:41.136] [org.enso.languageserver.runtime.ContextEventsListener] stopped
[DEBUG] [2024-10-02T11:09:41.139] [org.enso.languageserver.runtime.ContextRegistry] now supervising Actor[akka://language-server/user/context-registry/$L#1637037001]
[DEBUG] [2024-10-02T11:09:41.141] [org.enso.languageserver.runtime.RuntimeConnector] Starting the runtime connector
[ERROR] [2024-10-02T11:09:41.142] [akka.actor.OneForOneStrategy] Task java.util.concurrent.CompletableFuture$AsyncSupply@1f1d5bd2 rejected from java.util.concurrent.ThreadPoolExecutor@83e51f1[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@1f1d5bd2 rejected from java.util.concurrent.ThreadPoolExecutor@83e51f1[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2081)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:841)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1376)
	at scala.library@2.13.11/scala.concurrent.impl.ExecutionContextImpl.execute(ExecutionContextImpl.scala:21)
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.execution.CommandExecutionEngine.invoke(CommandExecutionEngine.scala:94)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.Handler.onMessage(Handler.scala:77)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.Endpoint.$anonfun$sendBinary$1(Endpoint.scala:60)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.Endpoint.$anonfun$sendBinary$1$adapted(Endpoint.scala:58)
	at scala.library@2.13.11/scala.util.Success.foreach(Try.scala:260)
	at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.Endpoint.sendBinary(Endpoint.scala:58)
	at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.TruffleInstrument$Env$MessageTransportProxy$MessageEndpointProxy.sendBinary(TruffleInstrument.java:1222)
	at org.enso.language.server/org.enso.languageserver.runtime.RuntimeConnector$$anonfun$initialized$1.applyOrElse(RuntimeConnector.scala:92)
	at scala.library@2.13.11/scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at org.enso.logging.utils.akka/org.enso.logging.utils.akka.ActorLoggingReceive.apply(ActorLoggingReceive.scala:35)
	at org.enso.logging.utils.akka/org.enso.logging.utils.akka.ActorLoggingReceive.apply(ActorLoggingReceive.scala:14)
	at scala.library@2.13.11/scala.PartialFunction.applyOrElse(PartialFunction.scala:214)
	at scala.library@2.13.11/scala.PartialFunction.applyOrElse$(PartialFunction.scala:213)
	at org.enso.logging.utils.akka/org.enso.logging.utils.akka.ActorLoggingReceive.applyOrElse(ActorLoggingReceive.scala:14)
	at scala.library@2.13.11/scala.PartialFunction$Combined.applyOrElse(PartialFunction.scala:305)
	at org.enso.akka.wrapper/akka.actor.Actor.aroundReceive(Actor.scala:537)
	at org.enso.akka.wrapper/akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at org.enso.language.server/org.enso.languageserver.runtime.RuntimeConnector.aroundReceive(RuntimeConnector.scala:23)
	at org.enso.akka.wrapper/akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at org.enso.akka.wrapper/akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at org.enso.akka.wrapper/akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at org.enso.akka.wrapper/akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at org.enso.akka.wrapper/akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
[DEBUG] [2024-10-02T11:09:41.142] [org.enso.languageserver.runtime.RuntimeConnector] restarting
[DEBUG] [2024-10-02T11:09:41.142] [org.enso.languageserver.runtime.RuntimeConnector] restarted
[ERROR] [2024-10-02T11:09:46.122] [org.enso.languageserver.runtime.RuntimeKiller] Disposal of runtime resources timed out
[DEBUG] [2024-10-02T11:09:46.122] [org.enso.languageserver.runtime.RuntimeKiller] Shutting down the Truffle context. Attempt #1
[DEBUG] [2024-10-02T11:09:46.129] [enso.org.enso.interpreter.runtime.SerializationPool] Serialization manager shutdownNow.
[DEBUG] [2024-10-02T11:09:46.129] [enso.org.enso.interpreter.runtime.SerializationPool] Serialization manager has been shut down.
[DEBUG] [2024-10-02T11:09:46.135] [org.enso.languageserver.runtime.RuntimeKiller] stopped
[DEBUG] [2024-10-02T11:09:46.136] [org.enso.languageserver.boot.LanguageServerComponent] Terminated Truffle context
[INFO] [2024-10-02T11:09:46.145] [org.enso.languageserver.boot.LanguageServerComponent] Terminated JSON connections
[INFO] [2024-10-02T11:09:46.147] [org.enso.languageserver.boot.LanguageServerComponent] Terminated binary connections
[WARN] [2024-10-02T11:09:46.152] [org.enso.languageserver.runtime.handler.DestroyContextHandler] Failed to receive a [Request(Some(e4d21268-e5aa-40c8-b045-9a0603a2e988),DestroyContextRequest(63ecb781-9ed2-4039-b795-c60b0c3c93b6))] response in [5 seconds]. Retrying.
[DEBUG] [2024-10-02T11:09:46.172] [org.enso.languageserver.monitoring.IdlenessMonitor] stopped
[DEBUG] [2024-10-02T11:09:46.172] [org.enso.languageserver.capability.CapabilityRouter] stopped
```

**Comment by JaroslavTulach** [comment]
Not seen in a while.
