### ISSUE TITLE
Allow to execute Y.js and Insight together 

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#11477]
Since the implementation of [reload insight script on file change](https://github.com/enso-org/enso/pull/11415#issuecomment-2453902666) we have a nice and comfortable way to execute **Enso Insight** scripts like [Detect Assign Statements](https://github.com/enso-org/enso/pull/11385#issuecomment-2431344514) in the IDE and observe how engine executes the code.

The next step is to **connect Y.js and Insight** together. Let's do it like this:

- modify [ContextInsightSetup](https://github.com/enso-org/enso/blob/2bbd90970547eed11b4c52f5b73c0bac785379f3/engine/common/src/main/java/org/enso/common/ContextInsightSetup.java#L170) to emulate _necessary JS environment_
- the [emulation has already been written](https://github.com/enso-org/enso/blob/2bbd90970547eed11b4c52f5b73c0bac785379f3/lib/java/ydoc-server/src/main/java/org/enso/ydoc/polyfill/web/WebEnvironment.java) and is part of `ydoc-server` module.
- make sure the **emulation is also initialized** in `ContextInsightSetup` via the `epb` language:

```java
    var epbSrc =
        Source.newBuilder("epb", path.toFile())
            .content("js:0#" + codeToExecute)
            .build();
```

It is essential to use `epb` language as it sets a proper [inner context for JavaScript](https://github.com/enso-org/enso/blob/2bbd90970547eed11b4c52f5b73c0bac785379f3/engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/ForeignEvalNode.java#L107) rather than trying to execute JavaScript directly (as it is not ready for multi threaded access).

- all of the above has been **solved** by #11822
- we just **need a demo**:

At the end please demonstrate how a simple script showing co-operation between Enso Insight and Y.js structures can be created and used in the IDE via `-Denso.dev.insight` property.

**Comment by JaroslavTulach** [comment]
@Frizi, @4e6 I guess it is time to specify what:

> demonstrate how a simple script showing co-operation

shall mean?  I've just tried `2024.5.1-nightly.2024.12.10` version:
- if I perform `sbt ydoc-server/test`
- a new file `./lib/java/ydoc-server/target/classes/org/enso/ydoc/server/ydoc.cjs` gets created
- I assume that's the script we want to execute to demonstrate Y-doc server can run together with Insight
- thus we shall [follow the tutorial](https://github.com/enso-org/enso/pull/11415#issuecomment-2453902666) and just set `ENSO_JVM_OPTS=-Denso.dev.insight=$ENSO_ROOT/lib/java/ydoc-server/target/classes/org/enso/ydoc/server/ydoc.cjs`

Is that correct assumption guys? Then the whole script would be:
```bash
enso$ sbt ydoc-server/test
enso$ export ENSO_JVM_OPTS=-Denso.dev.insight=`pwd`/lib/java/ydoc-server/target/classes/org/enso/ydoc/server/ydoc.cjs
enso$ sbt runProjectManagerDistribution
```
and launching IDE in another terminal as `corepack pnpm run dev:gui`.

**Comment by JaroslavTulach** [comment]
With `2024.5.1-nightly.2024.12.10` the above steps fail with:
```
[ERROR] [2024-12-10T08:07:51.962] [org.enso.languageserver.protocol.json.JsonConnectionController] Failed to initialize resources.
java.util.concurrent.CompletionException: org.graalvm.polyglot.PolyglotException: ReferenceError: crypto is not defined
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
        at org.enso.akka.wrapper/akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: org.graalvm.polyglot.PolyglotException: ReferenceError: crypto is not defined
        at <js>.poly_enso_eval(ydoc.cjs:3858)
        at <epb>.(Unknown)
        at org.graalvm.polyglot/org.graalvm.polyglot.Context.initialize(Context.java:579)
        at org.enso.language.server/org.enso.languageserver.boot.resource.TruffleContextInitialization.initComponent(TruffleContextInitialization.java:47)
        at org.enso.language.server/org.enso.languageserver.boot.resource.LockedInitialization.lambda$init$0(LockedInitialization.java:37)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
```
We need to modify [ContextInsightSetup](https://github.com/enso-org/enso/blob/2bbd90970547eed11b4c52f5b73c0bac785379f3/engine/common/src/main/java/org/enso/common/ContextInsightSetup.java#L170) to emulate necessary JS environment as provided by `ydoc-polyfill`.

- #11822 

Created a #11822 PR to turn on the `ydoc-polyfill`.

**Comment by JaroslavTulach** [comment]
Once I asked _Where is the (type script?) code representing an AST element? Is there information about offset/length? What code needs to be added lib/java/ydoc-server/target/classes/org/enso/ydoc/server/ydoc.cjs to print all AST that shall be updated with expressionUpdates and their offset/length? Having a diff doing this printing would be a good entry point for me._

**Comment by 4e6** [comment]
I was not able to get enough information from the insight script to prepare update messages that could be exchanged with GUI. For example,

```js
insight.on("return", function(ctx, frame) {
  print(`[return] ctx='${JSON.stringify(ctx)}'`)
  print(`[return] frame='${JSON.stringify(frame)}'`)
}, {
  expressions: true,
  statements: true,
  roots: true,
  rootNameFilter: ".*main"
});
```
#### `ctx`

```json
{
   "name":"local.NewProject1.Main::local.NewProject1.Main::main",
   "source":{
      "characters":"from Standard.Base import all\nfrom Standard.Table import all\nfrom Standard.Database import all\nfrom Standard.AWS import all\nfrom Standard.Google_Api import all\nfrom Standard.Snowflake import all\nimport Standard.Examples\nimport Standard.Visualization\n\n## ICON group\nfirst_column file1 =\n    vector1 = file1.column_names\n    any1 = vector1.first\n    any1\n\nmain =\n    file1 = Data.read Examples.welcome\n    any1 = Main.first_column file1\n    any3 = file1.at 'Column 1'\n\n\n\n#### METADATA ####\n[[{\"index\":{\"value\":278},\"size\":{\"value\":5}},\"b9b7d881-fed9-49cc-a3c0-feb247635f89\"],[{\"index\":{\"value\":300},\"size\":{\"value\":18}},\"2bbf7b4a-6866-4783-a793-22b72c1d5161\"],[{\"index\":{\"value\":330},\"size\":{\"value\":13}},\"c3dedc01-bbbc-4660-9dad-7a0f5f50d59a\"],[{\"index\":{\"value\":348},\"size\":{\"value\":4}},\"17961ddd-0306-4c20-a7f5-82eace2f7e5e\"],[{\"index\":{\"value\":373},\"size\":{\"value\":26}},\"fcf199e6-d2b1-44b7-be92-a47545d6a593\"],[{\"index\":{\"value\":411},\"size\":{\"value\":23}},\"3d29652c-e20c-4436-addb-1060cc55013a\"],[{\"index\":{\"value\":446},\"size\":{\"value\":8}},\"fce3a9bd-d7c7-40d9-887c-eceb0ee25240\"],[{\"index\":{\"value\":446},\"size\":{\"value\":19}},\"dfc7341d-aba3-49c6-be18-f5f9e5562d83\"]]\n{\"ide\":{\"node\":{\"b9b7d881-fed9-49cc-a3c0-feb247635f89\":{\"position\":{\"vector\":[-388,282]}},\"2bbf7b4a-6866-4783-a793-22b72c1d5161\":{\"position\":{\"vector\":[-388,210]}},\"c3dedc01-bbbc-4660-9dad-7a0f5f50d59a\":{\"position\":{\"vector\":[-388,138]}},\"17961ddd-0306-4c20-a7f5-82eace2f7e5e\":{\"position\":{\"vector\":[-388,66]}},\"fcf199e6-d2b1-44b7-be92-a47545d6a593\":{\"position\":{\"vector\":[-388,282]},\"visualization\":{\"show\":false,\"width\":1027.671875,\"height\":193}},\"3d29652c-e20c-4436-addb-1060cc55013a\":{\"position\":{\"vector\":[-443,177]}},\"dfc7341d-aba3-49c6-be18-f5f9e5562d83\":{\"position\":{\"vector\":[-145,177]}},\"fce3a9bd-d7c7-40d9-887c-eceb0ee25240\":{\"position\":{\"vector\":[-145,177]}}},\"widget\":{},\"import\":{},\"snapshot\":\"eJx9kD0LwjAQhvf8igMHt4A4O/iFOKhDRcdytokEL7mSplb99ba2FotopiTPk/deoj1biAK6FH0qZ5grMDZjHwCJhO7RPZ7oD15gwNPfgOkx+g1XzGdS8TQzv53IcakJL70Z7baTlje0Gan8CxxMXiCZBwbDTojBANbz3RbOnotMaOPzECdMhXWgDakRTARU66qSwL46NbeyUWKHthpRC+juNW09+QrqgBAWjWuj2liof0p6hSm8u8pSUcJWfQZuqofyu9ZbGXeNMMBw3hijoXgCQg+d7w==\"}}",
      "name":"local.NewProject1.Main",
      "language":"enso",
      "mimeType":null,
      "uri":"truffle:51f7bf11a1e5144c224e96c1c245f7b479c22bbc0fc4fb757bfe5e72ae5c58b4/local.NewProject1.Main"
   },
   "characters":"main =\n    file1 = Data.read Examples.welcome\n    any1 = Main.first_column file1\n    any3 = file1.at 'Column 1'",
   "line":16,
   "startLine":16,
   "endLine":19,
   "column":1,
   "startColumn":1,
   "endColumn":30,
   "charIndex":354,
   "charLength":111,
   "charEndIndex":465
}
```

#### `frame`

```json
{
   "file1":{},
   "any1":"Column 1",
   "any3":{}
}

**Comment by 4e6** [comment]
If the issue is just about running `ydoc-server` from the insight script, then you can already do it since #11822 by pointing `enso.dev.insight` property to the `ydoc-server-polyglot` artifact:

```
ENSO_JVM_OPTS="-Denso.dev.insight=$(pwd)/app/ydoc-server-polyglot/dist/main.cjs" java -jar project-manager.jar
```

**Comment by JaroslavTulach** [comment]
The goal I'd like to see is:
- modify the `app/ydoc-server-polyglot/dist/main.cjs` to update the AST somehow
- modify the IDE to read/use such updated AST somehow

Btw. Use `ctx.returnValue`: https://www.graalvm.org/jdk20/tools/graalvm-insight/manual/#intercepting-and-altering-execution

<blockquote><img src="/jdk20/resources/img/graalvm.png" width="48" align="right"><div><strong><a href="https://www.graalvm.org/jdk20/tools/graalvm-insight/manual/#intercepting-and-altering-execution">GraalVM</a></strong></div><div>GraalVM is an advanced JDK with ahead-of-time Native Image compilation.</div></blockquote>

**Comment by JaroslavTulach** [comment]
> Added ability to debug JS in Chrome Dev Tools.

Do you mean something other than `enso --inspect` which has already been working?
