### ISSUE TITLE
Remove cycles from IR by migrating the type inference pass to use the `StaticModuleScope` metadata instead of `BindingsMap`

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#11509]
In #11399 I'm introducing `StaticModuleScope` needed to be able to resolve method calls on atoms. It has some resemblance to `BindingsMap` but it is a bit 'higher-level' - instead of holding raw IR expressions, it contains type representations that are not part of raw IR. It was needed to reflect the runtime `ModuleScope`. 

Since it's available, the resolution of atom constructors in type propagation could also rely on `StaticModuleScope` instead of `BindingsMap`. This will allow us to remove the added `typReference` expression from `Argument` type which will get rid of a problematic cycle in the IR. This should then fix an issue with `duplicate` that does not like cycles in the IR.

**Comment by JaroslavTulach** [comment]
I am facing the "cycle in IR" problem while working on
- #11171

The cycle goes from `Argument` an cycles thru:
```
[error]     at org.enso.compiler.core.ir.Name$Literal.duplicate(Name.scala:531)
[error]     at org.enso.compiler.core.ir.Name$Literal.duplicate(Name.scala:474)
[error]     at org.enso.compiler.pass.resolve.TypeSignatures$Signature.duplicate(TypeSignatures.scala:369)
[error]     at org.enso.compiler.core.ir.MetadataStorage.duplicate(MetadataStorage.java:98)
[error]     at org.enso.compiler.core.ir.Name$Literal.duplicate(Name.scala:531)
[error]     at org.enso.compiler.core.ir.Name$Literal.duplicate(Name.scala:474)
```

**Comment by radeusgd** [comment]
> This will allow us to remove the added `typReference` expression from `Argument` type which will get rid of a problematic cycle in the IR. This should then fix an issue with `duplicate` that does not like cycles in the IR.

The cycle has already been removed in #11399.

The `TypeResolver` still references the `BidningsMap` but I don't think these references can be easily replaced with `StaticModuleScope`.

The `TypeResolver` looks for 'what type this identifier refers to' which is exactly what `BindingsMap` solves.

`StaticModuleScope` only solves 'what signature does method `foo` on type `Typ` have'.

So they solve slightly different cases. I think the cases that should have been moved to `StaticModuleScope` have already been moved and the remaining usages seem correct, so the issue may be closed.
