### ISSUE TITLE
Console warning on project startup

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11652]
```
storeHooks.ts:111 Warning: Cannot update a component (`RealAssetRow2`) while rendering a different component (`AssetsTable`). To locate the bad setState() call inside `AssetsTable`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at AssetsTable (http://localhost:5173/src/dashboard/layouts/AssetsTable.tsx:213:5)
    at div
    at div
    at div
    at Drive (http://localhost:5173/src/dashboard/layouts/Drive.tsx:42:13)
    at $64fa3d84918910a7$export$2881499e37b75b9a (http://localhost:5173/@fs/home/hubert/work/repos/enso/enso/node_modules/.cache/vite/deps/react-aria-components.js?v=5f159f29:1063:54)
    at div
    at Wrapper (http://localhost:5173/@fs/home/hubert/work/repos/enso/enso/node_modules/.cache/vite/deps/react-aria-components.js?v=5f159f29:835:49)
    at $e1995378a142960e$export$fb8073518f34e6ec (http://localhost:5173/@fs/home/hubert/work/repos/enso/enso/node_modules/.cache/vite/deps/react-aria-components.js?v=5f159f29:976:42)
    at DashboardTabPanels (http://localhost:5173/src/dashboard/pages/dashboard/DashboardTabPanels.tsx:29:13)
    at $64fa3d84918910a7$export$2881499e37b75b9a (http://localhost:5173/@fs/home/hubert/work/repos/enso/enso/node_modules/.cache/vite/deps/react-aria-components.js?v=5f159f29:1063:54)
    at div
    at $5e8ad37a45e1c704$var$TabsInner (http://localhost:5173/@fs/home/hubert/work/repos/enso/enso/node_modules/.cache/vite/deps/react-aria-components.js?v=5f159f29:12352:44)
    at $e1995378a142960e$var$CollectionInner (http://localhost:5173/@fs/home/hubert/work/repos/enso/enso/node_modules/.cache/vite/deps/react-aria-components.js?v=5f159f29:864:50)
    at $e1995378a142960e$export$bf788dd355e3a401 (http://localhost:5173/@fs/home/hubert/work/repos/enso/enso/node_modules/.cache/vite/deps/react-aria-components.js?v=5f159f29:853:42)
```

**Comment by MrFlashAccount** [comment]
Not a bug, but adds extra noise to console.

**Comment by PabloBuchu** [comment]
@MrFlashAccount I am reassigning this on you. Please take a look once you have some free time
