### ISSUE TITLE
Spurious test failure in ReceivesTreeUpdatesHandlerTest

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11667]
```
Error: de_ci::program::command: sbt ℹ️ [ERROR] [2024-11-26 13:00:06,001] [org.enso.languageserver.filemanager.PathWatcher] Failed to initialize path watcher for path [Path(0ccef028-b252-4034-befe-e949847cca6e,Vector())]. {}
 INFO ide_ci::program::command: sbt ℹ️ java.util.concurrent.TimeoutException: Future timed out after [5 seconds]
 INFO ide_ci::program::command: sbt ℹ️ 	at scala.library@2.13.11/scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
 INFO ide_ci::program::command: sbt ℹ️ 	at scala.library@2.13.11/scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
 INFO ide_ci::program::command: sbt ℹ️ 	at scala.library@2.13.11/scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:104)
 INFO ide_ci::program::command: sbt ℹ️ 	at scala.library@2.13.11/scala.concurrent.Await$.$anonfun$ready$1(package.scala:174)
 INFO ide_ci::program::command: sbt ℹ️ 	at scala.library@2.13.11/scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
 INFO ide_ci::program::command: sbt ℹ️ 	at scala.library@2.13.11/scala.concurrent.Await$.ready(package.scala:124)
 INFO ide_ci::program::command: sbt ℹ️ 	at org.enso.language.server/org.enso.languageserver.filemanager.PathWatcher$$anonfun$uninitializedStage$1.$anonfun$applyOrElse$12(PathWatcher.scala:91)
 INFO ide_ci::program::command: sbt ℹ️ 	at scala.library@2.13.11/scala.util.Try$.apply(Try.scala:210)
 INFO ide_ci::program::command: sbt ℹ️ 	at org.enso.language.server/org.enso.languageserver.filemanager.PathWatcher$$anonfun$uninitializedStage$1.applyOrElse(PathWatcher.scala:91)
 INFO ide_ci::program::command: sbt ℹ️ 	at org.enso.akka.wrapper/akka.actor.Actor.aroundReceive(Actor.scala:537)
 INFO ide_ci::program::command: sbt ℹ️ 	at org.enso.akka.wrapper/akka.actor.Actor.aroundReceive$(Actor.scala:535)
 INFO ide_ci::program::command: sbt ℹ️ 	at org.enso.language.server/org.enso.languageserver.filemanager.PathWatcher.aroundReceive(PathWatcher.scala:40)
 INFO ide_ci::program::command: sbt ℹ️ 	at org.enso.akka.wrapper/akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
 INFO ide_ci::program::command: sbt ℹ️ 	at org.enso.akka.wrapper/akka.actor.ActorCell.invoke(ActorCell.scala:547)
 INFO ide_ci::program::command: sbt ℹ️ 	at org.enso.akka.wrapper/akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
 INFO ide_ci::program::command: sbt ℹ️ 	at org.enso.akka.wrapper/akka.dispatch.Mailbox.run(Mailbox.scala:231)
 INFO ide_ci::program::command: sbt ℹ️ 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
 INFO ide_ci::program::command: sbt ℹ️ 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
 INFO ide_ci::program::command: sbt ℹ️ 	at java.base/java.lang.Thread.run(Thread.java:1583)
 INFO ide_ci::program::command: sbt ℹ️ [info] - must fail to acquire capability if directory doesn't exist *** FAILED *** (5 seconds, 10 milliseconds)
 INFO ide_ci::program::command: sbt ℹ️ [info]   java.util.ConcurrentModificationException:
 INFO ide_ci::program::command: sbt ℹ️ [info]   at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095)
 INFO ide_ci::program::command: sbt ℹ️ [info]   at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049)
 INFO ide_ci::program::command: sbt ℹ️ [info]   at org.enso.logging.service.logback/org.enso.logging.service.logback.MemoryAppender.flush(MemoryAppender.java:42)
 INFO ide_ci::program::command: sbt ℹ️ [info]   at org.enso.testkit.ReportLogsOnFailure.withFixture(ReportLogsOnFailure.scala:39)
 INFO ide_ci::program::command: sbt ℹ️ [info]   at org.enso.testkit.ReportLogsOnFailure.withFixture$(ReportLogsOnFailure.scala:33)
 INFO ide_ci::program::command: sbt ℹ️ [info]   at org.enso.language.server/org.enso.languageserver.websocket.json.ReceivesTreeUpdatesHandlerTest.withFixture(ReceivesTreeUpdatesHandlerTest.scala:7)
 INFO ide_ci::program::command: sbt ℹ️ [info]   at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1238)
 INFO ide_ci::program::command: sbt ℹ️ [info]   at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1250)
 INFO ide_ci::program::command: sbt ℹ️ [info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
 INFO ide_ci::program::command: sbt ℹ️ [info]   at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1250)
 INFO ide_ci::program::command: sbt ℹ️ [info]   ...
 INFO ide_ci::program::command: sbt ℹ️ [info] - must reacquire capability receivesTreeUpdates (44 milliseconds)
 ```
src: https://github.com/enso-org/enso/actions/runs/12029527358/job/33535001571?pr=11595#step:7:5698

**Comment by hubertp** [comment]
Haven't seen those in a while
