### ISSUE TITLE
Switching the select column list of columns over and over causes the backend to fail

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#11678]
Data file: https://drive.google.com/file/d/1OAk3LK-grh6yJAT7xBfz6StM25e-6SJ6/view?usp=drive_link
 
[New Project 33.zip](https://github.com/user-attachments/files/17932967/New.Project.33.zip)

```
[WARN] [2024-11-27T10:40:27.682] [enso.org.enso.interpreter.service.ExecutionService] Encountered exception while waiting on status of pending jobs
java.util.concurrent.CancellationException: null
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:121)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.execution.JobExecutionEngine$ForceJobCancellations.$anonfun$run$2(JobExecutionEngine.scala:107)
        at scala.library@2.13.11/scala.collection.immutable.Vector.foreach(Vector.scala:2122)
        at org.enso.runtime.instrument.common/org.enso.interpreter.instrument.execution.JobExecutionEngine$ForceJobCancellations.run(JobExecutionEngine.scala:91)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:106)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:140)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:131)
        at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:745)
        at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
        at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
        at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
        at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:519)
        at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:500)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:102)
```

Clicking and changing the set of columns seems to make this repeatable.

**Comment by JaroslavTulach** [comment]
@hubertp cannot reproduce.
