### ISSUE TITLE
Missing Case in UFCS Desugaring

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1249]
### General Summary
When trying to call an inline lambda on a value using dot syntax it fails to work.

### Steps to Reproduce

1. Create a file `test.enso` containing the following:

```
from Base import all

main = Debug.breakpoint
```

2. Execute the following:

```
> x = [1,2]
> vis = x -> x.to_json.to_text
```

3. Working case:

```
x.vis
```

4. Broken cases

```
> [1,2].(x -> x.to_json.to_text)
Evaluation failed with: No_Such_Method_Error (Vector org.enso.interpreter.runtime.data.Array@733f1395) UnresolvedSymbol<.>
java.lang.Exception: No_Such_Method_Error (Vector org.enso.interpreter.runtime.data.Array@733f1395) UnresolvedSymbol<.>
Caused by: java.lang.Exception: Attached Guest Language Frames (5)
        at <enso>.<eval>(Unknown Source)
        at <enso>.Debug.breakpoint(Unknown Source)
        at <enso>.test::test.test::main(test.enso:3)
        at <unknown>.org.graalvm.polyglot.Value<Function>.execute(Unknown Source)
```

and

```
> x.(x->x.to_json.to_text)
Evaluation failed with: No_Such_Method_Error (Vector org.enso.interpreter.runtime.data.Array@587f4f63) UnresolvedSymbol<.>
java.lang.Exception: No_Such_Method_Error (Vector org.enso.interpreter.runtime.data.Array@587f4f63) UnresolvedSymbol<.>
Caused by: java.lang.Exception: Attached Guest Language Frames (5)
        at <enso>.<eval>(Unknown Source)
        at <enso>.Debug.breakpoint(Unknown Source)
        at <enso>.test::test.test::main(test.enso:3)
        at <unknown>.org.graalvm.polyglot.Value<Function>.execute(Unknown Source)
```

Please note that both of these cases work with standard function call syntax (`(x -> x.to_json.to_text) [1,2]` and `(x-> x.to_json.to_text) x`).

### Expected Result
They should all be equivalent.

### Actual Result
See above.

### Enso Version

```
Enso Compiler and Runtime
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: wip/ara/lex-text @ 7bb04c6b074106cdbe23ba91dc128286396622d0
Running on: Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation, JDK 11.0.8.0.2+1-LTS-jvmci-20.2-b03
            Mac OS X 10.15.7 (x86_64)
```

**Comment by iamrecursion** [comment]
This issue arises due to the restrictiveness of the `MethodCall` syntax recogniser in `AstView`. It only matches on applications, rather than on any construct.
