### ISSUE TITLE
Matching Atoms with Wrong Number of Fields Exposes Internal Variables

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1470]
### General Summary

As in the title, when a pattern match of a constructor has a wrong number of fields *and* one of the fields is another atom, the printed error includes some internal variables.

### Steps to Reproduce

1. Create a new project
2. Replace `Main.enso` with:
   ```
   from Base import all

   type Foo
       type Foo a b

   hmm : Foo -> Text
   hmm x = case x of
       Foo a Nothing c -> "baz"

   main =
       x = Foo "a" "b"
       y = here.hmm x
       IO.println y
   ```
3. Run it

### Expected Result

It should just report that we are matching a wrong number of fields:
```
Main.enso[8:5-8:19]: Wrong number of fields when matching on Foo. Expected 2 fields, but provided 3.
```

### Actual Result

Besides the expected error, it reports a usage of an undefined internal variable:

```
Main.enso[8:5-8:19]: Wrong number of fields when matching on Foo. Expected 2 fields, but provided 3.
Main.enso: Variable `<internal--683>` is not defined.
```

Full stacktrace:
```
In module Ensobugs.Main:
Compiler encountered errors:
Main.enso[8:5-8:19]: Wrong number of fields when matching on Foo. Expected 2 fields, but provided 3.
Main.enso: Variable `<internal--683>` is not defined.
Exception in thread "main" Compilation aborted due to errors.
	at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:547)
	at org.enso.polyglot.Module.getAssociatedConstructor(Module.scala:15)
	at org.enso.runner.Main$.runMain(Main.scala:386)
	at org.enso.runner.Main$.runPackage(Main.scala:321)
	at org.enso.runner.Main$.run(Main.scala:307)
	at org.enso.runner.Main$.main(Main.scala:558)
	at org.enso.runner.Main.main(Main.scala)
```

### Enso Version

```
Enso Launcher
Version:    0.2.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: enso-0.2.0 @ d2df28bc43fcfee614fb31780cd46a59ebb16127
Built on:   Linux (amd64)
Enso engine from project Ensobugs: 
Enso Compiler and Runtime
Version:    0.2.2-SNAPSHOT
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: wip/rw/database-library* @ 463c47f6d231cfb6fe512cffdcf1245f23062a66
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 4.15.0-135-generic (amd64)
```

**Comment by radeusgd** [comment]
Moved to https://www.pivotaltracker.com/story/show/181935642

<blockquote><div><strong><a href="https://www.pivotaltracker.com/story/show/181935642">Matching Atoms with Wrong Number of Fields Exposes Internal Variables - Pivotal Tracker</a></strong></div></blockquote>
