### ISSUE TITLE
Allow Creation of User Projects with the Name 'Test'

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1558]
### General Summary

If the new project is created with the name `Test`, it clashes with the `Test` module from the std-lib (testing library) with the following error:

```
[info] [2021-03-08T17:35:36.304Z] [org.enso.languageserver.runtime.RuntimeConnector] Engine connection established.
org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: Duplicate key Test.Main (attempted merging values org.enso.interpreter.runtime.Module@7976e536 and org.enso.interpreter.runtime.Module@670a4738)
    at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
    at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
    at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
    at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
    at scala.collection.convert.JavaCollectionWrappers$IteratorWrapper.forEachRemaining(JavaCollectionWrappers.scala:27)
    at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
    at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at org.enso.interpreter.runtime.Context.initialize(Context.java:109)
    at org.enso.interpreter.Language.initializeContext(Language.java:75)
```

### Motivation

`Test` is a common name for a project.

**Comment by iamrecursion** [comment]
I think the two fixes that are needed are:

- We should handle the case where a project name shadows that of an external dependency. The project the user is running in should shadow the dependency. We should emit a warning when this happens.
- We should rename our `Test` library to something a little less prone to clashing with projects that users may use for experimentation. `Spec`, perhaps.
