### ISSUE TITLE
ICE when running a file with no main method defined

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1585]
The following triggers internal compiler error:

```
type x
```

Output:
```
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.NullPointerException
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext$ToHostValueNode.execute(PolyglotLanguageContext.java:859)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractInvokeNode.executeShared(PolyglotValue.java:2158)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$InvokeNode.executeImpl(PolyglotValue.java:2198)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:119)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:550)
        at org.enso.polyglot.Module.getMethod(Module.scala:31)
        at org.enso.runner.Main$.runMain(Main.scala:387)
        at org.enso.runner.Main$.runSingleFile(Main.scala:326)
        at org.enso.runner.Main$.run(Main.scala:309)
        at org.enso.runner.Main$.main(Main.scala:556)
        at org.enso.runner.Main.main(Main.scala)
Original Internal Error:
java.lang.NullPointerException
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext$ToHostValueNode.execute(PolyglotLanguageContext.java:859)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$AbstractInvokeNode.executeShared(PolyglotValue.java:2158)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropCodeCache$InvokeNode.executeImpl(PolyglotValue.java:2198)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:119)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:512)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:496)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:136)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropValue.invoke(PolyglotValue.java:2898)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:550)
        at org.enso.polyglot.Module.getMethod(Module.scala:31)
        at org.enso.runner.Main$.runMain(Main.scala:387)
        at org.enso.runner.Main$.runSingleFile(Main.scala:326)
        at org.enso.runner.Main$.run(Main.scala:309)
        at org.enso.runner.Main$.main(Main.scala:556)
        at org.enso.runner.Main.main(Main.scala)
Caused by: Attached Guest Language Frames (1)
```

### Enso Version
0.2.7

**Comment by mwu-tow** [comment]
I first thought it is due to a name but the following ICEs as well:

```
from Standard.Base import all

type Foo
    type Bar
```

**Comment by mwu-tow** [comment]
Nah, these are actually due to missing `main`.
