### ISSUE TITLE
Null Pointer Exception when using `True && column`

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1599]
### Steps to Reproduce
Run the following 
```
from Standard.Base import all

from Standard.Table.Data.Column import Column

main = 
    c = Column.from_vector "name" [1,2,3]
    IO.println <| True && c
```

### Expected Result
Either result of memberwise `True && _` over column elements or a proper error.
(i.e. about the user code, not some null pointer in depths of java)

### Actual Result
```
Exception in thread "main" java.lang.NullPointerException: Null receiver values are not supported by libraries.
        at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.dispatch(LibraryFactory.java:442)
        at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.create(LibraryFactory.java:290)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.specialize(InteropLibraryGen.java:6983)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.hasMetaObject(InteropLibraryGen.java:6766)
        at org.enso.interpreter.node.expression.builtin.text.util.TypeToDisplayTextNode.doDisplay(TypeToDisplayTextNode.java:58)
        at org.enso.interpreter.node.expression.builtin.text.util.TypeToDisplayTextNodeGen.execute(TypeToDisplayTextNodeGen.java:32)
        at org.enso.interpreter.node.expression.builtin.error.displaytext.TypeErrorToDisplayTextNode.doAtom(TypeErrorToDisplayTextNode.java:28)
        at org.enso.interpreter.node.expression.builtin.error.displaytext.TypeErrorToDisplayTextNodeGen.execute(TypeErrorToDisplayTextNodeGen.java:31)
        at org.enso.interpreter.node.expression.builtin.error.displaytext.TypeErrorToDisplayTextMethodGen.execute(TypeErrorToDisplayTextMethodGen.java:45)
        at org.enso.interpreter.node.expression.builtin.error.displaytext.TypeErrorToDisplayTextMethodGen.execute(TypeErrorToDisplayTextMethodGen.java:18)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:512)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:496)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:446)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:434)
        at org.graalvm.truffle/com.oracle.truffle.api.nodes.IndirectCallNode$1.call(IndirectCallNode.java:91)
        at org.enso.interpreter.node.callable.ExecuteCallNode.callIndirect(ExecuteCallNode.java:86)
        at org.enso.interpreter.node.callable.ExecuteCallNodeGen$Uncached.executeCall(ExecuteCallNodeGen.java:165)
        at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode.uncachedDispatch(LoopingCallOptimiserNode.java:83)
        at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNodeGen$Uncached.executeDispatch(LoopingCallOptimiserNodeGen.java:99)
        at org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCall(IndirectCurryNode.java:130)
        at org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCurry(IndirectCurryNode.java:77)
        at org.enso.interpreter.node.callable.dispatch.IndirectCurryNodeGen$Uncached.execute(IndirectCurryNodeGen.java:114)
        at org.enso.interpreter.node.callable.dispatch.IndirectInvokeFunctionNode.invokeUncached(IndirectInvokeFunctionNode.java:82)
        at org.enso.interpreter.node.callable.dispatch.IndirectInvokeFunctionNodeGen$Uncached.execute(IndirectInvokeFunctionNodeGen.java:113)
        at org.enso.interpreter.node.callable.IndirectInvokeMethodNode.doFunctionalDispatch(IndirectInvokeMethodNode.java:75)
        at org.enso.interpreter.node.callable.IndirectInvokeMethodNodeGen$Uncached.execute(IndirectInvokeMethodNodeGen.java:372)
        at org.enso.interpreter.node.callable.InteropMethodCallNode.callUncached(InteropMethodCallNode.java:101)
        at org.enso.interpreter.node.callable.InteropMethodCallNodeGen$Uncached.execute(InteropMethodCallNodeGen.java:175)
        at org.enso.interpreter.runtime.callable.UnresolvedSymbol$Execute.doDispatch(UnresolvedSymbol.java:108)
        at org.enso.interpreter.runtime.callable.UnresolvedSymbolGen$InteropLibraryExports$Uncached.execute(UnresolvedSymbolGen.java:159)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.execute(InteropLibraryGen.java:4869)
        at org.enso.interpreter.runtime.callable.atom.Atom$InvokeMember.doCached(Atom.java:168)
        at org.enso.interpreter.runtime.callable.atom.Atom$InvokeMember.doUncached(Atom.java:179)
        at org.enso.interpreter.runtime.callable.atom.AtomGen$InteropLibraryExports$Uncached.invokeMember(AtomGen.java:329)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.invokeMember(InteropLibraryGen.java:5063)
        at org.enso.interpreter.runtime.error.PanicException.getExceptionMessage(PanicException.java:76)
        at org.enso.interpreter.runtime.error.PanicExceptionGen$InteropLibraryExports$Uncached.getExceptionMessage(PanicExceptionGen.java:271)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$Delegate.getExceptionMessage(InteropLibraryGen.java:3448)
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$UncachedDispatch.getExceptionMessage(InteropLibraryGen.java:5264)
        at org.enso.interpreter.runtime.error.PanicException.getMessage(PanicException.java:44)
        at org.enso.interpreter.runtime.error.PanicException.toString(PanicException.java:52)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotExceptionImpl.<init>(PolyglotExceptionImpl.java:186)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotExceptionImpl.<init>(PolyglotExceptionImpl.java:103)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.guestToHostException(PolyglotImpl.java:554)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.handleException(HostToGuestRootNode.java:139)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:123)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:591)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:562)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:512)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:496)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:136)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValue$InteropValue.execute(PolyglotValue.java:2873)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:457)
        at org.enso.polyglot.Function.execute(Function.scala:16)
        at org.enso.runner.Main$.runMain(Main.scala:390)
        at org.enso.runner.Main$.runSingleFile(Main.scala:326)
        at org.enso.runner.Main$.run(Main.scala:309)
        at org.enso.runner.Main$.main(Main.scala:563)
        at org.enso.runner.Main.main(Main.scala)
Caused by: Attached Guest Language Frames (2)
```

### Enso Version
```
Version:    0.2.8-SNAPSHOT
Built with: scala-2.13.5 for GraalVM 21.0.0.2
Built from: main* @ 8c9c293f567e4dd4f848cfa686f118c692db4dd3
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.10+8-jvmci-21.0-b06
            Windows 10 10.0 (amd64)
```

**Comment by mwu-tow** [comment]
Also, if such error is inevitable due to internal error, it should at least provide the enso stack trace as well.
