### ISSUE TITLE
Cannot use hash character `#` in string literals

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1603]
### Steps to Reproduce

Run the following
```
main = '#FF0000'
```

### Expected Result
Success.

### Actual Result
```
~ ❯ iex "H:\NBO\enso2\distribution\bin\enso.bat --run Moje2.enso"
In module Moje2:
Compiler encountered errors:
Moje2.enso[1:8-1:17]: Unclosed text literal.
Exception in thread "main" Compilation aborted due to errors.
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:548)
        at org.enso.polyglot.Module.getAssociatedConstructor(Module.scala:19)
        at org.enso.runner.Main$.runMain(Main.scala:386)
        at org.enso.runner.Main$.runSingleFile(Main.scala:326)
        at org.enso.runner.Main$.run(Main.scala:309)
        at org.enso.runner.Main$.main(Main.scala:563)
        at org.enso.runner.Main.main(Main.scala)  
```
### Enso Version
8c9c293f567e4dd4f848cfa686f118c692db4dd3

**Comment by iamrecursion** [comment]
Known issue. Waiting for the new parser to fix it.
