### ISSUE TITLE
Failed to initialize application

### ISSUE THREAD

**Issue by kunaltyagi** [enso-org/enso#3034]
Alpha 7 version installed
### What did you do?
Start application

### What did you expect to see?
Something

### What did you see instead?
Plain white screen which does modify cursor into a circle, but gives the following error:
```
Failed to initialize application: Failed to initialize language server RPC connection: Peer has replied with an error: Error { code: 6003, message: "Failed to initialize the Language S
```
Rest of message is cut off due to application size. The error couldn't be copied as well and was manually transcribed

### Enso Version
Latest GitHub release (.exe)

**Comment by bdevel** [comment]
I just installed Enso 2.0.0-alpha.18 for MacOS 11.3.1 and could not load anything due to failed language server. I then tried Enso alpha.14 which works.

```

Installed runtimes (1):
 - GraalVM 21.1.0-java11 [location: ***/graalvm-ce-java11-21.1.0]
[trace] [2021-11-02T18:23:39.068Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] received handled StartServer(bc646a26-15a9-4942-9704-aeb7b39d9a23,Project(0116faf6-3c9e-4b63-959f-18f34670e553,Restaurants_1,local,UserProject,2021-11-02T18:23:30.212999Z,Some(Edition(Some(2021.19),None,Map(),Map())),Some(2021-11-02T18:23:38.803326Z),Some(/Users/dev/enso/projects/Restaurants_1),Some(2021-11-02T18:23:32Z)),0.2.31,Actor[akka://project-manager/user/jsonrpc-connection-controller-bc646a26-15a9-4942-9704-aeb7b39d9a23/request-handler-ProjectOpen-3e127f51-3da8-4da1-8877-e67bfc7c0a88#1745451580]) from Actor[akka://project-manager/temp/$a] in state initializing
[trace] [2021-11-02T18:23:39.068Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] received handled Boot from Actor[akka://project-manager/user/language-server-registry/language-server-controller-0116faf6-3c9e-4b63-959f-18f34670e553#-918359417] in state initializing
[info] [2021-11-02T18:23:39.068Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Booting a language server [LanguageServerDescriptor(language-server-0116faf6-3c9e-4b63-959f-18f34670e553,719a1ea6-ccaf-4a7a-a1e0-a7273d1e761c,/Users/dev/enso/projects/Restaurants_1,NetworkConfig(127.0.0.1,49152,65535),org.enso.projectmanager.versionmanagement.DefaultDistributionConfiguration$@362c0099,0.2.31,JVMSettings(None,List()),false,Future(Success(Some(ws://localhost:51881/))))].
[trace] [2021-11-02T18:23:39.068Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] received handled FindFreeSocket from Actor[akka://project-manager/user/language-server-registry/language-server-controller-0116faf6-3c9e-4b63-959f-18f34670e553/bootloader-language-server-0116faf6-3c9e-4b63-959f-18f34670e553#-362812128] in state findingSocket
[debug] [2021-11-02T18:23:39.068Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Looking for available socket to bind the language server.
[info] [2021-11-02T18:23:39.07Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Found sockets for the language server [json:127.0.0.1:62578, binary:127.0.0.1:57594].
[trace] [2021-11-02T18:23:39.07Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] received handled Boot from Actor[akka://project-manager/user/language-server-registry/language-server-controller-0116faf6-3c9e-4b63-959f-18f34670e553/bootloader-language-server-0116faf6-3c9e-4b63-959f-18f34670e553#-362812128] in state bootingFirstTime
[debug] [2021-11-02T18:23:39.07Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Booting a language server.
[trace] [2021-11-02T18:23:39.07Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Discovering available components...
[debug] [2021-11-02T18:23:39.071Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Loading Graal runtime [/Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0].
[debug] [2021-11-02T18:23:39.071Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Installing GraalVM components [GraalVM 21.1.0-java11, MacOS].
[trace] [2021-11-02T18:23:39.071Z] [org.enso.runtimeversionmanager.components.GraalVMComponentUpdater] /Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0/Contents/Home/bin/gu { exists=true, executable=true }
[debug] [2021-11-02T18:23:39.071Z] [org.enso.runtimeversionmanager.components.GraalVMComponentUpdater] Executing: JAVA_HOME=/Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0/Contents/Home GRRAALVM_HOME=/Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0/Contents/Home /Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0/Contents/Home/bin/gu list -v
[trace] [2021-11-02T18:23:39.115Z] [org.enso.runtimeversionmanager.components.GraalVMComponentUpdater] ID       : graalvm


[debug] [2021-11-02T18:23:39.216Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Available GraalVM components: [Vector(GraalVMComponent(graalvm), GraalVMComponent(R), GraalVMComponent(js), GraalVMComponent(llvm-toolchain), GraalVMComponent(python))].
[info] [2021-11-02T18:23:39.216Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 21.1.0-java11].
[trace] [2021-11-02T18:23:39.217Z] [org.enso.projectmanager.infrastructure.languageserver.ExecutorWithUnlimitedPool] Starting Language Server Process [JAVA_HOME="/Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0/Contents/Home" ENSO_DATA_DIRECTORY="/Users/dev/Library/Application Support/org.enso" ENSO_AUXILIARY_LIBRARY_CACHES="/Applications/Enso.app/Contents/Resources/enso/dist/0.2.31/lib" ENSO_RUNTIME_DIRECTORY="/Users/dev/Library/Application Support/org.enso" ENSO_EDITION_PATH="/Users/dev/enso/editions" ENSO_CONFIG_DIRECTORY="/Users/dev/Library/Preferences/org.enso" ENSO_HOME="/Users/dev/enso" ENSO_LOG_DIRECTORY="/Users/dev/Library/Logs/org.enso" ENSO_LIBRARY_PATH="/Users/dev/enso/libraries" "/Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0/Contents/Home/bin/java" "-Dpolyglot.engine.IterativePartialEscape=true" "-Dtruffle.class.path.append=/Applications/Enso.app/Contents/Resources/enso/dist/0.2.31/component/runtime.jar" "-jar" "/Applications/Enso.app/Contents/Resources/enso/dist/0.2.31/component/runner.jar" "--logger-connect" "ws://localhost:51881/" "--server" "--root-id" "719a1ea6-ccaf-4a7a-a1e0-a7273d1e761c" "--path" "/Users/dev/enso/projects/Restaurants_1" "--interface" "127.0.0.1" "--rpc-port" "62578" "--data-port" "57594" "--log-level" "trace"]
[debug] [2021-11-02T18:23:39.225Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] Heartbeat connection initialized [Socket(127.0.0.1,62578)].
[debug] [2021-11-02T18:23:39.231Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] An error occurred during connecting to websocket Socket(127.0.0.1,62578). (java.lang.RuntimeException: Connection failed.)
[debug] [2021-11-02T18:23:39.231Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] An error occurred during closing web socket. ({})
akka.stream.StreamTcpException: Tcp command [Connect(127.0.0.1:62578,None,List(),Some(10 seconds),true)] failed because of java.net.ConnectException: Connection refused
Caused by: java.net.ConnectException: Connection refused
  at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_ConnectException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
  at sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
  at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
  at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.$anonfun$applyOrElse$4(TcpOutgoingConnection.scala:111)
  at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
  at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.applyOrElse(TcpOutgoingConnection.scala:111)
  at akka.actor.Actor.aroundReceive(Actor.scala:535)
  at akka.actor.Actor.aroundReceive$(Actor.scala:533)
  at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
  at akka.actor.ActorCell.invoke(ActorCell.scala:547)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
  at akka.dispatch.Mailbox.run(Mailbox.scala:231)
  at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
  at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
  at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```
