### ISSUE TITLE
Parser Error: Template Pattern Segment was Unmatched

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#470]
### General Summary
The parser is failing on certain inputs due to a template pattern segment not being matched. No matter whether the syntax is correct or not, there's no way the parser should fail.

### Steps to Reproduce

1. Execute the parser on the following input:

```
main =
    fn = a -> ((b = a) -> ((c = b + 1) -> b + c))
    fn 3
```

2. Note that it crashes.

### Expected Result
It parses successfully into a valid AST, even if it is syntactically invalid.

### Actual Result

```
[info]   org.enso.interpreter.test.InterpreterException: java.lang.Error: Internal error: template pattern segment was unmatched
[info]   at org.enso.syntax.text.ast.meta.Pattern.$anonfun$matchUnsafe$1(Pattern.scala:378)
[info]   at scala.Option.getOrElse(Option.scala:201)
[info]   at org.enso.syntax.text.ast.meta.Pattern.matchUnsafe(Pattern.scala:376)
[info]   at org.enso.syntax.text.ast.meta.Pattern.matchUnsafe$(Pattern.scala:371)
[info]   at org.enso.syntax.text.ast.meta.Pattern$Or.matchUnsafe(Pattern.scala:56)
[info]   at org.enso.syntax.text.ast.meta.Pattern.matchRevUnsafe(Pattern.scala:362)
[info]   at org.enso.syntax.text.ast.meta.Pattern.matchRevUnsafe$(Pattern.scala:358)
[info]   at org.enso.syntax.text.ast.meta.Pattern$Or.matchRevUnsafe(Pattern.scala:56)
[info]   at org.enso.syntax.text.ast.meta.Builder.build(Builder.scala:76)
[info]   at org.enso.syntax.text.ast.meta.Builder.merge(Builder.scala:38)
[info]   ...
```

### Enso Version

```
[info] Enso Compiler and Runtime
[info] Version:    0.0.1
[info] Built with: scala-2.13.1 for GraalVM 20.0.0
[info] Built from: wip/ara/lambda-consolidation* @ cc7701c20a04daa9e11c2062cf16971fb5552b3b
[info] Running on: Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.0.0, JDK 1.8.0_241-b07
[info]             Mac OS X 10.15.4 (x86_64)
```

**Comment by iamrecursion** [comment]
This bug will not be present in the new macro system.
