### ISSUE TITLE
Investigate LS behaviour when handler execution timeouts

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4960]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184359934).
<hr />

One of the logs representing issues at startup shows a corner case which I'm not sure is handled correctly.
From the stacktrace it seems that if a timeout occurs while executing the operation in zio execution context. The timeout in itself is not a problem as it can happen anyway.
What is peculiar is that a connection is closed for whatever reason (pay attention to timestamps to notice the order of the logs):
```
[info] [2023-01-29T17:38:11.456Z] [org.enso.languageserver.boot.resource.TruffleContextInitialization] Initialized Runtime context.
[info] [2023-01-29T17:38:11.456Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: Truffle context initialized.
[info] [2023-01-29T17:38:11.456Z] [org.enso.languageserver.protocol.json.JsonConnectionController] RPC session initialized for client [d2cf6682-b278-4956-9470-6413baa173cd].
[info] [2023-01-29T17:38:11.584Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Data session initialized for client: d2cf6682-b278-4956-9470-6413baa173cd [127.0.0.1:51391].
[info] [2023-01-29T17:38:11.646Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: project name is updated to [Unnamed].
[info] [2023-01-29T17:38:12.074Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: got type graph response.
[info] [2023-01-29T17:38:12.226Z] [org.enso.languageserver.search.SuggestionsHandler] Verifying: got verification response.
[info] [2023-01-29T17:38:12.306Z] [org.enso.languageserver.search.SuggestionsHandler] Verified.
[info] [2023-01-29T17:38:15.958Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Connection closed [127.0.0.1:51391].
[error] [2023-01-29T17:38:15.938Z] [org.enso.languageserver.requesthandler.vcs.InitVcsHandler] Initialize project request [Number(2)] for [d2cf6682-b278-4956-9470-6413baa173cd] failed with: null.
java.util.concurrent.TimeoutException: None
  at org.enso.languageserver.effect.ZioExec$.<clinit>(Exec.scala:123)
  at org.enso.languageserver.effect.ZioExec.$anonfun$execTimed$5(Exec.scala:79)
  at scala.Option.fold(Option.scala:263)
  at org.enso.languageserver.effect.ZioExec.$anonfun$execTimed$4(Exec.scala:79)
  at zio.Exit.fold(Exit.scala:97)
  at org.enso.languageserver.effect.ZioExec.$anonfun$execTimed$2(Exec.scala:79)
  at zio.internal.FiberContext.$anonfun$runAsync$1(FiberContext.scala:148)
  at zio.internal.FiberContext.$anonfun$notifyObservers$1(FiberContext.scala:1068)
  at scala.collection.immutable.List.foreach(List.scala:333)
  at zio.internal.FiberContext.notifyObservers(FiberContext.scala:1068)
  at zio.internal.FiberContext.zio$internal$FiberContext$$done(FiberContext.scala:948)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:915)
  at zio.internal.FiberContext.$anonfun$evaluateLater$1(FiberContext.scala:776)
  at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
  at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[info] [2023-01-29T17:38:40.422Z] [org.enso.projectmanager.protocol.ClientController] Client disconnected from the Project Manager [9b415e1b-e070-4aac-ad2e-1a97ae07803e]
[info] [2023-01-29T17:38:40.428Z] [org.enso.languageserver.runtime.RuntimeKiller] Shutting down the runtime server [Actor[akka://language-server/user/runtime-connector#1354295160]].
[error] [2023-01-29T17:38:40.458Z] [org.enso.projectmanager.boot.ProjectManager$] Main process execution failed.
```

We should really be able to recover from such an error and potentially even restart the operation.

## Comments:
So the conclusion of the ticket is that timeouts are OK, irrespective of the fact whether they are desirable. We've already increased LS's timeout for `init` operation but IDE should a) make `vcs` requests asynchronously b) it shouldn't really error on them as the project can continue to work as is. This is the job for #184370352 (Hubert Plociniczak - Feb 1, 2023)
<hr />

**Comment by hubertp** [comment]
We have reduced the time spent in the initialization so this specific timeout does not happen anymore.
However, timeouts on their own can and will probably and we will be fixing them, if possible, on a per-need basis.
