### ISSUE TITLE
Handle gracefully language server process failure

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5062]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184358814).
<hr />

Notice the unhandled `LanguageServerProcess$ServerTerminated` message in 
```
[error] [2023-01-29T17:12:38.387Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Table.Data.Column,Standard.Table.Data.Column.Column.type,from_vector)].
[warn] [2023-01-29T17:12:47.73Z] [enso] Visualisation evaluation failed: Compile error: The name `Column` could not be found..
[error] [2023-01-29T17:12:48.588Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.Network.HTTP,Standard.Base.Network.HTTP.HTTP.type,fetch)].
[warn] [2023-01-29T17:13:02.854Z] [enso] Visualisation evaluation failed: Compile error: The name `FREEZE` could not be found..
[error] [2023-01-29T17:13:10.006Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.Network.HTTP,Standard.Base.Network.HTTP.HTTP.type,fetch)].
[error] [2023-01-29T17:13:40.479Z] [enso] Error executing EnsureCompiledJob
org.enso.interpreter.service.error.FailedToApplyEditsException: Failed to apply edits for local.Unnamed_2.Main, edits=***, failure=InvalidPosition(Position(12,3786)), source='***'
  at org.enso.interpreter.service.ExecutionService.lambda$modifyModuleSources$9(ExecutionService.java:355)
  at scala.util.Either.fold(Either.scala:190)
  at org.enso.interpreter.service.ExecutionService.modifyModuleSources(ExecutionService.java:352)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.applyEdits(EnsureCompiledJob.scala:251)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledModule(EnsureCompiledJob.scala:85)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledFiles$2(EnsureCompiledJob.scala:67)
  at scala.collection.immutable.List.map(List.scala:246)
  at scala.collection.immutable.List.map(List.scala:79)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledFiles(EnsureCompiledJob.scala:67)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:47)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:37)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:110)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
[error] [2023-01-29T17:13:40.6Z] [enso] Error executing EnsureCompiledJob
org.enso.syntax.text.Parser.ParserError: Internal error in parser Could not deserialize metadata.
  at org.enso.syntax.text.Parser.$anonfun$splitMeta$2(Parser.scala:179)
  at scala.util.Either$LeftProjection.map(Either.scala:614)
  at org.enso.syntax.text.Parser.splitMeta(Parser.scala:178)
  at org.enso.compiler.Compiler.parseMeta(Compiler.scala:595)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.buildCacheInvalidationCommands(EnsureCompiledJob.scala:275)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.invalidateCaches(EnsureCompiledJob.scala:304)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledModule$2(EnsureCompiledJob.scala:88)
  at scala.util.Either.map(Either.scala:382)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledModule$1(EnsureCompiledJob.scala:87)
  at scala.Option.map(Option.scala:242)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledModule(EnsureCompiledJob.scala:85)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledFiles$2(EnsureCompiledJob.scala:67)
  at scala.collection.immutable.List.map(List.scala:246)
  at scala.collection.immutable.List.map(List.scala:79)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledFiles(EnsureCompiledJob.scala:67)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:47)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:37)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:110)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
Caused by: io.circe.ParsingFailure: expected whitespace or eof got '},"int...' (line 1, column 841)
[error] [2023-01-29T17:13:41.085Z] [enso] Error executing EnsureCompiledJob
org.enso.syntax.text.Parser.ParserError: Internal error in parser Could not deserialize metadata.
  at org.enso.syntax.text.Parser.$anonfun$splitMeta$2(Parser.scala:179)
  at scala.util.Either$LeftProjection.map(Either.scala:614)
  at org.enso.syntax.text.Parser.splitMeta(Parser.scala:178)
  at org.enso.compiler.Compiler.parseMeta(Compiler.scala:595)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.buildCacheInvalidationCommands(EnsureCompiledJob.scala:275)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.invalidateCaches(EnsureCompiledJob.scala:304)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledModule$2(EnsureCompiledJob.scala:88)
  at scala.util.Either.map(Either.scala:382)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledModule$1(EnsureCompiledJob.scala:87)
  at scala.Option.map(Option.scala:242)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledModule(EnsureCompiledJob.scala:85)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledFiles$2(EnsureCompiledJob.scala:67)
  at scala.collection.immutable.List.map(List.scala:246)
  at scala.collection.immutable.List.map(List.scala:79)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledFiles(EnsureCompiledJob.scala:67)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:47)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:37)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:110)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
Caused by: io.circe.ParsingFailure: expected whitespace or eof got '},"int...' (line 1, column 865)
[warn] [2023-01-29T17:13:41.192Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] Received unknown message: class org.enso.projectmanager.infrastructure.languageserver.LanguageServerProcess$ServerTerminated
[error] [2023-01-29T17:13:55.913Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] An error occurred during connecting to websocket Socket(127.0.0.1,51285). Tcp command [Connect(127.0.0.1:51285,None,List(),Some(10 seconds),true)] failed because of java.net.ConnectException: Connection refused
[error] [2023-01-29T17:13:55.913Z] [org.enso.projectmanager.infrastructure.languageserver.HeartbeatSession] An error occurred during closing web socket.
java.lang.RuntimeException: Connection failed.
  at akka.http.impl.engine.ws.WebSocketClientBlueprint$UpgradeStage$1$$anon$1.onUpstreamFailure(WebSocketClientBlueprint.scala:138)
  at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:525)
  at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:390)
  at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:650)
  at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:521)
  at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:625)
  at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:800)
  at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:818)
  at akka.actor.Actor.aroundReceive(Actor.scala:537)
  at akka.actor.Actor.aroundReceive$(Actor.scala:535)
  at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:716)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
  at akka.actor.ActorCell.invoke(ActorCell.scala:548)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
  at akka.dispatch.Mailbox.run(Mailbox.scala:231)
  at java.base@11.0.17/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.base@11.0.17/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base@11.0.17/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base@11.0.17/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
  at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: akka.stream.StreamTcpException: Tcp command [Connect(127.0.0.1:51285,None,List(),Some(10 seconds),true)] failed because of java.net.ConnectException: Connection refused
Caused by: java.net.ConnectException: Connection refused
  at java.base@11.0.17/sun.nio.ch.SocketChannelImpl.checkConnect(SocketChannelImpl.java)
  at java.base@11.0.17/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
  at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.$anonfun$applyOrElse$4(TcpOutgoingConnection.scala:111)
  at akka.io.TcpOutgoingConnection.akka$io$TcpOutgoingConnection$$reportConnectFailure(TcpOutgoingConnection.scala:53)
  at akka.io.TcpOutgoingConnection$$anonfun$connecting$1.applyOrElse(TcpOutgoingConnection.scala:111)
  at akka.actor.Actor.aroundReceive(Actor.scala:537)
  at akka.actor.Actor.aroundReceive$(Actor.scala:535)
  at akka.io.TcpConnection.aroundReceive(TcpConnection.scala:33)
  at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
  at akka.actor.ActorCell.invoke(ActorCell.scala:548)
  at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
  at akka.dispatch.Mailbox.run(Mailbox.scala:231)
  at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
  at java.base@11.0.17/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
  at java.base@11.0.17/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
  at java.base@11.0.17/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
  at java.base@11.0.17/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
  at java.base@11.0.17/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
  at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
  at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
[info] [2023-01-29T17:13:55.913Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerSupervisor] Server is unresponsive. Restarting [LanguageServerConnectionInfo(127.0.0.1,51285,50140)].
[info] [2023-01-29T17:16:46.346Z] [org.enso.projectmanager.protocol.ClientController] Client disconnected from the Project Manager [4fd7bcb4-79ba-4ad5-a820-86ef15280f7b]
[error] [2023-01-29T17:16:46.361Z] [org.enso.projectmanager.boot.ProjectManager$] Main process execution failed.
```

**Comment by jdunkerley** [comment]
Closing as too old!
