### ISSUE TITLE
Closing the project should gracefully shutdown all services

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5071]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184349284).
<hr />

```
[info] [2023-01-30T12:17:32.379Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Database @ 2023.1.1-dev at [***/2023.1.1-dev].
[error] [2023-01-30T12:17:44.168Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Base.Data,Standard.Base.Data,fetch)].
[error] [2023-01-30T12:17:45.198Z] [org.enso.languageserver.runtime.ContextEventsListener] Unable to find suggestion for [(Standard.Table.Data.Table_Conversions,Standard.Table.Data.Table.Table.type,from_objects)].
[info] [2023-01-30T12:19:31.914Z] [org.enso.projectmanager.protocol.ClientController] Client disconnected from the Project Manager [8ef19391-b4b2-4dcb-8ae8-907b4b3d059a]
[info] [2023-01-30T12:19:31.914Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Connection closed [127.0.0.1:51052].
[error] [2023-01-30T12:19:31.93Z] [org.enso.projectmanager.boot.ProjectManager$] Main process execution failed.
java.io.EOFException: Some(There is no more input left to read)
  at zio.console.package$Console$Service$$anon$1.$anonfun$getStrLn$1(package.scala:60)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:490)
  at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:770)
  at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base@11.0.17/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
  at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

**Comment by 4e6** [comment]
Closed by #7157
