### ISSUE TITLE
Invalid Sharing of AST nodes in EpbContext

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5087]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184321951).
<hr />

#183546453 enabled asserts in engine unit tests, but not in runtime-with-polyglot project. There is [invalid sharing of AST nodes](https://github.com/enso-org/enso/pull/4074#discussion_r1086255799) `AssertionError` which requires deeper investigation.

```
at com.oracle.truffle.polyglot.PolyglotSharingLayer.invalidSharingError(PolyglotSharingLayer.java:649)
at com.oracle.truffle.polyglot.PolyglotFastThreadLocals.validSharing(PolyglotFastThreadLocals.java:266)
at com.oracle.truffle.polyglot.PolyglotFastThreadLocals.getLanguageContext(PolyglotFastThreadLocals.java:236)
at com.oracle.truffle.polyglot.PolyglotFastThreadLocals$ContextReferenceImpl.get(PolyglotFastThreadLocals.java:457)
at org.enso.interpreter.epb.EpbContext.get(EpbContext.java:57)
at org.enso.interpreter.epb.node.ForeignEvalNode.getEpbContext(ForeignEvalNode.java:186)
at org.enso.interpreter.epb.node.ForeignEvalNode.parseJs(ForeignEvalNode.java:118)
```

This failure is caused by upgrading to GraalVM 22.2 and newer. GraalVM 22.2 introduced concept of "sharing layers" - that concept wasn't existing when `EpbContext` was created. Hence the new assertion error. Moreover the concept of "sharing layers" probably replaces all the work done in `EpbLanguage` - possibly the code isn't needed anymore.

## Tasks:
- [ ] Change the existing code to avoid the asserts
- [ ] Investigate if we can replace Epb by "sharing layers" and if so, plan that work

## Blockers:
[#183546453](https://www.pivotaltracker.com/story/show/#183546453) resolved

**Comment by Akirathan** [comment]
Reproduce with
```
Json.parse "{'name': 'John Smith'}"
```

AssertionError:
```
Execution finished with an error: java.lang.AssertionError: Invalid sharing of AST nodes detected. The current context uses a different sharing layer than the executed node. A common cause of this are CallTargets that are reused across different contexts in an invalid way.Stack trace: 
  <<current-context>>
    <-- Sharing Layer Change: 0x1C135F63 => 0x63C4D16 -->
  <epb>.(Unknown)(ForeignEvalNode@29bd2796)
  <epb>.(Unknown)
  <enso>.Json.json_parse(Json.enso:294)
  <enso>.Json.parse<arg-1>(Json.enso:48)
  <enso>.Panic.catch(Unknown)
  <enso>.Json.parse(Json.enso:47)
  <enso>.<eval>(Unknown)
  <enso>.Debug.breakpoint(Unknown)
  <enso>.Internal_Repl_Module___.internal_repl_entry_point___(Internal_Repl_Module___:4)
  <Unknown>.org.graalvm.polyglot.Value<Function>.execute(Unknown)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotSharingLayer.invalidSharingError(PolyglotSharingLayer.java:672)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.validSharing(PolyglotFastThreadLocals.java:300)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals.getLanguageContext(PolyglotFastThreadLocals.java:270)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotFastThreadLocals$ContextReferenceImpl.get(PolyglotFastThreadLocals.java:495)
        at <java> org.enso.interpreter.epb.EpbContext.get(EpbContext.java:106)
        at <java> org.enso.interpreter.epb.node.ForeignEvalNode.parseJs(ForeignEvalNode.java:117)
        at <java> org.enso.interpreter.epb.node.ForeignEvalNode.lockAndParse(ForeignEvalNode.java:82)
        at <java> org.enso.interpreter.epb.node.ForeignEvalNode.ensureParsed(ForeignEvalNode.java:63)
        at <java> org.enso.interpreter.epb.node.ForeignEvalNode.execute(ForeignEvalNode.java:52)
        at <epb> <epb> null(Unknown)
        at <enso> Json.json_parse(/home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso:294-295)
        at <enso> Json.parse<arg-1>(/home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso:48:22-36)
        at <enso> Panic.catch(Internal)
        at <enso> Json.parse(/home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Base/0.0.0-dev/src/Data/Json.enso:47-49)
        at <enso> <eval>(Internal)
        at <enso> Debug.breakpoint(Internal)
        at <enso> Internal_Repl_Module___.internal_repl_entry_point___(Internal_Repl_Module___:4:32-47)
```
