### ISSUE TITLE
NPE for invalid syntax

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5273]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184045371).
<hr />

While experimenting with some other test encountered this one:
```
from Standard.Base import all
          
foo x = @

main =
    x = Panic.catch Any (@) .convert_to_dataflow_error
    IO.println x
    IO.println (x.catch Any .to_text)
```

results in NPE roughly
```
[info]     org.enso.interpreter.test.InterpreterException: java.lang.NullPointerException
[info]     at org.enso.compiler.TreeToIr.translateExpression(TreeToIr.java:675)
[info]     at org.enso.compiler.TreeToIr.translateExpression(TreeToIr.java:810)
[info]     at org.enso.compiler.TreeToIr.translateCall(TreeToIr.java:513)
[info]     at org.enso.compiler.TreeToIr.translateExpression(TreeToIr.java:604)
[info]     at org.enso.compiler.TreeToIr.translateExpression(TreeToIr.java:770)
[info]     at org.enso.compiler.TreeToIr.translateExpression(TreeToIr.java:749)
[info]     at org.enso.compiler.TreeToIr.translateExpression(TreeToIr.java:598)
[info]     at org.enso.compiler.TreeToIr.translateModuleSymbol(TreeToIr.java:240)
[info]     at org.enso.compiler.TreeToIr.translateModule(TreeToIr.java:187)
[info]     at org.enso.compiler.TreeToIr.translate(TreeToIr.java:91)
```

This should result in some meaningful error not a crash.

**Comment by jdunkerley** [comment]
Tested and works better now :)
