### ISSUE TITLE
Removing any built-in class breaks incremental compilation

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5365]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/182868680).
<hr />

Removing a builtin class is not incremental-compilation friendly:
```
sbt:enso> buildEngineDistribution
[info] Strategy 'concat' was applied to 4 files (Run the task at debug level to see details)
[info] Strategy 'discard' was applied to 5 files (Run the task at debug level to see details)
[info] Strategy 'first' was applied to 10 files (Run the task at debug level to see details)
[info] Assembly up to date: /home/hubert/work/repos/enso/enso/runtime.jar
[info] Strategy 'concat' was applied to a file (Run the task at debug level to see details)
[info] Strategy 'discard' was applied to 5 files (Run the task at debug level to see details)
[info] Strategy 'first' was applied to 11 files (Run the task at debug level to see details)
[info] Assembly up to date: /home/hubert/work/repos/enso/enso/runner.jar
[info] Regenerating manifest for [distribution/lib/Standard/Base/0.0.0-dev].
java.lang.reflect.InvocationTargetException
  | => eat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.enso.interpreter.runtime.builtin.Builtins.lambda$registerBuiltinMethods$1(Builtins.java:145)
	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
	at org.enso.interpreter.runtime.builtin.Builtins.registerBuiltinMethods(Builtins.java:140)
	at org.enso.interpreter.runtime.builtin.Builtins.<init>(Builtins.java:94)
	at org.enso.interpreter.runtime.Context.<init>(Context.java:106)
	at org.enso.interpreter.Language.createContext(Language.java:115)
	at org.enso.interpreter.Language.createContext(Language.java:44)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.createEnvContext(LanguageAccessor.java:283)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:557)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:500)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:642)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.getBindings(PolyglotContextImpl.java:969)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.getBindings(PolyglotContextDispatch.java:97)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.getBindings(Context.java:540)
	at org.enso.polyglot.PolyglotContext.getTopScope(PolyglotContext.scala:37)
	at org.enso.languageserver.libraries.CompilerBasedDependencyExtractor.findImportedLibraries$1(CompilerBasedDependencyExtractor.scala:28)
	at org.enso.languageserver.libraries.CompilerBasedDependencyExtractor.$anonfun$findDependencies$2(CompilerBasedDependencyExtractor.scala:40)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.immutable.HashSet.flatMap(HashSet.scala:34)
	at org.enso.languageserver.libraries.CompilerBasedDependencyExtractor.findDependencies(CompilerBasedDependencyExtractor.scala:40)
	at org.enso.libraryupload.LibraryUploader.$anonfun$updateManifest$1(LibraryUploader.scala:95)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.util.Try$.apply(Try.scala:210)
	at org.enso.libraryupload.LibraryUploader.updateManifest(LibraryUploader.scala:94)
	at org.enso.runner.ProjectUploader$.updateManifest(ProjectUploader.scala:76)
	at org.enso.runner.Main$.main(Main.scala:1003)
	at org.enso.runner.Main.main(Main.scala)
Caused by: java.lang.NoClassDefFoundError: org/enso/interpreter/node/expression/builtin/interop/generic/ReadArrayElementNode
	at org.enso.interpreter.node.expression.builtin.interop.generic.ReadArrayElementMethodGen.<init>(ReadArrayElementMethodGen.java:38)
	at org.enso.interpreter.node.expression.builtin.interop.generic.ReadArrayElementMethodGen.makeFunction(ReadArrayElementMethodGen.java:42)
	... 32 more
Caused by: java.lang.ClassNotFoundException: org.enso.interpreter.node.expression.builtin.interop.generic.ReadArrayElementNode
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 34 more
[info] Engine package created at built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev
```

## Comments:
The main problem is that metadata for builtins is append only, on purpose. Detecting that some class was removed is actually non-trivial in an incremental setting because old classes won't be part of the processing round as they don't need to be recompiled. (Hubert Plociniczak - Aug 2, 2022)
<hr />
As an alternative solution, we need a button to request a _clean build_. Once human notices the CI has gone into an endless loop(#182867911) or is broken due to debris from previous runs (#182868680), human can step in a request complete clean build. Could CI offer such _button_/_action_, @murbanczyk? (jaroslavtulach - Aug 22, 2022)
<hr />
	@murbanczyk wrote:
> To allow resolving this issue without my manual intervention, I have exposed a special "Clean Runners" workflow. (https://github.com/enso-org/ci/actions/workflows/clean.yml) Running it should resolve issues.
 (jaroslavtulach - Aug 25, 2022)
<hr />

**Comment by hubertp** [comment]
Still an issue but happens so rarely and there is a workaround that it's likely a won't fix.
