### ISSUE TITLE
System.create_process test fails on CI

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5438]
This task is automatically imported from the old Task Issue Board and it was originally created by Dmitry Bushev.
Original issue is [here](https://www.pivotaltracker.com/story/show/182638378).
<hr />

The `SystemProcessTest` randomly fails on CI (Linux) sometimes for cached and sometimes for unchached context https://github.com/enso-org/enso/runs/7096501330?check_suite_focus=true
```
[info]   - should redirect stdin unused (Unix) *** FAILED *** (39 milliseconds)
[info]     org.enso.interpreter.test.InterpreterException: a polyglot object
[info]     at <enso>.System.create_process(Unknown)
[info]     at <enso>.Test.main(Test:6)
[info]     at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:841)
[info]     at org.enso.polyglot.Function.execute(Function.scala:16)
[info]     at org.enso.interpreter.test.InterpreterRunner.$anonfun$eval$1(InterpreterTest.scala:183)
[info]     at org.enso.interpreter.test.InterpreterException$.rethrowPolyglot(InterpreterException.scala:18)
[info]     at org.enso.interpreter.test.InterpreterRunner.eval(InterpreterTest.scala:181)
[info]     at org.enso.interpreter.test.InterpreterRunner.eval$(InterpreterTest.scala:178)
[info]     at org.enso.interpreter.test.semantic.SystemProcessTest.eval(SystemProcessTest.scala:12)
[info]     at org.enso.interpreter.test.semantic.SystemProcessTest.$anonfun$specify$11(SystemProcessTest.scala:159)
```

**Comment by jdunkerley** [comment]
Not seen this in ages.
