### ISSUE TITLE
Parser fails on types like `[A | B]`

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5525]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/181139488).
<hr />

### Steps to reproduce
Create and run the following script:
```
from Standard.Base import all

foo : [Integer | Text] -> (Integer | Text)
foo v = v.at 0

main = 
    IO.println <| here.foo [1,2,3]
```

### Expected

```
1
```

### Actual

```
Exception in thread "main" org.graalvm.polyglot.PolyglotException: java.lang.Error: Internal error: not all template segments were fully matched
	at org.enso.syntax.text.ast.meta.Builder.build(Builder.scala:89)
	at org.enso.syntax.text.prec.Macro$Transformer.$anonfun$run$2(Macro.scala:72)
	at org.enso.syntax.text.prec.Macro$Transformer.$anonfun$run$2$adapted(Macro.scala:68)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.enso.syntax.text.prec.Macro$Transformer.run(Macro.scala:68)
(...) (truncated the rest)
```

## Comments:
For the new parser, I added a test case for this in https://github.com/enso-org/enso/pull/3802; it parses correctly, but `TreeToIr`'s handling of the case can't be tested yet, since the `TreeToIr` tests use the old parser as an oracle, and the old parser crashes in this case. (Keziah Wesley - Oct 17, 2022)
<hr />

**Comment by jdunkerley** [comment]
We shouldn't write in this form - should be `Vector (Text | Number)`
