### ISSUE TITLE
Nested square brackets break doc parser

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#5674]
### Bug description 

A [workaround](https://github.com/enso-org/enso/pull/5646/commits/7305d1cbbb0e6e90f5421404de93de5297337f0a) was necessary for https://github.com/enso-org/enso/pull/5646 to avoid doc parser crashing hard:
```
sbt:enso> docs-generator/run
[info] running org.enso.docs.generator.Main 
[error] java.lang.Error: Internal error: not all template segments were fully matched
[error] 	at org.enso.syntax.text.ast.meta.Builder.build(Builder.scala:89)
[error] 	at org.enso.syntax.text.prec.Macro$Transformer.$anonfun$run$2(Macro.scala:72)
[error] 	at org.enso.syntax.text.prec.Macro$Transformer.$anonfun$run$2$adapted(Macro.scala:68)
[error] 	at scala.collection.immutable.List.foreach(List.scala:333)
[error] 	at org.enso.syntax.text.prec.Macro$Transformer.run(Macro.scala:68)
[error] 	at org.enso.syntax.text.prec.Macro$.org$enso$syntax$text$prec$Macro$$transform(Macro.scala:22)
[error] 	at org.enso.syntax.text.prec.Macro$Transformer.$anonfun$run$6(Macro.scala:138)
[error] 	at cats.derived.MkFunctor.$anonfun$map$2(functor.scala:38)
[error] 	at cats.Later.value$lzycompute(Eval.scala:169)
[error] 	at cats.Later.value(Eval.scala:168)
[error] 	at cats.derived.MkFunctorGeneric.$anonfun$mkSafeMap$2(functor.scala:105)
[error] 	at cats.package$$anon$1.map(package.scala:106)
[error] 	at cats.derived.MkFunctorGeneric.$anonfun$mkSafeMap$1(functor.scala:105)
[error] 	at cats.Later.value$lzycompute(Eval.scala:169)
[error] 	at cats.Later.value(Eval.scala:168)
[error] 	at cats.Eval$.loop$1(Eval.scala:359)
[error] 	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:384)
[error] 	at cats.Eval$FlatMap.value(Eval.scala:305)
[error] 	at cats.derived.MkFunctor.map(functor.scala:38)
[error] 	at cats.derived.MkFunctor.map$(functor.scala:37)
[error] 	at cats.derived.MkFunctorGeneric$$anon$6.map(functor.scala:109)
[error] 	at org.enso.syntax.text.Shape$implicits$ToShapeOps.map(AST.scala:1119)
[error] 	at org.enso.syntax.text.AST$AstOps.map(AST.scala:1583)
[error] 	at org.enso.syntax.text.prec.Macro$Transformer.run(Macro.scala:138)
[error] 	at org.enso.syntax.text.prec.Macro$.org$enso$syntax$text$prec$Macro$$transform(Macro.scala:22)
[error] 	at org.enso.syntax.text.prec.Macro$Transformer.$anonfun$run$6(Macro.scala:138)
[error] 	at cats.derived.MkFunctor.$anonfun$map$2(functor.scala:38)
[error] 	at cats.Later.value$lzycompute(Eval.scala:169)
[error] 	at cats.Later.value(Eval.scala:168)
[error] 	at cats.derived.MkFunctorGeneric.$anonfun$mkSafeMap$2(functor.scala:105)
[error] 	at cats.package$$anon$1.map(package.scala:106)
[error] 	at cats.derived.MkFunctorGeneric.$anonfun$mkSafeMap$1(functor.scala:105)
[error] 	at cats.Later.value$lzycompute(Eval.scala:169)
[error] 	at cats.Later.value(Eval.scala:168)
[error] 	at cats.Eval$.loop$1(Eval.scala:359)
[error] 	at cats.Eval$.cats$Eval$$evaluate(Eval.scala:384)
[error] 	at cats.Eval$FlatMap.value(Eval.scala:305)
...
```

The current implementation does not accept docs having nested square brackets like
```
[ ... [ ... ] ... ]
```

Either we fix the current parser or add this as a test-case for the new one. Assuming we want the latter, assigning to @kazcw.

**Comment by wdanilo** [comment]
We should probably fix it in the new parser rather than the old one, right?

**Comment by hubertp** [comment]
@wdanilo Yes, I'd rather not touch the old one if it is going away.
