### ISSUE TITLE
NPE in  io.circe.Printer$PrintingFolder.onString from Client.processMessage(

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#5683]
### Discord username

Jaroslav Tulach#1623

### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While developing I am seeing:
```
java.lang.NullPointerException
        at io.circe.Printer$PrintingFolder.onString(Printer.scala:319)
        at io.circe.Printer$PrintingFolder.onString(Printer.scala:302)
        at io.circe.Json$JString.foldWith(Json.scala:364)
        at io.circe.JsonObject$LinkedHashMapJsonObject.appendToFolder(JsonObject.scala:343)
        at io.circe.Printer$PrintingFolder.onObject(Printer.scala:369)
        at io.circe.Printer$PrintingFolder.onObject(Printer.scala:302)
        at io.circe.Json$JObject.foldWith(Json.scala:426)
        at io.circe.Printer.unsafePrintToAppendable(Printer.scala:229)
        at io.circe.Printer.print(Printer.scala:197)
        at io.circe.Json.noSpaces(Json.scala:117)
        at org.enso.loggingservice.internal.service.Client.processMessage(Client.scala:91)
        at org.enso.loggingservice.internal.service.ThreadProcessingService.runQueue(ThreadProcessingService.scala:70)
        at org.enso.loggingservice.internal.service.ThreadProcessingService.$anonfun$startQueueProcessor$1(ThreadProcessingService.scala:50)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### Expected behaviour

I have a feeling this is related to encoding exceptions with `null` message that cannot be serialized, but I am not able to verify that in debugger.

### Enso Version

dev as of Feb 17, 2023

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

Browser

### Operating System

Linux

### Operating System Version

Ubuntu

### Hardware you are using

AMD Radeon

**Comment by JaroslavTulach** [comment]
Hubert, Radek, can you triage my bug report? Is it possible that `null` message could yield this error or am I totally off?

**Comment by JaroslavTulach** [comment]
I am using following modification to obtain the exception:
```diff
enso$ git diff
diff --git a/lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/Client.scala b/lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/Client.scala
index b7ed6547a..6b4223b95 100644
--- a/lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/Client.scala
+++ b/lib/scala/logging-service/src/main/scala/org/enso/loggingservice/internal/service/Client.scala
@@ -87,7 +87,14 @@ class Client(
         "the connection has been initialized."
       )
     )
-    val serializedMessage = message.asJson.noSpaces
+    val serializedMessage = try {
+        message.asJson.dropNullValues.noSpaces
+    } catch {
+        case npe: NullPointerException => {
+            npe.printStackTrace()
+            throw npe
+        }
+    }
     val offerResult       = queue.offer(TextMessage.Strict(serializedMessage))
     try {
       Await.result(offerResult, 30.seconds) match {
```

**Comment by radeusgd** [comment]
When does this happen? Just randomly when using the IDE? Or is there any particular set of steps when it happens more often?

I'm not sure what can be `null` in the `WSLogMessage`, nothing should be as far as I can tell... Indeed would be good to try debugging it and finding more precisely where that null is lurking.

**Comment by JaroslavTulach** [comment]
It happens randomly when I run the IDE & `project-manager` . I'll do a bit more debugging, if I catch the issues again. Thanks for taking a look.

**Comment by hubertp** [comment]
I think I saw something similar in the past when trying to visualize dataflow errors

**Comment by jdunkerley** [comment]
Left with `triage` label as need to reproduce.

**Comment by JaroslavTulach** [comment]
> I think I saw something similar in the past when trying to visualize dataflow errors

Thanks for the encouragement. I have a reproducer.
