### ISSUE TITLE
Parser NPE on empty assignment

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5903]
## Repro

Run the following code:
```
from Standard.Base import all

main =
    x = 4
    y = 
    z = 5
    IO.println x+y+z
```

## Expected result

I should get a syntax error providing file and line location where there was an assignment that did not have anything assigned to it.

## Actual result

It results in NPE and no contextual information at all:
```
Execution finished with an error: java.lang.NullPointerException
```

**Comment by radeusgd** [comment]
Example stack trace of this error:
```
at org.enso.compiler.core.IR$Expression.$anonfun$transformExpressions$1(IR.scala:1788)
        at org.enso.compiler.core.IR$Expression$Binding.mapExpressions(IR.scala:2010)
        at org.enso.compiler.core.IR$Expression$Binding.mapExpressions(IR.scala:1943)
        at org.enso.compiler.core.IR$Expression.transformExpressions(IR.scala:1788)
        at org.enso.compiler.core.IR$Expression.transformExpressions$(IR.scala:1782)
        at org.enso.compiler.core.IR$Expression$Binding.transformExpressions(IR.scala:1943)
        at org.enso.compiler.pass.resolve.DocumentationComments$.org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression(DocumentationComments.scala:74)
        at org.enso.compiler.pass.resolve.DocumentationComments$$anonfun$org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression$1.$anonfun$applyOrElse$1(DocumentationComments.scala:77)
        at scala.collection.immutable.List.map(List.scala:250)
        at org.enso.compiler.pass.resolve.DocumentationComments$$anonfun$org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression$1.applyOrElse(DocumentationComments.scala:77)
        at org.enso.compiler.pass.resolve.DocumentationComments$$anonfun$org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression$1.applyOrElse(DocumentationComments.scala:74)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
        at org.enso.compiler.core.IR$Expression.transformExpressions(IR.scala:1786)
        at org.enso.compiler.core.IR$Expression.transformExpressions$(IR.scala:1782)
        at org.enso.compiler.core.IR$Expression$Block.transformExpressions(IR.scala:1818)
        at org.enso.compiler.pass.resolve.DocumentationComments$.org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression(DocumentationComments.scala:74)
        at org.enso.compiler.pass.resolve.DocumentationComments$.resolveDefinition(DocumentationComments.scala:156)
        at org.enso.compiler.pass.resolve.DocumentationComments$.$anonfun$resolveModule$5(DocumentationComments.scala:200)
        at scala.collection.immutable.List.map(List.scala:250)
        at org.enso.compiler.pass.resolve.DocumentationComments$.resolveModule(DocumentationComments.scala:200)
        at org.enso.compiler.pass.resolve.DocumentationComments$.runModule(DocumentationComments.scala:45)     
        at org.enso.compiler.pass.PassManager.$anonfun$runPassesOnModule$2(PassManager.scala:101)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at org.enso.compiler.pass.PassManager.runPassesOnModule(PassManager.scala:92)
        at org.enso.compiler.Compiler.recognizeBindings(Compiler.scala:779)
        at org.enso.compiler.Compiler.uncachedParseModule(Compiler.scala:561)
        at org.enso.compiler.Compiler.parseModule(Compiler.scala:506)
        at org.enso.compiler.Compiler.ensureParsed(Compiler.scala:600)
        at org.enso.compiler.Compiler.gatherImportStatements(Compiler.scala:467)
        at org.enso.interpreter.runtime.Module$InvokeMember.gatherImportStatements(Module.java:614)
        at org.enso.interpreter.runtime.Module$InvokeMember.doInvoke(Module.java:643)
        at org.enso.interpreter.runtime.ModuleGen$InteropLibraryExports$Cached.invokeMember(ModuleGen.java:77) 
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8328)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$AbstractInvokeNode.executeShared(PolyglotValueDispatch.java:4446)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNoArgsNode.executeImpl(PolyglotValueDispatch.java:4510)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:971)
        at org.enso.polyglot.Module.gatherImportStatements(Module.scala:60)
        at org.enso.languageserver.libraries.CompilerBasedDependencyExtractor.findImportedLibraries$1(CompilerBasedDependencyExtractor.scala:29)
        at org.enso.languageserver.libraries.CompilerBasedDependencyExtractor.$anonfun$findDependencies$2(CompilerBasedDependencyExtractor.scala:40)
        at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
        at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
        at scala.collection.immutable.HashSet.flatMap(HashSet.scala:34)
        at org.enso.languageserver.libraries.CompilerBasedDependencyExtractor.findDependencies(CompilerBasedDependencyExtractor.scala:40)
        at org.enso.libraryupload.LibraryUploader.$anonfun$updateManifest$1(LibraryUploader.scala:95)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.Try$.apply(Try.scala:210)
        at org.enso.libraryupload.LibraryUploader.updateManifest(LibraryUploader.scala:94)
        at org.enso.runner.ProjectUploader$.updateManifest(ProjectUploader.scala:76)
        at org.enso.runner.Main$.main(Main.scala:1036)
        at org.enso.runner.Main.main(Main.scala)
Original Internal Error:
java.lang.NullPointerException
        at org.enso.compiler.core.IR$Expression.$anonfun$transformExpressions$1(IR.scala:1788)
        at org.enso.compiler.core.IR$Expression$Binding.mapExpressions(IR.scala:2010)
        at org.enso.compiler.core.IR$Expression$Binding.mapExpressions(IR.scala:1943)
        at org.enso.compiler.core.IR$Expression.transformExpressions(IR.scala:1788)
        at org.enso.compiler.core.IR$Expression.transformExpressions$(IR.scala:1782)
        at org.enso.compiler.core.IR$Expression$Binding.transformExpressions(IR.scala:1943)
        at org.enso.compiler.pass.resolve.DocumentationComments$.org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression(DocumentationComments.scala:74)
        at org.enso.compiler.pass.resolve.DocumentationComments$$anonfun$org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression$1.$anonfun$applyOrElse$1(DocumentationComments.scala:77)
        at scala.collection.immutable.List.map(List.scala:250)
        at org.enso.compiler.pass.resolve.DocumentationComments$$anonfun$org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression$1.applyOrElse(DocumentationComments.scala:77)
        at org.enso.compiler.pass.resolve.DocumentationComments$$anonfun$org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression$1.applyOrElse(DocumentationComments.scala:74)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
        at org.enso.compiler.core.IR$Expression.transformExpressions(IR.scala:1786)
        at org.enso.compiler.core.IR$Expression.transformExpressions$(IR.scala:1782)
        at org.enso.compiler.core.IR$Expression$Block.transformExpressions(IR.scala:1818)
        at org.enso.compiler.pass.resolve.DocumentationComments$.org$enso$compiler$pass$resolve$DocumentationComments$$resolveExpression(DocumentationComments.scala:74)
        at org.enso.compiler.pass.resolve.DocumentationComments$.resolveDefinition(DocumentationComments.scala:156)
        at org.enso.compiler.pass.resolve.DocumentationComments$.$anonfun$resolveModule$5(DocumentationComments.scala:200)
        at scala.collection.immutable.List.map(List.scala:250)
        at org.enso.compiler.pass.resolve.DocumentationComments$.resolveModule(DocumentationComments.scala:200)
        at org.enso.compiler.pass.resolve.DocumentationComments$.runModule(DocumentationComments.scala:45)     
        at org.enso.compiler.pass.PassManager.$anonfun$runPassesOnModule$2(PassManager.scala:101)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at org.enso.compiler.pass.PassManager.runPassesOnModule(PassManager.scala:92)
        at org.enso.compiler.Compiler.recognizeBindings(Compiler.scala:779)
        at org.enso.compiler.Compiler.uncachedParseModule(Compiler.scala:561)
        at org.enso.compiler.Compiler.parseModule(Compiler.scala:506)
        at org.enso.compiler.Compiler.ensureParsed(Compiler.scala:600)
        at org.enso.compiler.Compiler.gatherImportStatements(Compiler.scala:467)
        at org.enso.interpreter.runtime.Module$InvokeMember.gatherImportStatements(Module.java:614)
        at org.enso.interpreter.runtime.Module$InvokeMember.doInvoke(Module.java:643)
        at org.enso.interpreter.runtime.ModuleGen$InteropLibraryExports$Cached.invokeMember(ModuleGen.java:77) 
        at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8328)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$AbstractInvokeNode.executeShared(PolyglotValueDispatch.java:4446)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$InvokeNoArgsNode.executeImpl(PolyglotValueDispatch.java:4510)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
        at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.GraalRuntimeSupport.callProfiled(GraalRuntimeSupport.java:256)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue.invoke(PolyglotValueDispatch.java:2426)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.invokeMember(Value.java:971)
        at org.enso.polyglot.Module.gatherImportStatements(Module.scala:60)
        at org.enso.languageserver.libraries.CompilerBasedDependencyExtractor.findImportedLibraries$1(CompilerBasedDependencyExtractor.scala:29)
        at org.enso.languageserver.libraries.CompilerBasedDependencyExtractor.$anonfun$findDependencies$2(CompilerBasedDependencyExtractor.scala:40)
        at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
        at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
        at scala.collection.immutable.HashSet.flatMap(HashSet.scala:34)
        at org.enso.languageserver.libraries.CompilerBasedDependencyExtractor.findDependencies(CompilerBasedDependencyExtractor.scala:40)
        at org.enso.libraryupload.LibraryUploader.$anonfun$updateManifest$1(LibraryUploader.scala:95)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at scala.util.Try$.apply(Try.scala:210)
        at org.enso.libraryupload.LibraryUploader.updateManifest(LibraryUploader.scala:94)
        at org.enso.runner.ProjectUploader$.updateManifest(ProjectUploader.scala:76)
        at org.enso.runner.Main$.main(Main.scala:1036)
        at org.enso.runner.Main.main(Main.scala)
```

Maybe it will help with debugging - apparently it's another `null` in `transformExpression`.

Can we have some measures to ensure statically that no nulls get there? Maybe with some annotation-based static analysis?

**Comment by JaroslavTulach** [comment]
> Can we have some measures to ensure statically that no nulls get there? 

Possibly `@NotNull` annotation would help us. If we used it consistently. Anyway, unless we get real storm of these issues, we just solve it as they arrive, without trying to upgrade level of our coding practice.
