### ISSUE TITLE
Buffer contents mismatch between IDE and engine leads to unrecoverable failure

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6099]
### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

A failure to synchronize between IDE and engine 
```
[enso] Error executing org.enso.interpreter.instrument.job.EnsureCompiledJob@6d95b55d
org.enso.interpreter.service.error.FailedToApplyEditsException: Some(Failed to apply edits for local.BookClub_3.Main, edits=***, failure=InvalidPosition(Position(33,0)), source='***')$modifyModuleSources$9(ExecutionService.java:384)
  at scala.util.Either.fold(Either.scala:190)
  at org.enso.interpreter.service.ExecutionService.modifyModuleSources(ExecutionService.java:381)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.applyEdit
  ...
```
appears to lead to an unresponsive IDE and working, but useless, engine that keeps throwing parsing issue in metadata's IDs section:
```
org.enso.syntax.text.Parser.ParserError: Some(Internal error in parser Could not deserialize idmap.)
  at org.enso.syntax.text.Parser.$anonfun$splitMeta$1(Parser.scala:37)
  at scala.util.Either$LeftProjection.map(Either.scala:614)
  at org.enso.syntax.text.Parser.splitMeta(Parser.scala:36)
  at org.enso.compiler.Compiler.parseMeta(Compiler.scala:712)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.buildCacheInvalidationCommands(EnsureCompiledJob.scala:275)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.invalidateCaches(EnsureCompiledJob.scala:304)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledModule$2(EnsureCompiledJob.scala:87)
  at scala.util.Either.map(Either.scala:382)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledModule$1(EnsureCompiledJob.scala:86)
  at scala.Option.map(Option.scala:242)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledModule(EnsureCompiledJob.scala:84)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledFiles$2(EnsureCompiledJob.scala:66)
  at scala.collection.immutable.List.map(List.scala:246)
  at scala.collection.immutable.List.map(List.scala:79)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledFiles(EnsureCompiledJob.scala:66)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:46)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:36)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:113)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
Caused by: io.circe.ParsingFailure: Some(expected : got 'size":...' (line 1, column 3468))
```

Further compilations also appeared to crash rust's parser:
```
[ERROR] lib/rust/parser/jni/src/lib.rs:64 Ignoring invalid metadata: invalid type: map, expected a sequence at line 1 column 0.
```
### Expected behaviour

A failure to synchronize between IDE and engine is, in general, hard to reconcile so one side (either IDE or engine) should give up and accept some loss of data and reload buffer's contents.

### How we can reproduce it?

No steps to reproduce yet. This happened while manipulating node's contents and fighting with CB's awkward suggestions. 

One step towards improving the current state is to try to simulate this undesired scenario via our existing test setup, if possible.

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment]
We have a bit of infrastructure in IDE, so we could technically reload the file once version mismatch is spotted. So it could be fixed on the IDE side.

But any instances of such desynchronization should be debugged anyway.

**Comment by hubertp** [comment]
> But any instances of such desynchronization should be debugged anyway.

Absolutely. I will add some more debugging info so that at least we know the circumstances under which the failure occurred. Right now it is pretty much "failed to apply text edit, deal with it and good luck".

**Comment by farmaazon** [comment]
I have a separate issue about recovering from synchronization failure https://github.com/enso-org/enso/issues/5203, so I'm unassigning myself from this.

**Comment by hubertp** [comment]
I haven't seen the second exception in a while, and the underlying issue has been remedied in #5203
