### ISSUE TITLE
Demo scenes crash when built with development profile

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#6180]
### What type of issue is this?

Permanent 

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When building the GUI with `./run gui watch --skip-wasm-opt --wasm-profile=dev` I cannot work with demo scenes, as they crash at runtime. 

The shown error is

```
pkg-opt.wasm:0x4eae1fc Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (pkg-opt.wasm:0x4eae1fc)
    at rust_panic (pkg-opt.wasm:0x4b5c85e)
    at std::panicking::rust_panic_with_hook::hdc43d6b15c221d2e (pkg-opt.wasm:0x2ec59b7)
    at std::panicking::begin_panic_handler::{{closure}}::h138701bc4f366007 (pkg-opt.wasm:0x390b5ce)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h6a334029ca520246 (pkg-opt.wasm:0x4b2abfd)
    at rust_begin_unwind (pkg-opt.wasm:0x47652b4)
    at core::panicking::panic_fmt::hfb8e3b4832705da8 (pkg-opt.wasm:0x4ab9223)
    at core::panicking::assert_failed_inner::hbe435a5cb328de46 (pkg-opt.wasm:0x1c64915)
    at core::panicking::assert_failed::h10ce3e73e7a46628 (pkg-opt.wasm:0x2f432c5)
    at ensogl_text_msdf::texture::Texture::set_data::hc253137f51a2265e (pkg-opt.wasm:0x1896dfa)
    at ensogl_text::font::FontTemplate<ensogl_text::font::NonVariableFamily>::load_cache::hc1d8d5d046b02804 (pkg-opt.wasm:0xb67089)
    at ensogl_text::font::Embedded::load_font::{{closure}}::h9e576e91f37c9a62 (pkg-opt.wasm:0xeabf47)
    at core::option::Option<T>::map::h812b6955fac1e67f (pkg-opt.wasm:0x260612c)
    at ensogl_text::font::Embedded::load_font::hfb05c129d877afd3 (pkg-opt.wasm:0x37adbd1)
    at ensogl_text::font::RegistryData::try_load::hbab6d8939fcc9bf7 (pkg-opt.wasm:0xba19de)
    at ensogl_text::font::RegistryData::load::h46a39297e589e87f (pkg-opt.wasm:0x3a2ec6b)
    at ensogl_text::font::Registry::load::hafd30540ca4c3782 (pkg-opt.wasm:0x3949c0d)
    at ensogl_text::font::glyph::System::new::h5b972a0d0dd8385f (pkg-opt.wasm:0x18e12b2)
    at ensogl_text::component::text::TextModel::new::hb1a5f7c9c161e5e0 (pkg-opt.wasm:0xa0e38f)
    at ensogl_text::component::text::Text::new::h98de8e1d3022ffc2 (pkg-opt.wasm:0x199b0e7)
    at ide_view::status_bar::Model::new::hda3159a0711aa135 (pkg-opt.wasm:0xe0b5a8)
    at ide_view::status_bar::View::new::hd562ab344ff21701 (pkg-opt.wasm:0x20d665)
    at ide_view::root::Model::new::h5f753d224d012cd0 (pkg-opt.wasm:0x19a2e30)
    at ide_view::root::View::new::ha32b3bd90382fd6d (pkg-opt.wasm:0x177aa06)
    at <ide_view::root::View as ensogl_core::application::command::View>::new::h94d5f0999daf825f (pkg-opt.wasm:0x4e425f9)
    at ensogl_core::application::view::Registry::new_view::h08cbfd448d71d041 (pkg-opt.wasm:0x275ad60)
    at ensogl_core::application::Application::new_view::h59eb072516dc9b7e (pkg-opt.wasm:0x4ad46b1)
    at debug_scene_interface::init::h0ff58b610b7da9f4 (pkg-opt.wasm:0x2218bf)
    at debug_scene_interface::entry_point_interface::{{closure}}::he642a50c27b6c0a9 (pkg-opt.wasm:0x43e8f54)
    at <T as wasm_bindgen::closure::WasmClosureFnOnce<(),R>>::into_js_function::{{closure}}::h0e4cc72217bf0820 (pkg-opt.wasm:0x188b480)
    at <dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0f9200bad88708f3 (pkg-opt.wasm:0x3d49aa2)
    at __wbg_adapter_88 (eval at <anonymous> (index.ts:279:37), <anonymous>:17087:8)
    at real (eval at <anonymous> (index.ts:279:37), <anonymous>:16922:14)
    at Module.onRuntimeInitialized (eval at <anonymous> (index.ts:279:37), <anonymous>:13434:5)
    at doRun (eval at <anonymous> (index.ts:279:37), <anonymous>:16540:37)
    at run (eval at <anonymous> (index.ts:279:37), <anonymous>:16552:5)
    at runCaller (eval at <anonymous> (index.ts:279:37), <anonymous>:16518:5)
    at removeRunDependency (eval at <anonymous> (index.ts:279:37), <anonymous>:13811:7)
    at receiveInstance (eval at <anonymous> (index.ts:279:37), <anonymous>:13892:5)
    at receiveInstantiationResult (eval at <anonymous> (index.ts:279:37), <anonymous>:13896:5)

```

when executing `showLogs()`

another error is shown:

```

router.ts:48 panicked at 'assertion failed: '(left == right)'
  left: '6144',
 right: '32', lib/rust/ensogl/component/text/src/font/msdf/src/texture.rs:87:9

Stack:

Error
    at eval (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:17793:19)
    at logError (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:16936:14)
    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:17792:12)
    at console_error_panic_hook::Error::new::h089d5da412a450cc (http://localhost:8080/pkg-opt.wasm:wasm-function[414512]:0x4d6c97d)
    at console_error_panic_hook::format_panic_impl::h81fa303ff68f5b78 (http://localhost:8080/pkg-opt.wasm:wasm-function[84924]:0x2d2f343)
    at console_error_panic_hook::format_panic::hd347a3ec156114f0 (http://localhost:8080/pkg-opt.wasm:wasm-function[473856]:0x4e4c7d1)
    at enso_web::report_panic::he0fbc91535466bec (http://localhost:8080/pkg-opt.wasm:wasm-function[19463]:0x196fe3e)
    at core::ops::function::Fn::call::he49ee373b556e9fa (http://localhost:8080/pkg-opt.wasm:wasm-function[329838]:0x4aa1d22)
    at std::panicking::rust_panic_with_hook::hdc43d6b15c221d2e (http://localhost:8080/pkg-opt.wasm:wasm-function[92674]:0x2ec598a)
    at std::panicking::begin_panic_handler::{{closure}}::h138701bc4f366007 (http://localhost:8080/pkg-opt.wasm:wasm-function[150520]:0x390b5ce)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h6a334029ca520246 (http://localhost:8080/pkg-opt.wasm:wasm-function[340273]:0x4b2abfd)
    at rust_begin_unwind (http://localhost:8080/pkg-opt.wasm:wasm-function[280889]:0x47652b4)
    at core::panicking::panic_fmt::hfb8e3b4832705da8 (http://localhost:8080/pkg-opt.wasm:wasm-function[331425]:0x4ab9223)
    at core::panicking::assert_failed_inner::hbe435a5cb328de46 (http://localhost:8080/pkg-opt.wasm:wasm-function[25844]:0x1c64915)
    at core::panicking::assert_failed::h10ce3e73e7a46628 (http://localhost:8080/pkg-opt.wasm:wasm-function[95106]:0x2f432c5)
    at ensogl_text_msdf::texture::Texture::set_data::hc253137f51a2265e (http://localhost:8080/pkg-opt.wasm:wasm-function[17870]:0x1896dfa)
    at ensogl_text::font::FontTemplate<ensogl_text::font::NonVariableFamily>::load_cache::hc1d8d5d046b02804 (http://localhost:8080/pkg-opt.wasm:wasm-function[3262]:0xb67089)
    at ensogl_text::font::Embedded::load_font::{{closure}}::h9e576e91f37c9a62 (http://localhost:8080/pkg-opt.wasm:wasm-function[5462]:0xeabf47)
    at core::option::Option<T>::map::h812b6955fac1e67f (http://localhost:8080/pkg-opt.wasm:wasm-function[54863]:0x260612c)
    at ensogl_text::font::Embedded::load_font::hfb05c129d877afd3 (http://localhost:8080/pkg-opt.wasm:wasm-function[141637]:0x37adbd1)
    at ensogl_text::font::RegistryData::try_load::hbab6d8939fcc9bf7 (http://localhost:8080/pkg-opt.wasm:wasm-function[3391]:0xba19de)
    at ensogl_text::font::RegistryData::load::h46a39297e589e87f (http://localhost:8080/pkg-opt.wasm:wasm-function[157997]:0x3a2ec6b)
    at ensogl_text::font::Registry::load::hafd30540ca4c3782 (http://localhost:8080/pkg-opt.wasm:wasm-function[152117]:0x3949c0d)
    at ensogl_text::font::glyph::System::new::h5b972a0d0dd8385f (http://localhost:8080/pkg-opt.wasm:wasm-function[18398]:0x18e12b2)
    at ensogl_text::component::text::TextModel::new::hb1a5f7c9c161e5e0 (http://localhost:8080/pkg-opt.wasm:wasm-function[2581]:0xa0e38f)
    at ensogl_text::component::text::Text::new::h98de8e1d3022ffc2 (http://localhost:8080/pkg-opt.wasm:wasm-function[19796]:0x199b0e7)
    at ide_view::status_bar::Model::new::hda3159a0711aa135 (http://localhost:8080/pkg-opt.wasm:wasm-function[4964]:0xe0b5a8)
    at ide_view::status_bar::View::new::hd562ab344ff21701 (http://localhost:8080/pkg-opt.wasm:wasm-function[426]:0x20d665)
    at ide_view::root::Model::new::h5f753d224d012cd0 (http://localhost:8080/pkg-opt.wasm:wasm-function[19857]:0x19a2e30)
    at ide_view::root::View::new::ha32b3bd90382fd6d (http://localhost:8080/pkg-opt.wasm:wasm-function[15955]:0x177aa06)
    at <ide_view::root::View as ensogl_core::application::command::View>::new::h94d5f0999daf825f (http://localhost:8080/pkg-opt.wasm:wasm-function[470589]:0x4e425f9)
    at ensogl_core::application::view::Registry::new_view::h08cbfd448d71d041 (http://localhost:8080/pkg-opt.wasm:wasm-function[59807]:0x275ad60)
    at ensogl_core::application::Application::new_view::h59eb072516dc9b7e (http://localhost:8080/pkg-opt.wasm:wasm-function[333280]:0x4ad46b1)
    at debug_scene_interface::init::h0ff58b610b7da9f4 (http://localhost:8080/pkg-opt.wasm:wasm-function[435]:0x2218bf)
    at debug_scene_interface::entry_point_interface::{{closure}}::he642a50c27b6c0a9 (http://localhost:8080/pkg-opt.wasm:wasm-function[241827]:0x43e8f54)
    at <T as wasm_bindgen::closure::WasmClosureFnOnce<(),R>>::into_js_function::{{closure}}::h0e4cc72217bf0820 (http://localhost:8080/pkg-opt.wasm:wasm-function[17789]:0x188b480)
    at <dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h0f9200bad88708f3 (http://localhost:8080/pkg-opt.wasm:wasm-function[180820]:0x3d49aa2)
    at __wbg_adapter_88 (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:17087:8)
    at real (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:16922:14)
    at Module.onRuntimeInitialized (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:13434:5)
    at doRun (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:16540:37)
    at run (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:16552:5)
    at runCaller (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:16518:5)
    at removeRunDependency (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:13811:7)
    at receiveInstance (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:13892:5)
    at receiveInstantiationResult (eval at <anonymous> (http://localhost:8080/index.js:74:5698), <anonymous>:13896:5)

```

### Expected behaviour

Demo scenes should work. 

### How we can reproduce it?

Run `./run gui watch --skip-wasm-opt --wasm-profile=dev`
Open Chrome and go to `http://localhost:8080/?startup.entry=interface`

### Enso Version

0d7682b6ec3cdea65e8ef713476af926f9fff1fc

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

Version 111.0.5563.64 (Official Build) Manjaro Linux (64-bit)

### Operating System

Linux

**Comment by farmaazon** [comment]
Looks like some assertion leaked. Perhaps it is as simple as removing it?

**Comment by MichaelMauderer** [comment]
Maybe, but, someone who knows the code should first check whether this is allowed to fail.

**Comment by kazcw** [comment]
Looks like a second case of #6011. I see what the problem is (effectively only the assertion is wrong); I'll fix it this morning. I didn't realize our default build has debug assertions disabled, so this check is only exercised in the rare case someone uses `--wasm-profile=dev`.
