### ISSUE TITLE
GUI froze when editing the node

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6197]
### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Trying to set the function name from scratch in a node and was deleting `operator2` when IDE suddenly froze and became completely unresponsive.
Here is the panic report from dev tools:
```
Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (pkg-opt.wasm:0x1dc9257)
    at rust_panic (pkg-opt.wasm:0x1db1f21)
    at std::panicking::rust_panic_with_hook::hdc43d6b15c221d2e (pkg-opt.wasm:0x1a9d5c0)
    at std::panicking::begin_panic_handler::{{closure}}::h138701bc4f366007 (pkg-opt.wasm:0x1c95198)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h6a334029ca520246 (pkg-opt.wasm:0x1daee21)
    at rust_begin_unwind (pkg-opt.wasm:0x1d1ff4b)
    at core::panicking::panic_fmt::hfb8e3b4832705da8 (pkg-opt.wasm:0x1d89bee)
    at core::panicking::panic_bounds_check::h121b7ecff4eb230d (pkg-opt.wasm:0x1cc45b6)
    at ensogl_core::system::gpu::data::attribute::AttributeScopeData::update::h56c09b3c1c1102ad (pkg-opt.wasm:0x869d12)
    at ensogl_core::display::symbol::gpu::geometry::primitive::mesh::MeshData::update::h5643599c6e9ac99a (pkg-opt.wasm:0x133e9f8)
    at ensogl_core::display::symbol::gpu::Symbol::update::h14defbc8139ef700 (pkg-opt.wasm:0x133eb7a)
    at ensogl_core::display::symbol::gpu::registry::SymbolRegistry::update::h0b66634131afddf5 (pkg-opt.wasm:0x10aaa37)
    at ensogl_core::display::world::with_context::he3eddfe4dd361aa3 (pkg-opt.wasm:0x1c77ca3)
    at ensogl_core::display::scene::Scene::update::he85c7a3991b94848 (pkg-opt.wasm:0x7af6d5)
    at ensogl_core::display::world::WorldData::run_next_frame::ha41bf315f15b0164 (pkg-opt.wasm:0x116b1eb)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h89d240dbde0f5c1e (pkg-opt.wasm:0x1a69ccc)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h1b0cff5f921fe515 (pkg-opt.wasm:0xcabb16)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h579b3da86b06acf2 (pkg-opt.wasm:0x1a20811)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h1b0cff5f921fe515 (pkg-opt.wasm:0xcabb16)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hbf2af3adc01a1ef4 (pkg-opt.wasm:0x1ac323f)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h1b0cff5f921fe515 (pkg-opt.wasm:0xcabb16)
    at <core::option::Option<T> as enso_prelude::option::OptionOps>::for_each::h63d29c5ca9f41a5b (pkg-opt.wasm:0x1bbfa77)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h8a82fc965a0d36e7 (pkg-opt.wasm:0x1bde680)
    at enso_callback::Registry<F>::run_once_impl::h82799ed08af2b4f8 (pkg-opt.wasm:0xfad908)
    at <enso_callback::Registry<dyn core::ops::function::FnOnce<()>+Output = ()> as enso_callback::traits::RegistryRunner0>::run_all::ha78e6827a1b214ca (pkg-opt.wasm:0x1dc5040)
    at enso_frp::microtasks::SchedulerData::run_all::hfac16568a710fa3a (pkg-opt.wasm:0x11c6ae5)
    at enso_frp::microtasks::Scheduler::new::{{closure}}::{{closure}}::h078c4dd78c617564 (pkg-opt.wasm:0x1cd717f)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h732d4c84bcc03b1c (pkg-opt.wasm:0x1db5631)
    at __wbg_adapter_86 (eval at <anonymous> (index.ts:279:37), <anonymous>:16981:8)
    at real (eval at <anonymous> (index.ts:279:37), <anonymous>:16907:14)
```

Backend  continues to work just fine.

### Expected behaviour

IDE should not freeze.

### How we can reproduce it?

1. Select some method on `Table` e.g. `set`.
2. Now start manually editing the node by deleting and writing the name of the same method. Eventually you will be able to freeze the GUI.

### Screenshots or screencasts

![Screenshot from 2023-04-04 17-14-33](https://user-images.githubusercontent.com/292128/229838439-0dc99437-ea9e-48e0-b3d6-f4d818f55483.png)

https://user-images.githubusercontent.com/292128/229846018-c1589ef4-2372-44fd-8893-8cc0cefcbd86.mp4

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by hubertp** [comment]
OK. This is really repeatable and makes GUI unusable.

**Comment by sylwiabr** [comment]
I can reproduce on a package from this commit https://github.com/enso-org/enso/commit/b3e54aeb5480862608cc98c21bb042ef30aa24e6 . For me it's crashing when I am trying to select entry from a CB.

**Comment by vitvakatu** [comment]
Yep, caused by https://github.com/enso-org/enso/commit/b3e54aeb5480862608cc98c21bb042ef30aa24e6

**Comment by 4e6** [comment]
Bisecting showed that commit b3e54aeb5480862608cc98c21bb042ef30aa24e6 indeed introduces the issue.

**Comment by sylwiabr** [comment]
Please, revert the commit. @kazcw @wdanilo was QA done on this PR?

**Comment by hubertp** [comment]
Thanks. I can confirm that it is working again.
