### ISSUE TITLE
Backend stops evaluation with a `File_Not_Found` error.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6763]
Starting with a new project, add a `Meta.meta Any` node.
This will evaluate.
Edit the node the to `Meta.meta Pair`.

The evaluation will stop with a `File not found` error in the IDE logs.
![image](https://github.com/enso-org/enso/assets/4699705/a91b3f69-8ffb-4d26-a6aa-c8c62f450f04)

**Comment by hubertp** [comment]
Couldn't reproduce, asked James for more info.

**Comment by JaroslavTulach** [comment]
The only code that contains `File not found` message is in [FileManagerApi](https://github.com/enso-org/enso/blob/a32a2eafbadc75c8ad5d350f4932977c2f9bb127/engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala#L190). The message is sent by [ProjectInfoHandler](https://github.com/enso-org/enso/blob/a32a2eafbadc75c8ad5d350f4932977c2f9bb127/engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/workspace/ProjectInfoHandler.scala#L57) just after logging a message _"Could not find the package configuration in the project at"_

**Comment by JaroslavTulach** [comment]
> Couldn't reproduce

I cannot reproduce either.

**Comment by jdunkerley** [comment]
Running with a debugger attached.
When I change the `Meta.meta Any` to `Meta.meta Pair`

It dies trying to read from `Meta.enso` within the project folder. org/enso/languageserver/filemanager/FileManager.scala:97

This raises a FileSystemFailure.FileNotFound which is then returned as a ReadTextualFileResult and then an OpenFIleResponse before being serialised to FileNotFoundError and sent to the IDE.

Project source is:
```
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
from Standard.Table.Data.Column import Column
import Standard.Visualization

main =
    operator1 = "Press TAB key to create a new node"
    operator2 = Meta.meta Any
```

so nothing obviously wrong there.

Please advise what you want me to send to help diagnose but it is 100% repeatable on mine.

**Comment by jdunkerley** [comment]
It appears it caused by double clicking and then the IDE trying to enter the node of the StdLib function.
The backend then tries to get the `Meta.enso` file and then you get the `File not found`.
After that you need to restart.

cc: @farmaazon @hubertp

**Comment by jdunkerley** [comment]
Thanks to @radeusgd for working out what I was doing!

**Comment by Akirathan** [comment]
I tried to reproduce this, and I was unable to crash the LS:
![image](https://github.com/enso-org/enso/assets/14013887/86b69e31-f19b-4ebf-9af6-45baee6ce101)

After sending "File not found" message to the IDE, LS normally continues to work, no errors in the LS log.

**Comment by radeusgd** [comment]
> I tried to reproduce this, and I was unable to crash the LS: ![image](https://user-images.githubusercontent.com/14013887/239596020-86b69e31-f19b-4ebf-9af6-45baee6ce101.png)
> 
> After sending "File not found" message to the IDE, LS normally continues to work, no errors in the LS log.

Can you still compute new expressions in the IDE?

I'm not sure if LS full-on crashes. It does not do further processing.

With above ruled out, maybe it's a Windows only issue?

**Comment by hubertp** [comment]
I was able to reproduce. Will see if I can make it more fault tolerant on the backend.

**Comment by sylwiabr** [comment]
@radeusgd I reproduced it on MacOS so not a Windows-specific bug

**Comment by hubertp** [comment]
Underlying failure:
```
[warn] [2023-05-22T16:15:15.32Z] [enso] Execution of function main failed (Null receiver values are not supported by libraries.).
java.lang.NullPointerException: Some(Null receiver values are not supported by libraries.)
  at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.dispatch(LibraryFactory.java:528)
  at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.create(LibraryFactory.java:295)
  at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.specialize(InteropLibraryGen.java:9873)
  at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.isTime(InteropLibraryGen.java:9211)
  at org.enso.interpreter.node.expression.builtin.meta.TypeOfNodeGen.executeAndSpecialize(TypeOfNodeGen.java:395)
  at org.enso.interpreter.node.expression.builtin.meta.TypeOfNodeGen.execute(TypeOfNodeGen.java:215)
  at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.typeOf(IdExecutionInstrument.java:289)
  at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.onExpressionReturn(IdExecutionInstrument.java:257)
  at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.onReturnValue(IdExecutionInstrument.java:237)
  at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventProviderChainNode.innerOnReturnValue(ProbeNode.java:1392)
  at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onReturnValue(ProbeNode.java:995)
  at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode.onReturnValue(ProbeNode.java:231)
  at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:116)
  at org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric_generic1(AssignmentNodeGen.java:57)
  at org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric(AssignmentNodeGen.java:36)
  at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:114)
  at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:56)
  at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:114)
  at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:56)
  at org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:495)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:68)
  at org.enso.interpreter.node.callable.ExecuteCallNode.callDirect(ExecuteCallNode.java:91)
  at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeAndSpecialize(ExecuteCallNodeGen.java:137)
  at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:64)
  at org.enso.interpreter.node.callable.dispatch.SimpleCallOptimiserNode.executeDispatch(SimpleCallOptimiserNode.java:54)
  at org.enso.interpreter.node.callable.dispatch.CurryNode.doCall(CurryNode.java:157)
  at org.enso.interpreter.node.callable.dispatch.CurryNode.execute(CurryNode.java:108)
  at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeCached(InvokeFunctionNode.java:92)
  at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.executeAndSpecialize(InvokeFunctionNodeGen.java:102)
  at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:58)
  at org.enso.interpreter.node.callable.InteropApplicationNode.callCached(InteropApplicationNode.java:79)
  at org.enso.interpreter.node.callable.InteropApplicationNodeGen.execute(InteropApplicationNodeGen.java:46)
  at org.enso.interpreter.node.callable.FunctionCallInstrumentationNode$FunctionCall$Execute.callCached(FunctionCallInstrumentationNode.java:103)
  at org.enso.interpreter.node.callable.FunctionCallGen$InteropLibraryExports$Cached.execute(FunctionCallGen.java:75)
  at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7765)
  at org.enso.interpreter.service.ExecutionService$ExecuteRootNode.execute(ExecutionService.java:482)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:181)
  at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:222)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeProgram(ProgramExecutionSupport.scala:106)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$3(ProgramExecutionSupport.scala:215)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:391)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$2(ProgramExecutionSupport.scala:215)
  at scala.util.Either.flatMap(Either.scala:352)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.runProgram(ProgramExecutionSupport.scala:209)
  at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:38)
  at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:15)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:111)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
Caused by: com.oracle.truffle.api.TruffleStackTrace.LazyStackTrace: None
```

**Comment by JaroslavTulach** [comment]
@hubertp what have you done to get the exception stack trace? Why the stack trace wasn't visible in the original bug reports?

It'd be easier for all of us, if our logs contained exceptions with stacktraces.

**Comment by Akirathan** [comment]
> @hubertp what have you done to get the exception stack trace? Why the stack trace wasn't visible in the original bug reports?
> 
> It'd be easier for all of us, if our logs contained exceptions with stacktraces.

We have exception with stack traces in our logs. In this case, you don't even have to do verbose logging. Not attaching the stack trace to the issue is probably my fault when trying to reproduce the issue. It seems that I misunderstood the description and did a different sequence of steps, therefore, not bumping into this issue.

**Comment by hubertp** [comment]
> @hubertp what have you done to get the exception stack trace? Why the stack trace wasn't visible in the original bug reports?
> 
> It'd be easier for all of us, if our logs contained exceptions with stacktraces.

It is in the logs, that's how I got it.

**Comment by hubertp** [comment]
Also, another one I got while playing with this double-clicking on `Meta`:
```
[warn] [2023-05-23T13:59:59.972Z] [enso] Execution of function main failed (The null source not found.).
org.enso.interpreter.service.error.SourceNotFoundException: Some(The null source not found.)
  at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:162)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeProgram(ProgramExecutionSupport.scala:129)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$3(ProgramExecutionSupport.scala:215)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:391)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$2(ProgramExecutionSupport.scala:215)
  at scala.util.Either.flatMap(Either.scala:352)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.runProgram(ProgramExecutionSupport.scala:209)
  at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:38)
  at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:15)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:111)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
```

**Comment by JaroslavTulach** [comment]
> > @hubertp what have you done to get the exception stack trace? Why the stack trace wasn't visible in the original bug reports?
> > It'd be easier for all of us, if our logs contained exceptions with stacktraces.
> 
> It is in the logs, that's how I got it.

I see. Does that mean our new policy of _requiring log files to be attached to bug reports_ would help us resolve this issue without trying to reproduce the problem? Just by looking at attached logs?

**Comment by hubertp** [comment]
@JaroslavTulach I don't know exactly why we even send `1003: File not found` but the two seem to happen around the same activity. It can be that they are not related after all.

EDIT: it appears they are not exactly related.

**Comment by hubertp** [comment]
Once again apologies for mixing various problems here. I will file tickets for the above exceptions.

Back to the ticket. Isn't the unresponsive IDE/LS caused by the fact that before opening the file we issue a request to push the execution context down the stack but IDE never really pops it after a unsuccessful opening of the file? Shouldn't those requests be the other way around?
![Screenshot from 2023-05-23 18-05-39](https://github.com/enso-org/enso/assets/292128/75355fb8-0833-4790-949e-7d97fb66d74b)

**Comment by hubertp** [comment]
Yeap, it's a regression caused by https://github.com/enso-org/enso/pull/6617. If we don't send the request to push the context before an (failed) attempt to open the file, everything works as expected.

**Comment by farmaazon** [comment]
But I assume, as a rule, I _can_ push stack frame before (or without) opening a file? Can I?

**Comment by hubertp** [comment]
> But I assume, as a rule, I _can_ push stack frame before (or without) opening a file? Can I?

I think so. Just need to make sure to pop it on opening file failure or requests don't make sense to LS, as it was the case in this ticket.
