### ISSUE TITLE
Cannot call a static method with Polyglot.invoke

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#6784]
I tried to call a static method by using the type as object, but it did not work:

```
> Polyglot.invoke Locale "poland" []
Evaluation failed with: Message not supported.
java.lang.Exception: Message not supported.
	at <enso>.<eval>(Unknown Source)
	at <enso>.Debug.breakpoint(Unknown Source)
	at <enso>.Internal_Repl_Module___::Internal_Repl_Module___::internal_repl_entry_point___(Internal_Repl_Module___:4)
	at <unknown>.org.graalvm.polyglot.Value<Function>.execute(Unknown Source)
```

**Comment by jdunkerley** [comment]
Dynamic invocation of Enso methods doesn't work via Polyglot.invoke.
