### ISSUE TITLE
meta1 = meta1 triggers silent NPE

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6821]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Backend silently reports NPE when manually editing the node.
```
[warn] [2023-05-24T07:40:48.687Z] [enso] Execution of function main failed (Null receiver values are not supported by libraries.).
java.lang.NullPointerException: Some(Null receiver values are not supported by libraries.)
  at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.dispatch(LibraryFactory.java:528)
  at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.create(LibraryFactory.java:295)
  at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.specialize(InteropLibraryGen.java:9873)
  at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.isTime(InteropLibraryGen.java:9211)
  at org.enso.interpreter.node.expression.builtin.meta.TypeOfNodeGen.executeAndSpecialize(TypeOfNodeGen.java:395)
  at org.enso.interpreter.node.expression.builtin.meta.TypeOfNodeGen.execute(TypeOfNodeGen.java:215)
  at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.typeOf(IdExecutionInstrument.java:289)
  at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.onExpressionReturn(IdExecutionInstrument.java:257)
  at org.enso.interpreter.instrument.IdExecutionInstrument$IdExecutionEventNode.onReturnValue(IdExecutionInstrument.java:237)
  at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventProviderChainNode.innerOnReturnValue(ProbeNode.java:1392)
  at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode$EventChainNode.onReturnValue(ProbeNode.java:995)
  at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.ProbeNode.onReturnValue(ProbeNode.java:231)
  at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:116)
  at org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric_generic1(AssignmentNodeGen.java:57)
  at org.enso.interpreter.node.scope.AssignmentNodeGen.executeGeneric(AssignmentNodeGen.java:36)
  at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:114)
  at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:56)
  at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:114)
  at org.enso.interpreter.node.callable.function.BlockNode.executeGeneric(BlockNode.java:56)
  at org.enso.interpreter.node.ClosureRootNode.execute(ClosureRootNode.java:85)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callDirect(OptimizedCallTarget.java:495)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedDirectCallNode.call(OptimizedDirectCallNode.java:68)
  at org.enso.interpreter.node.callable.ExecuteCallNode.callDirect(ExecuteCallNode.java:91)
  at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeAndSpecialize(ExecuteCallNodeGen.java:137)
  at org.enso.interpreter.node.callable.ExecuteCallNodeGen.executeCall(ExecuteCallNodeGen.java:64)
  at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode$RepeatedCallNode.executeRepeating(LoopingCallOptimiserNode.java:216)
  at org.graalvm.truffle/com.oracle.truffle.api.nodes.RepeatingNode.executeRepeatingWithValue(RepeatingNode.java:112)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.profilingLoop(OptimizedOSRLoopNode.java:154)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedOSRLoopNode.execute(OptimizedOSRLoopNode.java:105)
  at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNode.dispatch(LoopingCallOptimiserNode.java:68)
  at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNodeGen.executeAndSpecialize(LoopingCallOptimiserNodeGen.java:59)
  at org.enso.interpreter.node.callable.dispatch.LoopingCallOptimiserNodeGen.executeDispatch(LoopingCallOptimiserNodeGen.java:44)
  at org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCall(IndirectCurryNode.java:132)
  at org.enso.interpreter.node.callable.dispatch.IndirectCurryNode.doCurry(IndirectCurryNode.java:78)
  at org.enso.interpreter.node.callable.dispatch.IndirectCurryNodeGen.executeAndSpecialize(IndirectCurryNodeGen.java:65)
  at org.enso.interpreter.node.callable.dispatch.IndirectCurryNodeGen.execute(IndirectCurryNodeGen.java:47)
  at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNode.invokeUncached(InvokeFunctionNode.java:141)
  at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.executeAndSpecialize(InvokeFunctionNodeGen.java:113)
  at org.enso.interpreter.node.callable.dispatch.InvokeFunctionNodeGen.execute(InvokeFunctionNodeGen.java:58)
  at org.enso.interpreter.node.callable.InteropApplicationNode.callCached(InteropApplicationNode.java:79)
  at org.enso.interpreter.node.callable.InteropApplicationNodeGen.execute(InteropApplicationNodeGen.java:46)
  at org.enso.interpreter.node.callable.FunctionCallInstrumentationNode$FunctionCall$Execute.callCached(FunctionCallInstrumentationNode.java:103)
  at org.enso.interpreter.node.callable.FunctionCallGen$InteropLibraryExports$Cached.execute(FunctionCallGen.java:75)
  at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.execute(InteropLibraryGen.java:7765)
  at org.enso.interpreter.service.ExecutionService$ExecuteRootNode.execute(ExecutionService.java:482)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:181)
  at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:222)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeProgram(ProgramExecutionSupport.scala:106)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$3(ProgramExecutionSupport.scala:215)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
  at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:391)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$2(ProgramExecutionSupport.scala:215)
  at scala.util.Either.flatMap(Either.scala:352)
  at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.runProgram(ProgramExecutionSupport.scala:209)
  at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:38)
  at org.enso.interpreter.instrument.job.ExecuteJob.run(ExecuteJob.scala:15)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:111)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
Caused by: com.oracle.truffle.api.TruffleStackTrace.LazyStackTrace: None
```

### Expected behaviour

No exception.

### How we can reproduce it?

1. Create a new node with `Meta` contents and finish the creation by accepting with Enter
2. ctrl+click to enter manual edition of the node
3. Double click (with a ctrl?) on `Meta` to select the text
4. ... an exception should appear in the logs

### Screenshots or screencasts

[Kazam_screencast_00010.webm](https://github.com/enso-org/enso/assets/292128/a1754e2b-dc33-472a-90dd-3130dc62398f)

### Logs

[out11.txt](https://github.com/enso-org/enso/files/11551825/out11.txt)

### Enso Version

62fecfa474e3958ce6fda54c00ef91a86bfa2c2e

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by JaroslavTulach** [comment]
This line
```
 at org.enso.interpreter.node.ExpressionNodeWrapper.executeGeneric(ExpressionNodeWrapper.java:116)
```
must be sending `null` to the instrument. Try to print which node is `getInstrumentedNode()`.

**Comment by hubertp** [comment]
The first ExpressionNode is for the one that results in `null`, the second one is for the whole node that resulted in NPE:
[null_node.txt](https://github.com/enso-org/enso/files/11555854/null_node.txt)

It doesn't seem very revealing on first sight.

**Comment by hubertp** [comment]
I think I have it. Somehow the steps to reproduce, namely the whole selection of `Meta`, end up rewriting the code from
```
meta1 = Meta
```
to
```
meta1 = meta1
```
That would certainly explain the NPE.

**Comment by JaroslavTulach** [comment]
> meta1 = meta1

There are two ways to fix this:
- throw a compilation error - using uninitialized variable is wrong
- make sure the `null` is converted to `Nothing` - I do remember @kustosz arguing once for getting ready for uninitialized variables - don't remember why, but should they exist - then `Nothing` would be their value

Great discovery. I can confirm `m.enso`:
```haskell
main = 
    m1 = m1
    m1
```
yields
```
$ enso --run m.enso
Execution finished with an error: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "receiver" is null
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext$ToHostValueNode.execute(PolyglotLanguageContext.java:857)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch$InteropValue$ExecuteNoArgsNode.executeImpl(PolyglotValueDispatch.java:4375)
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.HostToGuestRootNode.execute(HostToGuestRootNode.java:124)
        at <java> org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:878)
        at <java> org.enso.polyglot.Function.execute(Function.scala:16)
        at <java> org.enso.runner.Main$.runMain(Main.scala:836)
```

**Comment by hubertp** [comment]
@farmaazon regarding IDE behaviour - is it expected that when I select the expression in the assignment it replaces it by the variable itself?

**Comment by farmaazon** [comment]
> @farmaazon regarding IDE behaviour - is it expected that when I select the expression in the assignment it replaces it by the variable itself?

Again, this is about how CB previews work. When you edit node, and you are inside "Meta" string, we try to find the best matching entry _and preview it_. Preview means: we temporarily update the code.

On the screencast, you may see that `meta1` is picked as the best match. We don't find `Meta` perhaps because it's marked with PRIVATE tag.

**Comment by JaroslavTulach** [comment]
> you may see that `meta1` is picked as the best match

Can you find that the node is assigning value to `meta1` variable out? Couldn't you then skip such self-assigning offer?

We've been chatting with Hubert about possible fix on the engine side:
- clearly we cannot continue to throw `NullPointerException: Some(Null receiver values are not supported by libraries.)`
- we could raise a compilation error: `= meta1` is an **unknown variable** before the assignment happens
- we could accept `meta1 = meta1` code and just treat all unassigned variables as having `Nothing` value

I am trying to convince Hubert that reporting compilation error with **unknown variable** provides better programming experience. However that implies `meta1 = meta1` yields an uncompilable code where _nothing executes_ - that's not good for the IDE user experience. How to align these two perspectives (textual & visual)?

If the IDE _avoided self assignments_ itself, then we could _report compilation error_ without any worries as the problem wouldn't happen in the IDE (easily).

**Comment by farmaazon** [comment]
> Can you find that the node is assigning value to meta1 variable out? Couldn't you then skip such self-assigning offer?

Yes, we can. But this not resolve the "compilation error dilemma" entirely, as the user always can write anything they want (including meta1) and press ctrl+enter.

I think compile errors are turned into Panics in IDE, aren't they? If even then they forbid evaluation of independent nodes being lower in the code, we indeed have an UX problem.

**Comment by farmaazon** [comment]
I will create an issue for problems with local variables in CB (there are more than "self-assignment" mentioned here).

**Comment by JaroslavTulach** [comment]
> all unassigned variables as having `Nothing` value

Correction: unassigned variables should probably have `DataflowError.throw` value.

**Comment by radeusgd** [comment]
Note that we've been tracking the issue of cyclic/recursive definitions at #5500, it seems to have been de-prioritized after the bugtracker migration.

_I wonder how many other bugs have been forgotten this way 😕_

**Comment by farmaazon** [comment]
> I will create an issue for problems with local variables in CB (there are more than "self-assignment" mentioned here).

Created as #6915
