### ISSUE TITLE
IDE unresponsive after reported RuntimeError

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6952]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

IDE becomes unresponsive after a short moment of opening a project.
That project worked before for me but when I tried to bisect, IDE continued to behave the same way since at least 20/05. So not sure what is happening.

Encountered error in the logs after which it freezes:
```
Uncaught (in promise) RuntimeError: unreachable
    at __rg_oom (pkg-opt.wasm:0x20d9554)
    at __rust_alloc_error_handler (pkg-opt.wasm:0x20e11d9)
    at alloc::alloc::handle_alloc_error::rt_error::h81daab63a51f18b0 (pkg-opt.wasm:0x20e3bce)
    at alloc::alloc::handle_alloc_error::h724d9ce32b41bdb0 (pkg-opt.wasm:0x20e3bc2)
    at hashbrown::raw::Fallibility::alloc_err::hac56deb9e035bdb0 (pkg-opt.wasm:0x20d49c2)
    at hashbrown::raw::RawTable<T,A>::reserve_rehash::hbb6aeec93c8874be (pkg-opt.wasm:0xc43d54)
    at hashbrown::raw::RawTable<T,A>::insert::h0b0a9282fb108104 (pkg-opt.wasm:0x17282c4)
    at ide_view_graph_editor::builtin::visualization::native::text_visualization::grid_cache::GridCache<T>::add_item::hea7d6a8e547283ce (pkg-opt.wasm:0x1898742)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::he0a67ebf8625b97a (pkg-opt.wasm:0x128f8bb)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hcebd7b085828d0a7 (pkg-opt.wasm:0xaf8dcb)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::he1ad4c1861193edf (pkg-opt.wasm:0xc050b3)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h2ebbd73d9e15e5f0 (pkg-opt.wasm:0x1709d58)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::he1ad4c1861193edf (pkg-opt.wasm:0xc050b3)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hf4c924d140d8d671 (pkg-opt.wasm:0x1697717)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h0834216cae92cecb (pkg-opt.wasm:0xd472d2)
    at enso_frp::nodes::<impl enso_frp::stream::WeakNode<enso_frp::nodes::SourceData<Out>>>::emit::hb2bcd689f4d1781a (pkg-opt.wasm:0x1da0d57)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::ha1505055da1b70d7 (pkg-opt.wasm:0x1a410b2)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h0834216cae92cecb (pkg-opt.wasm:0xd472d2)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hd3da4882c69afb66 (pkg-opt.wasm:0x1619489)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h6591ce7aacd94b32 (pkg-opt.wasm:0xc02324)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hb4c9fcb4e623ab7b (pkg-opt.wasm:0xd179b1)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h734ca0b6db5920de (pkg-opt.wasm:0x1d61127)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::hb4c9fcb4e623ab7b (pkg-opt.wasm:0xd179b1)
    at enso_frp::nodes::<impl enso_frp::stream::WeakNode<enso_frp::nodes::SourceData<Out>>>::emit::h4aff3afa977b3a63 (pkg-opt.wasm:0x1e55372)
    at enso_prelude::channel::process_stream_with_handle::{{closure}}::h5d315c3f726370d7 (pkg-opt.wasm:0x6ff6c2)
    at futures_util::stream::stream::StreamExt::poll_next_unpin::hd5cdf71362d04e41 (pkg-opt.wasm:0x1027662)
    at futures_executor::local_pool::LocalPool::poll_pool::h7ce81f29ccaebc5f (pkg-opt.wasm:0x1f46ffa)
    at std::thread::local::LocalKey<T>::with::h4a6abba7ccc7bacd (pkg-opt.wasm:0x1d86709)
    at futures_executor::local_pool::LocalPool::run_until_stalled::h25d91c1db5b97c4e (pkg-opt.wasm:0x1f6d0db)
    at <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut::h6de2aa7aaaeaab99 (pkg-opt.wasm:0x1faab6f)
    at alloc::vec::Vec<T,A>::retain_mut::haffbc1f3a45f6f28 (pkg-opt.wasm:0x15c42c6)
    at <enso_callback::Registry<dyn core::ops::function::FnMut<(T1,)>+Output = ()> as enso_callback::traits::RegistryRunner1>::run_all::h16c963e470113c33 (pkg-opt.wasm:0x148ff63)
    at core::ops::function::FnOnce::call_once{{vtable.shim}}::h25add263b958d432 (pkg-opt.wasm:0x1e8a894)
    at enso_callback::Registry<F>::run_once_impl::h7f2241b9d9086ac8 (pkg-opt.wasm:0x11505ab)
    at <enso_callback::Registry<dyn core::ops::function::FnOnce<()>+Output = ()> as enso_callback::traits::RegistryRunner0>::run_all::h56bb07efb2430239 (pkg-opt.wasm:0x20e681c)
    at enso_frp::microtasks::SchedulerData::run_all::h9556a12f55b8c1c5 (pkg-opt.wasm:0x146dbd8)
    at enso_frp::microtasks::Scheduler::new::{{closure}}::{{closure}}::h3c9a8723b73c4a5c (pkg-opt.wasm:0x1fd8fff)
    at <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h9aba2225acfb79ee (pkg-opt.wasm:0x20d632a)
    at __wbg_adapter_92 (eval at <anonymous> (index.ts:296:37), <anonymous>:16987:8)
    at real (eval at <anonymous> (index.ts:296:37), <anonymous>:16907:14)
```

### Expected behaviour

IDE shouldn't freeze.

### How we can reproduce it?

[Unnamed_42.zip](https://github.com/enso-org/enso/files/11654366/Unnamed_42.zip)
For me it is 100% reproducible with the above project. 

Behaves in the same way in the locally built version as well with a standalone.

### Screenshots or screencasts

![Screenshot from 2023-06-05 17-51-53](https://github.com/enso-org/enso/assets/292128/00f2b001-a4b6-4f35-8da0-2bc77fd6af15)

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution (local project), Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by Akirathan** [comment]
I can reproduce this on the latest develop 03d725b829e234a92c27dafcc43cb56671f0586f. Nevertheless, what I am also seeing are 3 attach visualization request timeouts, and they seem to happen at a similar time to the aforementioned runtime error throw from `handle_alloc_error`. Looking at the stack trace, I am guessing that the exception was thrown when some visualization was computed? This might be related to the visualizations timing out? Maybe some race conditions?

Because of my observations, I think this is related to https://github.com/enso-org/enso/issues/6724.

**Comment by Akirathan** [comment]
Can also reproduce on `enso-linux-2023.2.1-nightly.2023.6.5.AppImage`. Moreover, I have now observed, that the RuntimeError from the IDE side is an immediate reaction to the timeout responses from LS.
![image](https://github.com/enso-org/enso/assets/14013887/a688fef9-b96b-4f45-a377-afadfe97c9ea)

**Comment by hubertp** [comment]
@Akirathan I would suggest to file a separate ticket for failed visualization (and it's probably a library issue). Such response should never render the whole IDE unusuable, so I would suggest to unassign me.

**Comment by farmaazon** [comment]
Attached project works fine in GUI2 - there's no rust panics there after all.
