### ISSUE TITLE
TableVisualization silently crashes in UI

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7050]
Stacktrace:
```
router.ts:48 [WARN] app/gui/view/graph-editor/src/component/visualization/foreign/java_script/instance.rs:239 Failed to call method Function { obj: Object { obj: JsValue(Function(onDataReceived)) } } with error: JsValue(TypeError: Cannot read properties of undefined (reading 'map')
TypeError: Cannot read properties of undefined (reading 'map')
    at TableVisualization.onDataReceived (eval at new_function_with_args (eval at <anonymous> (http://localhost:8080/index.js:74:4187)), <anonymous>:283:67)
    at eval (eval at <anonymous> (http://localhost:8080/index.js:74:4187), <anonymous>:18546:35)
    at handleError (eval at <anonymous> (http://localhost:8080/index.js:74:4187), <anonymous>:17093:14)
    at imports.wbg.__wbg_call_9495de66fdbe016b (eval at <anonymous> (http://localhost:8080/index.js:74:4187), <anonymous>:18545:12)
    at js_sys::Function::call1::h81a361b4f3fa3524 (http://localhost:8080/pkg-opt.wasm:wasm-function[52581]:0x20e928b)
    at ide_view_graph_editor::component::visualization::foreign::java_script::instance::InstanceModel::try_call1::ha5522817e1d8f230 (http://localhost:8080/pkg-opt.wasm:wasm-function[19039]:0x18b0f17)
    at ide_view_graph_editor::component::visualization::foreign::java_script::instance::InstanceModel::receive_data::hd4dc86890cbe9e7d (http://localhost:8080/pkg-opt.wasm:wasm-function[39793]:0x1f01907)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h1e7c518d5bc690fe (http://localhost:8080/pkg-opt.wasm:wasm-function[29554]:0x1c770f0)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h6d460008f96bde67 (http://localhost:8080/pkg-opt.wasm:wasm-function[3955]:0xd64b7b)
    at enso_frp::nodes::<impl enso_frp::stream::WeakNode<enso_frp::nodes::SourceData<Out>>>::emit::h655aa04af3b0ce78 (http://localhost:8080/pkg-opt.wasm:wasm-function[36725]:0x1e54c02)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::h2b634bab66be888e (http://localhost:8080/pkg-opt.wasm:wasm-function[24390]:0x1ac0da4)
```

**Comment by hubertp** [comment]
@jdunkerley let me know if I should spend time trying to figure out which node is causing this. It happened on the Enso 201 project.

**Comment by hubertp** [comment]
[Warnings_3.zip](https://github.com/enso-org/enso/files/11788915/Warnings_3.zip)

Happens when showing full screen visualization for:
![Screenshot from 2023-06-19 16-03-12](https://github.com/enso-org/enso/assets/292128/200feb14-ae5f-49ff-98e6-0bebddc06100)

**Comment by farmaazon** [comment]
No longer reproducible in GUI2
