### ISSUE TITLE
Dashboard Errors in Developer Console

### ISSUE THREAD

**Issue by JanBeelte** [enso-org/enso#7083]
### Discord username

Zylinderman#4528

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I start the IDE the developer console instantly shows the following error:
`Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.`

As soon as I open a project the following error shows up:
`Warning: Cannot update a component (`Dashboard`) while rendering a different component (`ProjectActionButton`). To locate the bad setState() call inside `ProjectActionButton`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render`

I do not see any cloud projects, when I move to the cloud tab it displays:
![image](https://github.com/enso-org/enso/assets/114063253/d03ea22d-7025-473f-a2c5-aeef7f4cab82)

### Expected behaviour

No errors in developer console.

### Logs

router.ts:62 Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
    at button
    at div
    at div
    at button
    at TemplatesRender (http://localhost:8080/index.js:56865:11)
    at div
    at div
    at Templates (http://localhost:8080/index.js:56907:11)
    at div
    at Dashboard (http://localhost:8080/index.js:57899:11)
    at RenderedRoute (http://localhost:8080/index.js:35163:5)
    at Outlet (http://localhost:8080/index.js:35348:26)
    at ProtectedLayout (http://localhost:8080/index.js:55732:23)
    at RenderedRoute (http://localhost:8080/index.js:35163:5)
    at Routes (http://localhost:8080/index.js:35408:5)
    at ModalProvider (http://localhost:8080/index.js:55822:11)
    at AuthProvider (http://localhost:8080/index.js:55510:11)
    at BackendProvider (http://localhost:8080/index.js:54912:11)
    at SessionProvider (http://localhost:8080/index.js:55442:11)
    at LoggerProvider (http://localhost:8080/index.js:55020:11)
    at AppRouter (http://localhost:8080/index.js:62410:19)
    at Router (http://localhost:8080/index.js:35355:15)
    at MemoryRouter (http://localhost:8080/index.js:35292:5)
    at App
consume @ router.ts:62
router.ts:62 Warning: Cannot update a component (`Dashboard`) while rendering a different component (`ProjectActionButton`). To locate the bad setState() call inside `ProjectActionButton`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at ProjectActionButton (http://localhost:8080/index.js:56351:5)
    at div
    at td
    at tr
    at Rows (http://localhost:8080/index.js:56779:11)
    at tbody
    at table
    at div
    at Dashboard (http://localhost:8080/index.js:57899:11)
    at RenderedRoute (http://localhost:8080/index.js:35163:5)
    at Outlet (http://localhost:8080/index.js:35348:26)
    at ProtectedLayout (http://localhost:8080/index.js:55732:23)
    at RenderedRoute (http://localhost:8080/index.js:35163:5)
    at Routes (http://localhost:8080/index.js:35408:5)
    at ModalProvider (http://localhost:8080/index.js:55822:11)
    at AuthProvider (http://localhost:8080/index.js:55510:11)
    at BackendProvider (http://localhost:8080/index.js:54912:11)
    at SessionProvider (http://localhost:8080/index.js:55442:11)
    at LoggerProvider (http://localhost:8080/index.js:55020:11)
    at AppRouter (http://localhost:8080/index.js:62410:19)
    at Router (http://localhost:8080/index.js:35355:15)
    at MemoryRouter (http://localhost:8080/index.js:35292:5)
    at App

### Enso Version

90df5adfb0641d8c771b3ae50f3bc5092b5f01af

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Manjaro  5.15.114-2-MANJARO #1 SMP PREEMPT Sun Jun 4 10:32:43 UTC 2023 x86_64 GNU/Linux

**Comment by MichaelMauderer** [comment]
I cannot seem to reproduce it, but it might depend on the state of the dashboard (in this example there are no cloud projects).

**Comment by farmaazon** [comment]
I've seen it today. It may be system-dependent (I also use Linux).

**Comment by JanBeelte** [comment]
What is interesting I get it in Electron, Firefox and Google Chrome.

**Comment by wdanilo** [comment]
CC @somebody1234
