### ISSUE TITLE
A panic is reported in the console when closing a project

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7144]
Repro:

1. Create a new project, wait for it to initialize.
2. Click on the 'hamburger button' to go back to the project list.
3. Hit the 'stop' button.
4. Observe the terminal output.

I see:
```
IPC error: "panicked at 'called `Option::unwrap()` on a `None` value', lib\\rust\\ensogl\\core\\src\\display\\world.rs:415:37\n\nStack:\n\nError\n    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:74:4187), <anonymous>:17591:17)\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[30777]:0x1795679\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[15694]:0x14db7e9\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[26785]:0x16f8713\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[20394]:0x1666e9a\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[10601]:0x1269cbd\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[10264]:0x12348a1\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[410]:0x135011\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[1049]:0x67d8a3\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[28971]:0x1730b2f\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[3407]:0xb9f489\n    at http://localhost:8080/pkg-opt.wasm:wasm-function[30897]:0x1799e65\n    at GB.stop (http://localhost:8080/index.js:74:4084)\n    at E7.stopApp (http://localhost:8080/index.js:1066:23572)\n    at L (http://localhost:8080/index.js:305:32741)\n    at onClick (http://localhost:8080/index.js:305:33610)\n    at Object.XA (http://localhost:8080/index.js:5:9858)\n    at eI (http://localhost:8080/index.js:5:10012)\n    at tI (http://localhost:8080/index.js:5:10069)\n    at wd (http://localhost:8080/index.js:5:31464)\n    at qp (http://localhost:8080/index.js:5:31881)\n    at http://localhost:8080/index.js:5:36794\n    at M5 (http://localhost:8080/index.js:8:36898)\n    at vp (http://localhost:8080/index.js:5:8991)\n    at G0 (http://localhost:8080/index.js:5:33168)\n    at o5 (http://localhost:8080/index.js:5:17363)\n    at gI (http://localhost:8080/index.js:5:17147)\n\n"
```

No serious failures occur - the project seems to be closed and can be reopened. But it seems that such a panic should not be occurring.

**Comment by radeusgd** [comment]
Better formatted from the Chrome Dev tools:

```
router.ts:48 panicked at 'called `Option::unwrap()` on a `None` value', lib\rust\ensogl\core\src\display\world.rs:415:37

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:74:4187), <anonymous>:17591:17)
    at http://localhost:8080/pkg-opt.wasm:wasm-function[30777]:0x1795679
    at http://localhost:8080/pkg-opt.wasm:wasm-function[15694]:0x14db7e9
    at http://localhost:8080/pkg-opt.wasm:wasm-function[26785]:0x16f8713
    at http://localhost:8080/pkg-opt.wasm:wasm-function[20394]:0x1666e9a
    at http://localhost:8080/pkg-opt.wasm:wasm-function[10601]:0x1269cbd
    at http://localhost:8080/pkg-opt.wasm:wasm-function[10264]:0x12348a1
    at http://localhost:8080/pkg-opt.wasm:wasm-function[410]:0x135011
    at http://localhost:8080/pkg-opt.wasm:wasm-function[1049]:0x67d8a3
    at http://localhost:8080/pkg-opt.wasm:wasm-function[28971]:0x1730b2f
    at http://localhost:8080/pkg-opt.wasm:wasm-function[3407]:0xb9f489
    at http://localhost:8080/pkg-opt.wasm:wasm-function[30897]:0x1799e65
    at GB.stop (http://localhost:8080/index.js:74:4084)
    at E7.stopApp (http://localhost:8080/index.js:1066:23572)
    at L (http://localhost:8080/index.js:305:32741)
    at onClick (http://localhost:8080/index.js:305:33610)
    at Object.XA (http://localhost:8080/index.js:5:9858)
    at eI (http://localhost:8080/index.js:5:10012)
    at tI (http://localhost:8080/index.js:5:10069)
    at wd (http://localhost:8080/index.js:5:31464)
    at qp (http://localhost:8080/index.js:5:31881)
    at http://localhost:8080/index.js:5:36794
    at M5 (http://localhost:8080/index.js:8:36898)
    at vp (http://localhost:8080/index.js:5:8991)
    at G0 (http://localhost:8080/index.js:5:33168)
    at o5 (http://localhost:8080/index.js:5:17363)
    at gI (http://localhost:8080/index.js:5:17147)
```

**Comment by farmaazon** [comment]
Closing, as GUI2 does not use panics.
