### ISSUE TITLE
No dropdowns on M1 Mac

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7242]
I tried the fix in this build https://github.com/enso-org/enso/actions/runs/5475368743 which I was told might fix the timeouts that were breaking dropdowns on Mac, but I saw the same behavior.

<img width="1393" alt="Screen Shot 2023-07-07 at 2 23 05 PM" src="https://github.com/enso-org/enso/assets/24406074/0dac5220-5dd2-454b-b238-82f0d8bdb5cf">

Console logs attached:
[localhost-1688754072722.log](https://github.com/enso-org/enso/files/11984834/localhost-1688754072722.log)

**Comment by hubertp** [comment]
@GregoryTravis Could I get server logs as well? That `Service error` is suspicious.

**Comment by GregoryTravis** [comment]
Console and server logs for a single run:

[20230710-141741-303-enso-project-manager.log](https://github.com/enso-org/enso/files/12003005/20230710-141741-303-enso-project-manager.log)
[localhost-1688998863359.log](https://github.com/enso-org/enso/files/12003006/localhost-1688998863359.log)

**Comment by hubertp** [comment]
Regarding no dropdowns, that's probably relevant (@jdunkerley @JaroslavTulach ?)

```
[error] [2023-07-10T14:18:33.445Z] [enso] Evaluation of visualization failed: [class org.enso.interpreter.service.error.MethodNotFoundException] Object Widgets does not define method get_full_annotations_json in module Standard.Visualization.Widgets.
org.enso.interpreter.service.error.MethodNotFoundException: Some(Object Widgets does not define method get_full_annotations_json in module Standard.Visualization.Widgets.)
  at org.enso.interpreter.service.ExecutionService.prepareFunctionCall(ExecutionService.java:113)
  at org.enso.interpreter.instrument.job.UpsertVisualisationJob$.$anonfun$evaluateModuleExpression$1(UpsertVisualisationJob.scala:240)
  at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:391)
  at org.enso.interpreter.instrument.job.UpsertVisualisationJob$.evaluateModuleExpression(UpsertVisualisationJob.scala:224)
  at org.enso.interpreter.instrument.job.UpsertVisualisationJob$.$anonfun$evaluateVisualisationExpression$1(UpsertVisualisationJob.scala:303)
  at scala.util.Either.flatMap(Either.scala:352)
  at org.enso.interpreter.instrument.job.UpsertVisualisationJob$.org$enso$interpreter$instrument$job$UpsertVisualisationJob$$evaluateVisualisationExpression(UpsertVisualisationJob.scala:302)
  at org.enso.interpreter.instrument.job.UpsertVisualisationJob.run(UpsertVisualisationJob.scala:55)
  at org.enso.interpreter.instrument.job.UpsertVisualisationJob.run(UpsertVisualisationJob.scala:37)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:111)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:100)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:134)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:125)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:709)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:632)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:565)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:549)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:477)
  at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:458)
  at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:96)
```

**Comment by hubertp** [comment]
> 2023.2.1-nightly.2023.5.11

Seems like you are running an outdated version of Enso?

**Comment by GregoryTravis** [comment]
Indeed, the latest nightly had dropdowns for me.
