### ISSUE TITLE
Enso CLI crashes if piped on Windows PowerShell

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7293]
Try creating file:
```
from Standard.Base import all

main =
    IO.println "HELLO WORLD"
```
and running it using the launcher: `enso run hello-world.enso` - this will work.

Now if I run it and pipe the output: `enso run hello-world.enso | Tee-Object -FilePath "out.txt"`, I get:
```
Exception in thread "main" com.sun.jna.LastErrorException: [6] Nieprawidłowe dojście.
        at com.sun.jna.Native.invokeVoid(Native Method)
        at com.sun.jna.Function.invoke(Function.java:415)
        at com.sun.jna.Function.invoke(Function.java:361)
        at com.sun.jna.Library$Handler.invoke(Library.java:265)
        at org.jline.terminal.impl.jna.win.$Proxy0.GetConsoleScreenBufferInfo(Unknown Source)
        at org.jline.terminal.impl.jna.win.JnaWinSysTerminal.getBufferSize(JnaWinSysTerminal.java:177)
        at org.jline.reader.impl.LineReaderImpl.doDisplay(LineReaderImpl.java:766)
        at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:315)
        at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:127)
        at org.enso.runner.TerminalIO.<init>(Repl.scala:94)
        at org.enso.runner.Main$.run(Main.scala:604)
        at org.enso.runner.Main$.main(Main.scala:1131)
        at org.enso.runner.Main.main(Main.scala)
```

**Comment by radeusgd** [comment]
I verified if it may be a launcher issue, but no - running the runner directly yields the same result:

```
> .\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\bin\enso --run ..\repr\hello-world.enso | Tee-Object -FilePath "out.txt"
Exception in thread "main" com.sun.jna.LastErrorException: [6] Nieprawidłowe dojście.
        at com.sun.jna.Native.invokeVoid(Native Method)
        at com.sun.jna.Function.invoke(Function.java:415)
        at com.sun.jna.Function.invoke(Function.java:361)
        at com.sun.jna.Library$Handler.invoke(Library.java:265)
        at org.jline.terminal.impl.jna.win.$Proxy0.GetConsoleScreenBufferInfo(Unknown Source)
        at org.jline.terminal.impl.jna.win.JnaWinSysTerminal.getBufferSize(JnaWinSysTerminal.java:177)
        at org.jline.reader.impl.LineReaderImpl.doDisplay(LineReaderImpl.java:766)
        at org.jline.reader.impl.LineReaderImpl.<init>(LineReaderImpl.java:315)
        at org.jline.reader.LineReaderBuilder.build(LineReaderBuilder.java:127)
        at org.enso.runner.TerminalIO.<init>(Repl.scala:94)
        at org.enso.runner.Main$.run(Main.scala:604)
        at org.enso.runner.Main$.main(Main.scala:1131)
        at org.enso.runner.Main.main(Main.scala)
```

**Comment by JaroslavTulach** [comment]
I guess the biggest problem is going to find a Windows machine to run Enso. I may set one up. Hubert is said to have a virtual machine for experiments. Assigning to us.

**Comment by Akirathan** [comment]
@radeusgd Which terminal emulator are you using on Windows? `windows-terminal`, or different?

**Comment by radeusgd** [comment]
> @radeusgd Which terminal emulator are you using on Windows? `windows-terminal`, or different?

Yes, I'm using the default Windows Terminal and I tried it both on Powershell and `conhost` with same results.

**Comment by JaroslavTulach** [comment]
Is it still valid? We have upgraded `jline` multiple times since then.

**Comment by radeusgd** [comment]
It seems to be working correctly now.

![Image](https://github.com/user-attachments/assets/9c49c1dc-9854-42a8-a173-6bd3f381e4b5)

**Comment by JaroslavTulach** [comment]
Thank you for verifying. It is hard to do so for Linux users (even with dual boot) especially during Google Meeting...
