### ISSUE TITLE
panicked at 'Failed to read configuration: MutuallyExclusiveOptions'

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7346]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I tried to launch local project I got left hanging on empty Enso background with this error in the dev-tools log:

![image](https://github.com/enso-org/enso/assets/108271897/4c06c1f7-c2e1-41b0-a21f-f2588de5d25e)

upon checking the CLI I got this:

```[info] [2023-07-20T07:09:28.977Z] [org.enso.languageserver.boot.LanguageServerComponent] Started server at json:127.0.0.1:58706, binary:127.0.0.1:59360
[info] [2023-07-20T07:09:29.503Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Language server booted [LanguageServerConnectionInfo(127.0.0.1,58706,59360)].
IPC error: "panicked at 'Failed to read configuration: MutuallyExclusiveOptions', app/gui/src/lib.rs:181:56\n\nStack:\n\nError\n    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:67:4238), <anonymous>:17592:17)\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[33941]:0x1836d32\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[16081]:0x150cbd0\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[29539]:0x17772e8\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[18665]:0x1621301\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[34046]:0x183ad7d\n    at JR.runEntryPoints (http://localhost:8080/index.js:70:2819)\n    at async JR.run (http://localhost:8080/index.js:67:3997)\n\n"
[info] [2023-07-20T07:10:50.705Z] [org.enso.projectmanager.protocol.ClientController] Client disconnected from the Project Manager [53577e6c-cc45-4235-9594-e6ecc1897868]
[info] [2023-07-20T07:10:50.712Z] [org.enso.projectmanager.boot.ProjectManager$] Stopping server...
[info] [2023-07-20T07:10:50.713Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerKiller] Killing all servers [Map(e233dbee-b63f-48c0-80f9-4eac11e0f9ab -> Actor[akka://project-manager/user/language-server-registry/language-server-controller-e233dbee-b63f-48c0-80f9-4eac11e0f9ab#-801814239])].
[info] [2023-07-20T07:10:50.715Z] [org.enso.languageserver.runtime.RuntimeKiller] Shutting down the runtime server [Actor[akka://language-server/user/runtime-connector#1111376103]].
[info] [2023-07-20T07:10:51.337Z] [org.enso.languageserver.runtime.RuntimeConnector] Starting the runtime connector.
[error] [2023-07-20T07:10:51.337Z] [akka.actor.OneForOneStrategy] Cannot invoke "org.enso.interpreter.instrument.execution.CommandProcessor.stop()" because the return value of "org.enso.interpreter.instrument.Handler.commandProcessor()" is null
[error] [2023-07-20T07:10:55.744Z] [org.enso.languageserver.runtime.RuntimeKiller] Disposal of runtime resources timed out.
[info] [2023-07-20T07:10:55.744Z] [org.enso.languageserver.runtime.RuntimeKiller] Shutting down the Truffle context [org.graalvm.polyglot.Context@23e0b0e4]. Attempt #1.
[info] [2023-07-20T07:10:55.747Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated truffle context.
[info] [2023-07-20T07:10:55.754Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated json connections.
[info] [2023-07-20T07:10:55.755Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated binary connections.
[info] [2023-07-20T07:10:55.766Z] [akka.actor.CoordinatedShutdown] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
[info] [2023-07-20T07:10:55.794Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated actor system.
[info] [2023-07-20T07:10:55.794Z] [org.enso.languageserver.boot.MainModule] Closed Language Server main module.
[info] [2023-07-20T07:10:55.794Z] [org.enso.languageserver.boot.LanguageServerComponent] Terminated main module.
[info] [2023-07-20T07:10:55.841Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerController] Language server shut down successfully [Project(e233dbee-b63f-48c0-80f9-4eac11e0f9ab,Orders_1,local,UserProject,2023-07-20T05:59:13.454950100Z,Some(Edition(Some(2023.2.1-nightly.2023.7.20),None,Map(),Map())),C:\Users\xvc\enso\projects\Orders_1,Some(2023-07-20T07:09:27.357332300Z),Some(2023-07-20T05:59:14.0127487Z))].
[warn] [2023-07-20T07:10:55.841Z] [org.enso.projectmanager.infrastructure.languageserver.ShutdownHookActivator] Shutdown hook activator has no recollection of project e233dbee-b63f-48c0-80f9-4eac11e0f9ab. Either it was closed already or it never existed. Ignoring.
[info] [2023-07-20T07:10:55.841Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerKiller] All language servers have been killed.
[info] [2023-07-20T07:10:55.842Z] [akka.actor.CoordinatedShutdown] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]```

### Expected behaviour

projects launching w/o panics

### How we can reproduce it?

_No response_

### Screenshots or screencasts

_No response_

### Logs

_No response_

### Enso Version

2023.7.20 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by 4e6** [comment]
From the logs
```
IPC error: "panicked at 'Failed to read configuration: MutuallyExclusiveOptions', app/gui/src/lib.rs:181:56\n\nStack:\n\nError\n    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:67:4238), <anonymous>:17592:17)\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[33941]:0x1836d32\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[16081]:0x150cbd0\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[29539]:0x17772e8\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[18665]:0x1621301\n    at https://cdn.enso.org/ide/2023.2.1-nightly.2023.7.20/pkg-opt.wasm:wasm-function[34046]:0x183ad7d\n    at JR.runEntryPoints (http://localhost:8080/index.js:70:2819)\n    at async JR.run (http://localhost:8080/index.js:67:3997)\n\n"
```
I can assume it is failing here https://github.com/enso-org/enso/blob/d8d467f62be1c990ecf180da1ac20228c07916e1/app/gui/src/lib.rs#L181

**Comment by farmaazon** [comment]
The `MutuallyExclusiveOptions` means that someone provided the IDE both project manager and language server endpoints. We should receive only one of those.

At least, that was the case some time ago. Maybe the commit I reverted recently had allowed. Anyway, because we do not allow for renaming project in the view anyway, I think the dashboard do not have to pass PM endpoints.

**Comment by farmaazon** [comment]
Merging with  #7424 which has reproduction scenario.
