### ISSUE TITLE
Panic after resizing window

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#7531]
### Discord username

Frizi

### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Application panics after shinking the electron window to minimum allowed size.

### Expected behaviour

The application should survive being shrunk down without any panics.

### How we can reproduce it?

1. Open a project that has some nodes in it.
2. Resize the window to minimum allowed size, and make it big again.
3. In case the panic didn't hapen, open devtools panel, make it relatively big and try again.

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/919491/e126d257-006a-4be7-ab34-04250abc2af4

### Logs

Looks like an issue in visualization resize handler.

```
panicked at 'assertion failed: min <= max', /rustc/1e4f90061cc4bc566f99ab21b1f101182b10cf0c/library/core/src/num/f32.rs:1394:9

Stack:

Error
    at imports.wbg.__wbg_new_abda76e883ba8a5f (eval at <anonymous> (http://localhost:8080/index.js:6837:30), <anonymous>:4805:17)
    at __wbg_new_abda76e883ba8a5f externref shim (http://localhost:8080/pkg-opt.wasm:wasm-function[67845]:0x21f89d9)
    at console_error_panic_hook::format_panic::h3c453625fc45ff83 (http://localhost:8080/pkg-opt.wasm:wasm-function[25980]:0x1b4bfe8)
    at core::ops::function::Fn::call::h4bca6da3beceaf25 (http://localhost:8080/pkg-opt.wasm:wasm-function[50078]:0x20d3ff9)
    at std::panicking::rust_panic_with_hook::hdc43d6b15c221d2e (http://localhost:8080/pkg-opt.wasm:wasm-function[40305]:0x1f25fb2)
    at std::panicking::begin_panic_handler::{{closure}}::h138701bc4f366007 (http://localhost:8080/pkg-opt.wasm:wasm-function[47323]:0x20731a1)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h6a334029ca520246 (http://localhost:8080/pkg-opt.wasm:wasm-function[65381]:0x21e708c)
    at rust_begin_unwind (http://localhost:8080/pkg-opt.wasm:wasm-function[53185]:0x211f776)
    at core::panicking::panic_fmt::hfb8e3b4832705da8 (http://localhost:8080/pkg-opt.wasm:wasm-function[62254]:0x21ba5ff)
    at core::panicking::panic::h1a31d6034d7a4a62 (http://localhost:8080/pkg-opt.wasm:wasm-function[54323]:0x2139611)
    at ide_view_graph_editor::component::visualization::container::ContainerModel::resize::h0ec7bba144dc723a (http://localhost:8080/pkg-opt.wasm:wasm-function[44207]:0x1fe8fe0)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hc926fddf57227af2 (http://localhost:8080/pkg-opt.wasm:wasm-function[22101]:0x19e3a0f)
    at <enso_frp::stream::Node<Def> as enso_frp::stream::EventEmitter>::emit_event::h2c82270f67cafa8f (http://localhost:8080/pkg-opt.wasm:wasm-function[4504]:0xe35e2f)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hfefdb368ccc26311 (http://localhost:8080/pkg-opt.wasm:wasm-function[23893]:0x1a8e8c2)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h9ec9b7213f7b6131 (http://localhost:8080/pkg-opt.wasm:wasm-function[4657]:0xe74883)
    at <enso_frp::stream::WeakNode<Def> as enso_frp::stream::WeakEventConsumer<T>>::on_event_if_exists::hc8780cebe9551aff (http://localhost:8080/pkg-opt.wasm:wasm-function[36695]:0x1e585ff)
    at <enso_frp::stream::OwnedStream<Out> as enso_frp::stream::EventEmitter>::emit_event::h9ec9b7213f7b6131 (http://localhost:8080/pkg-opt.wasm:wasm-function[4657]:0xe748eb)
    at ensogl_core::system::web::dom::shape::WithKnownShape<T>::new::{{closure}}::he4a6a5b4f1f0b471 (http://localhost:8080/pkg-opt.wasm:wasm-function[44565]:0x1ff9c2a)
    at <dyn core::ops::function::FnMut<(A,B)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h4fd3d49015d09c45 (http://localhost:8080/pkg-opt.wasm:wasm-function[66037]:0x21edc3d)
    at __wbg_adapter_69 (eval at <anonymous> (http://localhost:8080/index.js:6837:30), <anonymous>:4139:8)
    at real (eval at <anonymous> (http://localhost:8080/index.js:6837:30), <anonymous>:4072:14)
    at ResizeObserver.eval (eval at <anonymous> (http://localhost:8080/index.js:6837:30), <anonymous>:3274:5)

```

### Enso Version

b9934b0e3348dd5f033990963ed0af5068afdae2

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Windows 11

**Comment by vitvakatu** [comment]
Oops, the issue is because of these lines:
```rust
let max_size = Vector2::from(screen_shape).component_mul(&MAX_PORTION_OF_SCREEN);
new_size.x = new_size.x.clamp(MIN_SIZE.x, max_size.x);
new_size.y = new_size.y.clamp(MIN_SIZE.y, max_size.y);
```
