### ISSUE TITLE
Syntax error results in silent error

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7555]
Typo "round self round self" results in a silent error.

Typo is here: https://github.com/enso-org/enso/blob/gmt-silent-error/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso#L770

sbt build log:
[err.txt](https://github.com/enso-org/enso/files/12313798/err.txt)

**Comment by 4e6** [comment]
When changing the method signature to `round self round self`

```diff
diff --git a/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso b/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
index 873bc779a..d18822760 100644
--- a/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
+++ b/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso
@@ -865,7 +865,7 @@ type Column

              Column.from_vector "foo" [1.2, 2.3, 3.6] . round == (Column.from_vector "foo" [1, 2, 4])
     round : Integer -> Boolean -> Column | Illegal_Argument | Invalid_Value_Type
-    round self (decimal_places:Integer = 0) (use_bankers:Boolean = False) = Value_Type.expect_numeric self <|
+    round self round self (decimal_places:Integer = 0) (use_bankers:Boolean = False) = Value_Type.expect_numeric self <|
         Illegal_Argument.handle_java_exception <| Rounding_Helpers.check_decimal_places decimal_places <|
             new_name = naming_helper.function_name "round" [self]
             run_vectorized_ternary_op self Java_Storage.Maps.ROUND decimal_places use_bankers new_name=new_name
```

on the current develop I get a compiler error:
```
[ERROR] [2023-12-06T19:17:38+03:00] [org.enso.runner.Main] Unexpected internal error
org.graalvm.polyglot.PolyglotException: org.enso.compiler.core.CompilerError: Compiler Internal Error: The body of a method should always be a function.
	at org.enso.runtime/org.enso.compiler.pass.analyse.AliasAnalysis$.analyseModuleDefinition(AliasAnalysis.scala:270)
	at org.enso.runtime/org.enso.compiler.pass.analyse.AliasAnalysis$.$anonfun$runModule$1(AliasAnalysis.scala:103)
	at org.enso.runtime/scala.collection.immutable.List.map(List.scala:250)
	at org.enso.runtime/org.enso.compiler.pass.analyse.AliasAnalysis$.runModule(AliasAnalysis.scala:103)
	at org.enso.runtime/org.enso.compiler.pass.PassManager.$anonfun$runPassesOnModule$2(PassManager.scala:101)
...
```

**Comment by GregoryTravis** [comment]
That looks better than what I was getting before. Does it indicate what line the error was on?

**Comment by 4e6** [comment]
> Does it indicate what line the error was on?

No, it's a hard compiler error. It indicates that the program is in an incorrect state during the compilation

**Comment by 4e6** [comment]
Also discovered that duplicated arguments produce a warning. There are several issues with that

1. The program with warnings fails during the serialization.
2. The warning points to the original argument, and not to the one that shadows the original argument.

```
/home/dbushev/enso/projects/Unnamed/src/Main.enso:7:5: warning: Unused function argument a.
    7 | foo a a = a
      |     ^
/home/dbushev/enso/projects/Unnamed/src/Main.enso:7:5: warning: The argument 'a' is shadowed by another one with the same name.
    7 | foo a a = a
      |     ^
[ERROR] [2023-12-07T20:43:39+03:00] [enso.org.enso.interpreter.caches.ModuleCache] Failed to save cache for local.Unnamed.Main.
java.io.IOException: No persistance for org.enso.compiler.core.ir.expression.warnings.Shadowed$FunctionParam
	at org.enso.runtime/org.enso.persist.PerMap.searchSupertype(PerMap.java:63)
	at org.enso.runtime/org.enso.persist.PerMap.searchSupertype(PerMap.java:56)
	at org.enso.runtime/org.enso.persist.PerMap.searchSupertype(PerMap.java:56)
	at org.enso.runtime/org.enso.persist.PerMap.forType(PerMap.java:73)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:67)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:104)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:196)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:184)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:99)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistDiagnosticStorage.writeObject(IrPersistance.java:397)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistDiagnosticStorage.writeObject(IrPersistance.java:389)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:99)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistDefinitionArgument_Specified.writeObject(PersistDefinitionArgument_Specified.java:32)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistDefinitionArgument_Specified.writeObject(PersistDefinitionArgument_Specified.java:4)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:72)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:104)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:196)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:184)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:99)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistFunction_Lambda.writeObject(PersistFunction_Lambda.java:25)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistFunction_Lambda.writeObject(PersistFunction_Lambda.java:4)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:72)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:104)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaSeq.writeObject(IrPersistance.java:346)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaSeq.writeObject(IrPersistance.java:335)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:99)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistMethod_Explicit.writeObject(PersistMethod_Explicit.java:27)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistMethod_Explicit.writeObject(PersistMethod_Explicit.java:4)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:72)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:104)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:196)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:184)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:99)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistModule.writeObject(PersistModule.java:28)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistModule.writeObject(PersistModule.java:4)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:139)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeObject(PerGenerator.java:51)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeObject(PerGenerator.java:33)
	at org.enso.runtime/org.enso.persist.Persistance.write(Persistance.java:173)
	at org.enso.runtime/org.enso.interpreter.caches.ModuleCache.serialize(ModuleCache.java:147)
	at org.enso.runtime/org.enso.interpreter.caches.ModuleCache.serialize(ModuleCache.java:26)
	at org.enso.runtime/org.enso.interpreter.caches.Cache.saveCacheTo(Cache.java:127)
	at org.enso.runtime/org.enso.interpreter.caches.Cache.lambda$save$0(Cache.java:89)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at org.enso.runtime/org.enso.interpreter.caches.Cache.save(Cache.java:85)
	at org.enso.runtime/org.enso.interpreter.runtime.TruffleCompilerContext.saveCache(TruffleCompilerContext.java:186)
	at org.enso.runtime/org.enso.interpreter.runtime.SerializationManager.$anonfun$doSerializeModule$1(SerializationManager.scala:611)
	at org.enso.runtime/org.enso.interpreter.runtime.SerializationManager.$anonfun$doSerializeModule$1$adapted(SerializationManager.scala:591)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.SystemThread.run(SystemThread.java:68)
```

**Comment by 4e6** [comment]
After fixing the `GenerateMethodBodies` compiler pass, the compilation returns proper compiler error:
```
built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso:869:22: error: Methods must have only one definition of the `this` argument, and it must be the first.
  869 |     round self round self (decimal_places:Integer = 0) (use_bankers:Boolean = False) = Value_Type.expect_numeric self <|
      |                      ^~~~
Aborting due to 1 errors and 0 warnings.
```
