### ISSUE TITLE
op1._ yields: Compiler Internal Error: Qualified names should not be present at codegen time

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7582]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When parsing columns in the table on the third node with `parse` the compiler error occurred:
```router.ts:62 [ERROR] app/gui/src/model/project/synchronized.rs:591 Execution failed in context ca4e82f0-e987-4ba2-9dce-d6f9265d37af. Error: Execution of function main failed (Compiler Internal Error: Qualified names should not be present at codegen time.)..```
and the node was missing values:
<img width="710" alt="Zrzut ekranu 2023-08-15 o 08 10 06" src="https://github.com/enso-org/enso/assets/12892578/6dd9b8a5-bb9c-4071-abf6-a5fc06e5d77e">
After some time it recovers and it was possible to choose the proper column from the drop-down.

### Expected behaviour

The drop-down should work after appearing on the node.

### Logs

[20230815-055256-813-enso-project-manager.log](https://github.com/enso-org/enso/files/12341657/20230815-055256-813-enso-project-manager.log)

### Enso Version

nightly 15.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by sylwiabr** [comment]
happened again when working further with the same project:
[20230804-080206-882-enso-project-manager.log](https://github.com/enso-org/enso/files/12342329/20230804-080206-882-enso-project-manager.log)

**Comment by sylwiabr** [comment]
https://drive.google.com/file/d/1_ocjOryj10ScC4TLq26M2-ueBxbqOdmw/view?usp=share_link @hubertp the project folder

<blockquote><div><strong><a href="https://drive.google.com/file/d/1_ocjOryj10ScC4TLq26M2-ueBxbqOdmw/view?usp=share_link">Google Drive: Sign-in</a></strong></div><div>Access Google Drive with a Google account (for personal use) or Google Workspace account (for business use).</div></blockquote>

**Comment by sylwiabr** [comment]
Another example of the same issue, had to restart IDE
[localhost-1692269582124.log](https://github.com/enso-org/enso/files/12368431/localhost-1692269582124.log)
[New_Project_16.zip](https://github.com/enso-org/enso/files/12368436/New_Project_16.zip)
[20230817-103106-810-enso-project-manager.log](https://github.com/enso-org/enso/files/12368438/20230817-103106-810-enso-project-manager.log)

**Comment by JaroslavTulach** [comment]
```
[enso] Execution of function main failed (Compiler Internal Error: Qualified names should not be present at codegen time.).
org.enso.compiler.core.CompilerError: Some(Compiler Internal Error: Qualified names should not be present at codegen time.)
  at org.enso.compiler.codegen.IrToTruffle$ExpressionProcessor.processName(IrToTruffle.scala:1535)
  at org.enso.compiler.codegen.IrToTruffle$ExpressionProcessor.org$enso$compiler$codegen$IrToTruffle$ExpressionProcessor$$run(IrToTruffle.scala:942)
  at org.enso.compiler.codegen.IrToTruffle$ExpressionProcessor.run(IrToTruffle.scala:930)
  at org.enso.compiler.codegen.IrToTruffle$ExpressionProcessor.processBlock(IrToTruffle.scala:1014)
  at org.enso.compiler.codegen.IrToTruffle$ExpressionProcessor.org$enso$compiler$codegen$IrToTruffle$ExpressionProcessor$$run(IrToTruffle.scala:938)
  at org.enso.compiler.codegen.IrToTruffle$ExpressionProcessor$BuildFunctionBody.computeBodyNode(IrToTruffle.scala:1693)
  at org.enso.compiler.codegen.IrToTruffle$ExpressionProcessor$BuildFunctionBody.bodyN$lzycompute(IrToTruffle.scala:1676)
  at org.enso.compiler.codegen.IrToTruffle$ExpressionProcessor$BuildFunctionBody.bodyN(IrToTruffle.scala:1676)
  at org.enso.compiler.codegen.IrToTruffle$ExpressionProcessor$BuildFunctionBody.bodyNode(IrToTruffle.scala:1679)
  at org.enso.compiler.codegen.IrToTruffle.$anonfun$processModule$33(IrToTruffle.scala:499)
  at org.enso.interpreter.node.MethodRootNode$LazyBodyNode.replaceItself(MethodRootNode.java:145)
  at org.enso.interpreter.node.MethodRootNode$LazyBodyNode.replaceLazyNode(MethodRootNode.java:133)
```

**Comment by hubertp** [comment]
It appears to complain about name `operator2._`. Easy to reproduce, just create a node by dragging from the table one.
edit: Even easier to repro: Execute repl on a program with `operator2._`.
I suppose this is something IDE wants to (temporarily) add but compiler shouldn't crash so bad.

**Comment by hubertp** [comment]
Simpler test-case:
```
main =
    op = 1
    op._
```

**Comment by JaroslavTulach** [comment]
#7651 provides a _safety net_ fix for this and other `CompilerError` abnormal situations. With the fix following program:
```ruby
from Standard.Base import IO, Panic, Any

run op =
    IO.println op
    op._

main =
    IO.println "One"
    Panic.recover Any <| run 1
    IO.println "Two"
    Panic.recover Any <| run 2
    IO.println "Tři"
    Panic.recover Any <| run 3
```
outputs:
```
One
Two
Tři
(Error: (Compile_Error.Error 'Compiler Internal Error: Qualified names should not be present at codegen time.'))
```
e.g. when the `run` function is called, it yields which can be turned into `Compile_Error` with the help of  `Panic.recover`.

**Comment by JaroslavTulach** [comment]
To continue other investigations let's note that compiling following program
```ruby
run op = op._
main = run
```
yields:
```
t.enso:1:5: warning: Unused function argument op.
    1 | run op = op._
      |     ^~
t.run[t.enso:1-3]
```
e.g. the `op._` _isn't treated as a usage_ of variable `op`. We should probably detect such case and treat it as a compiler error, not just a warning...
