### ISSUE TITLE
Connection to backend lost repeated

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7624]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I lose connection to the backend every minute or so, and so spend most of the time waiting for the project to reload.

### Expected behaviour

I expect to be able to work for a little while without having to restart the IDE.

### How we can reproduce it?

This happens with most of my attempts to do book clubs, but I'll attach the project I was working on.

### Logs

[2023-08-21T20-24-10.503Z-ide-2023.2.1-dev.log](https://github.com/enso-org/enso/files/12402439/2023-08-21T20-24-10.503Z-ide-2023.2.1-dev.log)
[New_Project_1.tgz](https://github.com/enso-org/enso/files/12402446/New_Project_1.tgz)

### Enso Version

local build on wip/gmt/5131-db-take-drop / 8e97f7a9e69440c8aeac7f9a1b92b07e31ccd1df

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by hubertp** [comment]
@GregoryTravis Any other non-ide logs? There isn't much to go on with this, I'm afraid.

**Comment by hubertp** [comment]
Noticed those errors when doing pair debugging and looking at the logs:
```
[error] [2023-08-22T13:02:13.259Z] [enso] Error executing org.enso.interpreter.instrument.job.EnsureCompiledJob@7c9febcd
org.enso.interpreter.service.error.FailedToApplyEditsException: Some(Failed to apply edits for local.New_Project_1.Main, edits=***, failure=InvalidPosition(Position(16,0),text edit start line (16) outside of buffer's line count (16)), source='***')
  at org.enso.interpreter.service.ExecutionService.lambda$modifyModuleSources$9(ExecutionService.java:382)
  at scala.util.Either.fold(Either.scala:190)
  at org.enso.interpreter.service.ExecutionService.modifyModuleSources(ExecutionService.java:379)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.applyEdits(EnsureCompiledJob.scala:263)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledModule(EnsureCompiledJob.scala:94)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledFiles$2(EnsureCompiledJob.scala:73)
  at scala.collection.immutable.List.map(List.scala:246)
  at scala.collection.immutable.List.map(List.scala:79)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledFiles(EnsureCompiledJob.scala:73)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:49)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.run(EnsureCompiledJob.scala:38)
  at org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:111)
  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  at java.base/java.lang.Thread.run(Thread.java:833)
```
and (probably a consequence of it)
```
[error] [2023-08-22T13:02:13.537Z] [enso] Error executing org.enso.interpreter.instrument.job.EnsureCompiledJob@48141646
java.lang.IndexOutOfBoundsException: None
  at java.base/java.lang.Character.offsetByCodePoints(Character.java:9345)
  at java.base/java.lang.String.offsetByCodePoints(String.java:1640)
  at org.enso.text.buffer.CodePointView$Ops$.take(CodePointView.scala:91)
  at org.enso.text.buffer.CodePointView$Ops$.take(CodePointView.scala:57)
  at org.enso.text.buffer.Node.take(Tree.scala:183)
  at org.enso.text.buffer.Rope.takeWith(Rope.scala:81)
  at org.enso.text.buffer.CodePointView.take(CodePointView.scala:23)
  at org.enso.text.editing.RopeTextEditor$.cutOutHead(RopeTextEditor.scala:31)
  at org.enso.text.editing.RopeTextEditor$.edit(RopeTextEditor.scala:17)
  at org.enso.text.editing.RopeTextEditor$.edit(RopeTextEditor.scala:8)
  at org.enso.compiler.context.ChangesetBuilder.go$2(ChangesetBuilder.scala:192)
  at org.enso.compiler.context.ChangesetBuilder.invalidated(ChangesetBuilder.scala:197)
  at org.enso.compiler.context.ChangesetBuilder.compute(ChangesetBuilder.scala:157)
  at org.enso.compiler.context.ChangesetBuilder.build(ChangesetBuilder.scala:109)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.applyEdits(EnsureCompiledJob.scala:259)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.ensureCompiledModule(EnsureCompiledJob.scala:94)
  at org.enso.interpreter.instrument.job.EnsureCompiledJob.$anonfun$ensureCompiledFiles$2(EnsureCompiledJob.scala:73)
  at scala.collection.immutable.List.map(List.scala:246)
  at scala.collection.immutable.List.map(List.scala:79)
```

**Comment by GregoryTravis** [comment]
Logs attached. In today's session, I was able to create a new nodes. Then I started to use `Table.use_first_row_as_names`, only typed "use_first" and waited for suggestions to come up, but nothing came up. I hit cmd-enter and expected an error, but there was none. Opened the `use_first` node, and saw the three dots.
[2023-08-29T17-08-33.675Z-ide-2023.2.1-dev.log](https://github.com/enso-org/enso/files/12467549/2023-08-29T17-08-33.675Z-ide-2023.2.1-dev.log)
[localhost-1693329701750.log](https://github.com/enso-org/enso/files/12467550/localhost-1693329701750.log)
<img width="654" alt="Screen Shot 2023-08-29 at 1 21 32 PM" src="https://github.com/enso-org/enso/assets/24406074/078d3ac8-fa18-4fb9-8ca7-38a7cbc9cfc7">

**Comment by GregoryTravis** [comment]
Another session, with only the backend console logs attached. In this I worked for a while, then started getting mysterious type errors (with no detail); then, full-screen visualizations were partially off-screen, and then it stopped responding, even after restarting a few times.

[sout.txt](https://github.com/enso-org/enso/files/12468488/sout.txt)

**Comment by hubertp** [comment]
@GregoryTravis Weird.. don't see any relevant failures in it.

**Comment by GregoryTravis** [comment]
Another batch.
[localhost-1693337930631.log](https://github.com/enso-org/enso/files/12468585/localhost-1693337930631.log)
[backend.console.log.Tue-Aug-29-15.40.07-2023.txt](https://github.com/enso-org/enso/files/12468586/backend.console.log.Tue-Aug-29-15.40.07-2023.txt)
