### ISSUE TITLE
Could not recursively list files error

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#7695]
Wild stacktrace appeared while I was opening a local project in Enso. Creating an issue after short talk with @hubertp 

```
[info] [2023-08-30T10:29:55.804Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Data session initialized for client: 4141bb96-3988-465c-9002-2980f715ae5b [127.0.0.1:56246].
Aug 30, 2023 12:29:55 PM com.sun.jna.Native$1 uncaughtException
WARNING: JNA: Callback io.methvin.watchservice.MacOSXListeningWatchService$MacOSXListeningCallback@293f3a29 threw the following exception
java.lang.IllegalStateException: Could not recursively list files for /Users/pawelbuchowski/enso/projects/Orders_1/.enso/.vcs/
	at io.methvin.watchservice.MacOSXListeningWatchService$MacOSXListeningCallback.invoke(MacOSXListeningWatchService.java:231)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:415)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at jdk.proxy2/jdk.proxy2.$Proxy35.CFRunLoopRun(Unknown Source)
	at io.methvin.watchservice.MacOSXListeningWatchService$CFRunLoopThread.run(MacOSXListeningWatchService.java:174)
Caused by: java.nio.file.NoSuchFileException: /Users/pawelbuchowski/enso/projects/Orders_1/.enso/.vcs/HEAD.lock
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:374)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2845)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at io.methvin.watcher.PathUtils.recursiveVisitFiles(PathUtils.java:86)
	at io.methvin.watcher.PathUtils.recursiveListFiles(PathUtils.java:75)
	at io.methvin.watchservice.MacOSXListeningWatchService$MacOSXListeningCallback.invoke(MacOSXListeningWatchService.java:229)
	... 12 more

[info] [2023-08-30T10:29:56.369Z] [org.enso.languageserver.text.CollaborativeBuffer] Buffer opened for [path:Path(25269a4f-a175-479e-a851-8ddb74c5dfbc,Vector(src, Main.enso)), client:4141bb96-3988-465c-9002-2980f715ae5b].
```

**Comment by hubertp** [comment]
As far as I can see `watcher` library does not allow selective filtering of specific files. It's either recursive or not for the given root path. We would probably have to roll out our own implementation. @4e6 any thoughts?

**Comment by 4e6** [comment]
We can try to update the library first https://mvnrepository.com/artifact/io.methvin/directory-watcher

<blockquote><div><strong><a href="https://mvnrepository.com/artifact/io.methvin/directory-watcher">Just a moment...</a></strong></div></blockquote>

**Comment by hubertp** [comment]
@PabloBuchu :crossed_fingers: this should fix it but if not, please reopen if you see this again
