### ISSUE TITLE
Node evaluation is hanging

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7766]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When selecting columns the node evaluation is hanging. Opening CB is triggering node evaluation to be completed.

### Expected behaviour

Node should be evaluated.

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/1279c23a-5150-4de6-a551-cb0760b4e3a2

[enso-project-manager-2023-09-07.0.log](https://github.com/enso-org/enso/files/12549488/enso-project-manager-2023-09-07.0.log)
[New_Project_18.enso-project.zip](https://github.com/enso-org/enso/files/12549508/New_Project_18.enso-project.zip)

### Enso Version

Nightly 07.09.2023

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by hubertp** [comment]
There is 
```
[ERROR] [2023-09-07T14:42:39+02:00] [enso] Evaluation of visualization failed: [class java.lang.ArithmeticException] integer overflow
java.lang.ArithmeticException: integer overflow
	at java.base/java.lang.Math.toIntExact(Math.java:1135)
	at org.enso.compiler.core.TreeToIr.getIdentifiedLocation(TreeToIr.java:1695)
	at org.enso.compiler.core.TreeToIr.getIdentifiedLocation(TreeToIr.java:1682)
	at org.enso.compiler.core.TreeToIr.translateSyntaxError(TreeToIr.java:1613)
	at org.enso.compiler.core.TreeToIr$SyntaxException.toError(TreeToIr.java:1802)
	at org.enso.compiler.core.TreeToIr.translateImport(TreeToIr.java:1524)
	at org.enso.compiler.core.TreeToIr.translateModule(TreeToIr.java:173)
	at org.enso.compiler.core.TreeToIr.translate(TreeToIr.java:63)
	at org.enso.compiler.core.EnsoParser.generateIR(EnsoParser.java:39)
	at org.enso.compiler.Compiler.uncachedParseModule(Compiler.scala:603)
	at org.enso.compiler.Compiler.parseModule(Compiler.scala:569)
	at org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$1(Compiler.scala:247)
	at org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$1$adapted(Compiler.scala:247)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.enso.compiler.Compiler.runCompilerPipeline(Compiler.scala:247)
	at org.enso.compiler.Compiler.go$1(Compiler.scala:232)
	at org.enso.compiler.Compiler.runInternal(Compiler.scala:238)
	at org.enso.compiler.Compiler.run(Compiler.scala:135)
	at org.enso.interpreter.runtime.Module.compile(Module.java:372)
	at org.enso.interpreter.runtime.Module.compileScope(Module.java:299)
	at org.enso.interpreter.runtime.Module$InvokeMember.doInvoke(Module.java:647)
	at org.enso.interpreter.runtime.ModuleGen$InteropLibraryExports$Cached.invokeMember(ModuleGen.java:99)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8477)
	at org.enso.interpreter.service.ExecutionService$InvokeMemberRootNode.execute(ExecutionService.java:523)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:718)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:641)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:558)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:486)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:467)
	at org.enso.interpreter.service.ExecutionService.evaluateExpression(ExecutionService.java:247)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateModuleExpression$2(UpsertVisualizationJob.scala:258)
	at scala.collection.immutable.Vector1.map(Vector.scala:2152)
	at scala.collection.immutable.Vector1.map(Vector.scala:383)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateModuleExpression$1(UpsertVisualizationJob.scala:258)
	at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:391)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.evaluateModuleExpression(UpsertVisualizationJob.scala:239)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateVisualizationExpression$2(UpsertVisualizationJob.scala:326)
	at scala.util.Either.flatMap(Either.scala:352)
	at org.enso.interpreter.instrument.job.UpsertVisualizationJob$.$anonfun$evaluateVisualizationExpression$1(UpsertVisualizationJob.scala:325)
	at scala.util.Either.flatMap(Either.scala:352)
```
and 
```
[ERROR] [2023-09-07T15:06:28+02:00] [enso] Evaluation of visualization failed: [class java.util.ConcurrentModificationException] null
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at org.enso.interpreter.runtime.scope.ModuleScope.ensureMethodMapFor(ModuleScope.java:91)
	at org.enso.interpreter.runtime.scope.ModuleScope.registerMethod(ModuleScope.java:110)
	at org.enso.compiler.codegen.IrToTruffle.$anonfun$processModule$25(IrToTruffle.scala:602)
	at org.enso.compiler.codegen.IrToTruffle.$anonfun$processModule$25$adapted(IrToTruffle.scala:411)
	at scala.Option.foreach(Option.scala:437)
	at org.enso.compiler.codegen.IrToTruffle.$anonfun$processModule$17(IrToTruffle.scala:411)
	at org.enso.compiler.codegen.IrToTruffle.$anonfun$processModule$17$adapted(IrToTruffle.scala:344)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.enso.compiler.codegen.IrToTruffle.processModule(IrToTruffle.scala:344)
	at org.enso.compiler.codegen.IrToTruffle.run(IrToTruffle.scala:155)
	at org.enso.interpreter.runtime.TruffleCompilerContext.truffleRunCodegen(TruffleCompilerContext.java:124)
	at org.enso.interpreter.runtime.TruffleCompilerContext.truffleRunCodegen(TruffleCompilerContext.java:119)
	at org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$15(Compiler.scala:406)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.enso.compiler.Compiler.runCompilerPipeline(Compiler.scala:390)
	at org.enso.compiler.Compiler.go$1(Compiler.scala:232)
	at org.enso.compiler.Compiler.runInternal(Compiler.scala:238)
	at org.enso.compiler.Compiler.run(Compiler.scala:135)
	at org.enso.interpreter.runtime.Module.compile(Module.java:372)
	at org.enso.interpreter.runtime.Module.compileScope(Module.java:299)
	at org.enso.interpreter.runtime.Module$InvokeMember.doInvoke(Module.java:647)
	at org.enso.interpreter.runtime.ModuleGen$InteropLibraryExports$Cached.invokeMember(ModuleGen.java:99)
	at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen$CachedDispatch.invokeMember(InteropLibraryGen.java:8477)
	at org.enso.interpreter.service.ExecutionService$InvokeMemberRootNode.execute(ExecutionService.java:523)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:718)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:641)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:558)
	at jdk.internal.vm.compiler/org.graalvm.compiler.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:486)
```

**Comment by Akirathan** [comment]
I tried to reproduce it by creating some arbitrary long vectors for `select_columns` but failed to reproduce that. The IntegerOverflow error seems to come from quite a strange edge case of parser?
