### ISSUE TITLE
Deadlock in NI build wrt. classloading: "Image generator watchdog detected no activity"

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#7850]
There seem to be a deadlock in classloading of compiler passes caused by heavily parallel initialization of class constructors (e.g. `<cinit>`) during build of `engine-runner/buildNativeImage`.

Two builds showing the deadlock:
- [LambdaConsolidate$](https://github.com/enso-org/enso/actions/runs/6244128558/job/16950593584?pr=7848#step:10:1024) vs. [IgnoredBindings$](https://github.com/enso-org/enso/actions/runs/6244128558/job/16950593584?pr=7848#step:10:984)
- [BindingAnalysis$](https://github.com/enso-org/enso/actions/runs/6097344335/job/16544791211?pr=7728#step:10:1098) vs. [GlobalNames$](https://github.com/enso-org/enso/actions/runs/6097344335/job/16544791211?pr=7728#step:10:1184).

In both cases there are two threads initializing the compiler passes objects, each in different order:
```
"ForkJoinPool-2-worker-9" Id=76 in RUNNABLE
 at org.enso.compiler.pass.resolve.GlobalNames$.<clinit>(GlobalNames.scala:50)
 at org.enso.compiler.pass.analyse.TailCall$.<clinit>(TailCall.scala:58)
 at org.enso.compiler.pass.desugar.NestedPatternMatch$.<clinit>(NestedPatternMatch.scala:87)
 at org.enso.compiler.pass.optimise.ApplicationSaturation$.<clinit>(ApplicationSaturation.scala:37)
 at org.enso.compiler.pass.desugar.LambdaShorthandToLambda$.<clinit>(LambdaShorthandToLambda.scala:56)
 at org.enso.compiler.pass.resolve.IgnoredBindings$.<clinit>(IgnoredBindings.scala:47)
 at org.enso.compiler.pass.optimise.LambdaConsolidate$.<clinit>(LambdaConsolidate.scala:65)
 at org.enso.compiler.pass.analyse.DemandAnalysis$.<clinit>(DemandAnalysis.scala:46)
 at org.enso.compiler.pass.analyse.DataflowAnalysis$.<clinit>(DataflowAnalysis.scala:57)
 at org.enso.compiler.pass.desugar.SectionsToBinOp$.<clinit>(SectionsToBinOp.scala:36)
 at org.enso.compiler.pass.analyse.AliasAnalysis$.<clinit>(AliasAnalysis.scala:81)
 at org.enso.compiler.pass.desugar.FunctionBinding$.<clinit>(FunctionBinding.scala:46)
 at org.enso.compiler.pass.desugar.GenerateMethodBodies$.<clinit>(GenerateMethodBodies.scala:52)
 at org.enso.compiler.pass.resolve.DocumentationComments$.<clinit>(DocumentationComments.scala:42)
 at org.enso.compiler.pass.resolve.ModuleAnnotations$.<clinit>(ModuleAnnotations.scala:24)
 at org.enso.compiler.pass.desugar.ComplexType$.<clinit>(ComplexType.scala:56)
 at org.enso.compiler.pass.analyse.CachePreferenceAnalysis$.<clinit>(CachePreferenceAnalysis.scala:39)
 at java.base@17.0.7/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
 at java.base@17.0.7/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
 at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.ensureClassInitialized(ClassInitializationSupport.java:168)
```
vs. 
```
"ForkJoinPool-2-worker-12" Id=79 in RUNNABLE
at org.enso.compiler.pass.analyse.BindingAnalysis$.<clinit>(BindingAnalysis.scala:35)
at java.base@17.0.7/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
at java.base@17.0.7/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
at app/org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.ensureClassInitialized(ClassInitializationSupport.java:168)
```
These singletons that depend on other singletons seem to be dangerous. I am not sure how to convince scala to generate _deadlock free code_. @hubertp, please advice!

**Comment by hubertp** [comment]
We don't have circular dependencies between passes - there is even a check for that. But passes can depend on the same pass (in this case `BindingAnalysis` is the usual culprit).

**Comment by JaroslavTulach** [comment]
What the `BindingAnalysis<cinit>` is blocked  then? Another failed build:
- [GenerateMethodBodies$](https://github.com/enso-org/enso/actions/runs/6249373260/job/16965866384?pr=7855#step:10:1042)
- [FunctionBindings$](https://github.com/enso-org/enso/actions/runs/6249373260/job/16965866384?pr=7855#step:10:1190)
- [BindingsAnalysis$](https://github.com/enso-org/enso/actions/runs/6249373260/job/16965866384?pr=7855#step:10:1230)

**Comment by JaroslavTulach** [comment]
What does your disassembler says? Mine is showing:
```
enso$ /graalvm/bin/javap -c -cp ./engine/runtime/target/scala-2.13/classes/ 'org.enso.compiler.pass.analyse.BindingAnalysis$'
public final class org.enso.compiler.pass.analyse.BindingAnalysis$ implements org.enso.compiler.pass.IRPass,scala.Product {
  public static final org.enso.compiler.pass.analyse.BindingAnalysis$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class org/enso/compiler/pass/analyse/BindingAnalysis$
       3: dup
       4: invokespecial #64                 // Method "<init>":()V
       7: putstatic     #66                 // Field MODULE$:Lorg/enso/compiler/pass/analyse/BindingAnalysis$;
      10: getstatic     #66                 // Field MODULE$:Lorg/enso/compiler/pass/analyse/BindingAnalysis$;
      13: invokestatic  #70                 // InterfaceMethod org/enso/compiler/pass/IRPass.$init$:(Lorg/enso/compiler/pass/IRPass;)V
      16: getstatic     #66                 // Field MODULE$:Lorg/enso/compiler/pass/analyse/BindingAnalysis$;
      19: invokestatic  #73                 // InterfaceMethod scala/Product.$init$:(Lscala/Product;)V
      22: new           #75                 // class scala/collection/immutable/$colon$colon
      25: dup
      26: getstatic     #80                 // Field org/enso/compiler/pass/desugar/ComplexType$.MODULE$:Lorg/enso/compiler/pass/desugar/ComplexType$;
      29: new           #75                 // class scala/collection/immutable/$colon$colon
      32: dup
      33: getstatic     #85                 // Field org/enso/compiler/pass/desugar/FunctionBinding$.MODULE$:Lorg/enso/compiler/pass/desugar/FunctionBinding$;
      36: new           #75                 // class scala/collection/immutable/$colon$colon
      39: dup
      40: getstatic     #90                 // Field org/enso/compiler/pass/desugar/GenerateMethodBodies$.MODULE$:Lorg/enso/compiler/pass/desugar/GenerateMethodBodies$;
      43: getstatic     #95                 // Field scala/collection/immutable/Nil$.MODULE$:Lscala/collection/immutable/Nil$;
      46: invokespecial #98                 // Method scala/collection/immutable/$colon$colon."<init>":(Ljava/lang/Object;Lscala/collection/immutable/List;)V
      49: invokespecial #98                 // Method scala/collection/immutable/$colon$colon."<init>":(Ljava/lang/Object;Lscala/collection/immutable/List;)V
      52: invokespecial #98                 // Method scala/collection/immutable/$colon$colon."<init>":(Ljava/lang/Object;Lscala/collection/immutable/List;)V
      55: putstatic     #100                // Field precursorPasses:Lscala/collection/immutable/Seq;
      58: getstatic     #102                // Field bitmap$init$0:B
      61: iconst_1
      62: ior
      63: i2b
      64: putstatic     #102                // Field bitmap$init$0:B
      67: new           #75                 // class scala/collection/immutable/$colon$colon
      70: dup
      71: getstatic     #107                // Field org/enso/compiler/pass/resolve/MethodDefinitions$.MODULE$:Lorg/enso/compiler/pass/resolve/MethodDefinitions$;
      74: new           #75                 // class scala/collection/immutable/$colon$colon
      77: dup
      78: getstatic     #112                // Field org/enso/compiler/pass/resolve/Patterns$.MODULE$:Lorg/enso/compiler/pass/resolve/Patterns$;
      81: getstatic     #95                 // Field scala/collection/immutable/Nil$.MODULE$:Lscala/collection/immutable/Nil$;
      84: invokespecial #98                 // Method scala/collection/immutable/$colon$colon."<init>":(Ljava/lang/Object;Lscala/collection/immutable/List;)V
      87: invokespecial #98                 // Method scala/collection/immutable/$colon$colon."<init>":(Ljava/lang/Object;Lscala/collection/immutable/List;)V
      90: putstatic     #114                // Field invalidatedPasses:Lscala/collection/immutable/Seq;
      93: getstatic     #102                // Field bitmap$init$0:B
      96: iconst_2
      97: ior
      98: i2b
      99: putstatic     #102                // Field bitmap$init$0:B
     102: return

```
while this method is being executed, it has a lock on the class initializer - other class can access any field of `BindingsAnalysis$`. However, it is clear that the pass is accessing static fields of other classes (which are also behind a class loading lock). Clearly there is an access to `GenerateMethodBodies$.MODULE$` - a class which participated in a [deadlock just recently](https://github.com/enso-org/enso/issues/7850#issuecomment-1727502147).

**Comment by JaroslavTulach** [comment]
> We don't have circular dependencies between passes 

In ` class org.enso.compiler.pass.desugar.GenerateMethodBodies$` there is 
```
    33: getstatic     #117                // Field org/enso/compiler/pass/desugar/FunctionBinding$.MODULE$:Lorg/enso/compiler/pass/desugar/FunctionBinding$;
```
and in class `class org.enso.compiler.pass.desugar.FunctionBinding$` there is
```
      81: getstatic     #208                // Field org/enso/compiler/pass/desugar/GenerateMethodBodies$.MODULE$:Lorg/enso/compiler/pass/desugar/GenerateMethodBodies$;
```

There is a cyclic dependency (of the `<cinit>` initializers) and it is causing the native image build to get stuck!

**Comment by JaroslavTulach** [comment]
Another failure: https://github.com/enso-org/enso/actions/runs/6335322564/job/17206297931?pr=7909#step:10:1293

<blockquote><img src="https://opengraph.githubassets.com/8e2752c4e87966857c66d6b8bac78acd351671c2ca6befbaef2c782d6b7c4f21/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Make sure Integer can be treated as Float · enso-org/enso@5b2d670</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by Akirathan** [comment]
Three more failures:
- https://github.com/enso-org/enso/actions/runs/6375698889/job/17301755424?pr=7939#step:10:756
- https://github.com/enso-org/enso/actions/runs/6374666548/job/17299559275?pr=7893#step:10:742
- https://github.com/enso-org/enso/actions/runs/6350839778/job/17251123985?pr=7873#step:10:744

<blockquote><img src="https://opengraph.githubassets.com/fb8fd852becb25507b377fc15329895a9e75bfb214db4cd7edca85f7161e4511/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">[gui2] Removing nodes · enso-org/enso@411e363</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/fb8fd852becb25507b377fc15329895a9e75bfb214db4cd7edca85f7161e4511/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">[gui2] Shortcut manager + shortcuts for selecting nodes · enso-org/enso@938190e</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
