### ISSUE TITLE
Issues with non camel case projects when serializing modules

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7973]
As per conversation:
```
[ERROR] [2023-10-04T11:25:12+01:00] [enso.org.enso.compiler.ModuleCache] Failed to save cache for local.Enso_Cloud_API.Main.
java.io.NotSerializableException: com.oracle.truffle.api.source.SourceImpl
        at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1187)
        at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
```
Also, problems encountered with modules named `Mimic_Filter_SubjectIDs`. Worked fine when renamed to `Mimic_Filter_Subjects`.

**Comment by 4e6** [comment]
The issue should be resolved by the linked PRs
