### ISSUE TITLE
GUI2 starts with a missing dependency error

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8125]
```
> npm --workspace=enso-gui2 run dev
  VITE v4.4.9  ready in 696 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error: The following dependencies are imported but could not be resolved:

  lorem-ipsum (imported by /home/hubert/work/repos/enso/enso/app/gui2/src/components/ComponentBrowser.vue?id=0)

Are they installed?
    at file:///.../enso/node_modules/vite/dist/node/chunks/dep-df561101.js:45705:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///.../enso/node_modules/vite/dist/node/chunks/dep-df561101.js:45114:38
```

**Comment by hubertp** [comment]
User error.
