### ISSUE TITLE
Using TruffleLogger outside of engine leads to crashes

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8147]
As pointed out in https://github.com/enso-org/enso/pull/8014#discussion_r1351523293:

```diff
enso$ git diff
diff --git engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
index 8cb4b0b5c4..0b84019fd0 100644
--- engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
+++ engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/ReentrantLocking.scala
@@ -153,6 +153,8 @@ class ReentrantLocking(logger: TruffleLogger) extends Locking {
 
   /** @inheritdoc */
   override def acquireFileLock(file: File): Long = {
+    assertNotLocked(compilationLock, false, "wrong")
+    assertNotLocked(compilationLock, true, "wrong")
     // cannot have pendings lock as of EnsureCompiledJob.applyEdits
     assertNotLocked(
       pendingEditsLock,
$ sbt  runtime-with-instruments/test
```
and one gets:
```
java.lang.IllegalStateException: Thread using TruffleLogger has to have a current context or the TruffleLogger has to be bound to an engine., took 0.025 sec
[error]     at com.oracle.truffle.api.TruffleLogger$LoggerCache.noContext(TruffleLogger.java:1011)
[error]     at com.oracle.truffle.api.TruffleLogger$LoggerCache.isLoggable(TruffleLogger.java:993)
[error]     at com.oracle.truffle.api.TruffleLogger.isLoggableSlowPath(TruffleLogger.java:727)
[error]     at com.oracle.truffle.api.TruffleLogger.isLoggable(TruffleLogger.java:722)
[error]     at com.oracle.truffle.api.TruffleLogger.log(TruffleLogger.java:544)
[error]     at org.enso.interpreter.instrument.command.SynchronousCommand.execute(SynchronousCommand.scala:30)
[error]     at org.enso.interpreter.instrument.command.SynchronousCommand.execute(SynchronousCommand.scala:11)
[error]     at org.enso.interpreter.instrument.execution.CommandExecutionEngine.invoke(CommandExecutionEngine.scala:63)
[error]     at org.enso.interpreter.instrument.Handler.onMessage(Handler.scala:128)
[error]     at org.enso.interpreter.instrument.Endpoint.$anonfun$sendBinary$1(Handler.scala:66)
[error]     at org.enso.interpreter.instrument.Endpoint.$anonfun$sendBinary$1$adapted(Handler.scala:64)
[error]     at scala.Option.foreach(Option.scala:437)
[error]     at org.enso.interpreter.instrument.Endpoint.sendBinary(Handler.scala:64)
[error]     at com.oracle.truffle.api.instrumentation.TruffleInstrument$Env$MessageTransportProxy$MessageEndpointProxy.sendBinary(TruffleInstrument.java:1090)
[error]     at org.enso.interpreter.test.instrument.RuntimeServerEmulator.sendToRuntime(RuntimeServerEmulator.scala:53)
[error]     at org.enso.interpreter.test.instrument.RuntimeServerTest$TestContext.send(RuntimeServerTest.scala:94)
[error]     at org.enso.interpreter.test.instrument.IncrementalUpdatesTest.sendUpdatesWhenFunctionBodyIsChanged(IncrementalUpdatesTest.java:202)
[error]     at org.enso.interpreter.test.instrument.IncrementalUpdatesTest.sendUpdatesWhenFunctionBodyIsChangedBySettingValue(IncrementalUpdatesTest.java:150)
[error]     at org.enso.interpreter.test.instrument.IncrementalUpdatesTest.sendUpdatesWhenTextIsChangedBySettingValue(IncrementalUpdatesTest.java:105)
```

Also noted similar problems when logging things in serializer. Can be simulated when problems occur in verbose mode.

**Comment by hubertp** [comment]
This is weird - I'm no longer to reproduce this one. And I know I used to be able to.

**Comment by hubertp** [comment]
So it looks like my change in #7985 has _accidentally_ fixed it.

**Comment by JaroslavTulach** [comment]
I am able to reproduce the problem even on recent bits: Enough to set `private val debugLogLevel = Level.INFO` in [SerializationManager.scala](https://github.com/enso-org/enso/blob/10f35390a1c9aa05fda7c14ff569a3053e7c3e69/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala#L35) and then:
```
sbt:runtime> testOnly *SerdeCompilerTest
```
with that I get:
```
[error] Caused by: java.lang.IllegalStateException: Thread using TruffleLogger has to have a current context or the TruffleLogger has to be bound to an engine.
[error]     at com.oracle.truffle.api.TruffleLogger$LoggerCache.noContext(TruffleLogger.java:1011)
[error]     at com.oracle.truffle.api.TruffleLogger$LoggerCache.isLoggable(TruffleLogger.java:993)
[error]     at com.oracle.truffle.api.TruffleLogger.isLoggableSlowPath(TruffleLogger.java:727)
[error]     at com.oracle.truffle.api.TruffleLogger.isLoggable(TruffleLogger.java:722)
[error]     at com.oracle.truffle.api.TruffleLogger.log(TruffleLogger.java:526)
[error]     at org.enso.interpreter.runtime.TruffleCompilerContext.logSerializationManager(TruffleCompilerContext.java:91)
[error]     at org.enso.compiler.SerializationManager.$anonfun$doSerializeModule$1(SerializationManager.scala:591)
[error]     at org.enso.compiler.SerializationManager.$anonfun$doSerializeModule$1$adapted(SerializationManager.scala:583)
```
I am at 5e468f08adf8d470238471430ea5760857aa4ec2

**Comment by hubertp** [comment]
This is really odd. So #8169 provides somewhat a workaround for a case when we test the individual test. But when we run the full suite (e.g. `sbt> runtime/testOnly org.enso.compiler.*`) it still crashes. I narrowed it down to `useThreadPool` argument when serializing module. If false, everything will pass but I doubt this is what we want, so something is fishy when performing serialization asynchronously.
