### ISSUE TITLE
Tests fail on MacOS

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8657]
Running `sbt>test` (not the individual test!) fails with a rather misleading failure:
```
[info] CacheInvalidationTest:
[info] IR caching
[info] - should should propagate invalidation *** FAILED ***
[info]   Expected exception org.enso.interpreter.test.InterpreterException to be thrown, but java.util.NoSuchElementException was thrown (CacheInvalidationTest.scala:21)
[info] org.enso.compiler.test.CacheInvalidationTest *** ABORTED ***
[info]   java.io.IOException: Cannot delete file: /var/folders/ys/gf35fn152zz5kzxk8n6hbprc0000gs/T/enso-projects435575907855592398
[info]   at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1340)
[info]   at org.enso.runtime/org.enso.compiler.test.ModifiedTest.afterAll(ModifiedTest.scala:128)
[info]   at org.enso.runtime/org.enso.compiler.test.ModifiedTest.afterAll$(ModifiedTest.scala:127)
[info]   at org.enso.runtime/org.enso.compiler.test.CacheInvalidationTest.afterAll(CacheInvalidationTest.scala:6)
[info]   at org.scalatest.BeforeAndAfterAll.$anonfun$run$1(BeforeAndAfterAll.scala:225)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1(Status.scala:377)
[info]   at org.scalatest.Status.$anonfun$withAfterEffect$1$adapted(Status.scala:373)
[info]   at org.scalatest.CompositeStatus.whenCompleted(Status.scala:962)
[info]   at org.scalatest.Status.withAfterEffect(Status.scala:373)
[info]   at org.scalatest.Status.withAfterEffect$(Status.scala:371)
[info]   ...
[info]   Cause: java.nio.file.FileSystemException: /var/folders/ys/gf35fn152zz5kzxk8n6hbprc0000gs/T/enso-projects435575907855592398: Too many open files
[info]   at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
[info]   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[info]   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[info]   at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:461)
[info]   at java.base/java.nio.file.Files.newDirectoryStream(Files.java:481)
[info]   at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:301)
[info]   at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
[info]   at java.base/java.nio.file.Files.walkFileTree(Files.java:2779)
[info]   at java.base/java.nio.file.Files.walkFileTree(Files.java:2857)
[info]   at org.apache.commons.io.file.PathUtils.visitFileTree(PathUtils.java:1635)
[info]   ...
[info] ModuleAnnotationsTest:
[info] Annotation desugaring at the top level
[info] org.enso.compiler.test.pass.resolve.ModuleAnnotationsTest *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: org/enso/compiler/test/pass/resolve/ModuleAnnotationsTest$ResolveModule
[info]   at org.enso.runtime/org.enso.compiler.test.pass.resolve.ModuleAnnotationsTest.ResolveModule(ModuleAnnotationsTest.scala:34)
[info]   at org.enso.runtime/org.enso.compiler.test.pass.resolve.ModuleAnnotationsTest.$anonfun$new$2(ModuleAnnotationsTest.scala:65)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1240)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: org.enso.compiler.test.pass.resolve.ModuleAnnotationsTest$ResolveModule
[info]   at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[info]   at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[info]   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[info]   at org.enso.runtime/org.enso.compiler.test.pass.resolve.ModuleAnnotationsTest.ResolveModule(ModuleAnnotationsTest.scala:34)
[info]   at org.enso.runtime/org.enso.compiler.test.pass.resolve.ModuleAnnotationsTest.$anonfun$new$2(ModuleAnnotationsTest.scala:65)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
```

source: https://github.com/enso-org/enso/actions/runs/7355190090/job/20023435333

**Comment by hubertp** [comment]
We noticed a lot of open files when running tests which seems to be the culprit:
```
...
/Volumes/Second/Users/hubertp/enso/engine/runtime-parser/target/scala-2.13/classes/META-INF/services/org.enso.persist.Persistance
...
```
