### ISSUE TITLE
Language Server breaks on page refresh.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8689]
To reproduce
1. Open any project locally
2. Refresh page (ctrl/cmd+r in electron works)

Expected: page refreshes and loads project properly
Actual: language server reports exception, no node is colored.

The reported exception is 
```
java.lang.NullPointerException: Cannot invoke "java.util.UUID.toString()" because "a" is null
	at org.enso.IsolatedClassLoader//io.circe.Encoder$$anon$20.apply(Encoder.scala:307)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$$anon$20.apply(Encoder.scala:306)
	at org.enso.IsolatedClassLoader//org.enso.languageserver.protocol.json.JsonRpc$anon$importedEncoder$macro$6386$1$$anon$515.encodeObject(JsonRpc.scala:124)
	at org.enso.IsolatedClassLoader//org.enso.languageserver.protocol.json.JsonRpc$anon$importedEncoder$macro$6386$1$$anon$515.encodeObject(JsonRpc.scala:124)
	at org.enso.IsolatedClassLoader//io.circe.generic.encoding.DerivedAsObjectEncoder$$anon$1.encodeObject(DerivedAsObjectEncoder.scala:13)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsObject.apply(Encoder.scala:839)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsObject.apply$(Encoder.scala:839)
	at org.enso.IsolatedClassLoader//io.circe.generic.encoding.DerivedAsObjectEncoder.apply(DerivedAsObjectEncoder.scala:6)
	at org.enso.IsolatedClassLoader//io.circe.MidPriorityEncoders$IterableAsArrayEncoder.encodeArray(Encoder.scala:934)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsArray.apply(Encoder.scala:759)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsArray.apply$(Encoder.scala:759)
	at org.enso.IsolatedClassLoader//io.circe.MidPriorityEncoders$IterableAsArrayEncoder.apply(Encoder.scala:926)
	at org.enso.IsolatedClassLoader//org.enso.languageserver.protocol.json.JsonRpc$anon$importedEncoder$macro$6386$1$$anon$514.encodeObject(JsonRpc.scala:124)
	at org.enso.IsolatedClassLoader//org.enso.languageserver.protocol.json.JsonRpc$anon$importedEncoder$macro$6386$1$$anon$514.encodeObject(JsonRpc.scala:124)
	at org.enso.IsolatedClassLoader//io.circe.generic.encoding.DerivedAsObjectEncoder$$anon$1.encodeObject(DerivedAsObjectEncoder.scala:13)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsObject.apply(Encoder.scala:839)
	at org.enso.IsolatedClassLoader//io.circe.Encoder$AsObject.apply$(Encoder.scala:839)
	at org.enso.IsolatedClassLoader//io.circe.generic.encoding.DerivedAsObjectEncoder.apply(DerivedAsObjectEncoder.scala:6)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:293)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol.org$enso$jsonrpc$Protocol$$$anonfun$registerNotification$1(Protocol.scala:294)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.Protocol$$anonfun$5.apply(Protocol.scala:292)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.MessageHandler.org$enso$jsonrpc$MessageHandler$$issueNotification(MessageHandler.scala:94)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.MessageHandler$$anonfun$org$enso$jsonrpc$MessageHandler$$established$1.applyOrElse(MessageHandler.scala:51)
	at org.enso.IsolatedClassLoader//akka.actor.Actor.aroundReceive(Actor.scala:537)
	at org.enso.IsolatedClassLoader//akka.actor.Actor.aroundReceive$(Actor.scala:535)
	at org.enso.IsolatedClassLoader//org.enso.jsonrpc.MessageHandler.aroundReceive(MessageHandler.scala:13)
	at org.enso.IsolatedClassLoader//akka.actor.ActorCell.receiveMessage(ActorCell.scala:579)
	at org.enso.IsolatedClassLoader//akka.actor.ActorCell.invoke(ActorCell.scala:547)
	at org.enso.IsolatedClassLoader//akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
	at org.enso.IsolatedClassLoader//akka.dispatch.Mailbox.run(Mailbox.scala:231)
	at org.enso.IsolatedClassLoader//akka.dispatch.Mailbox.exec(Mailbox.scala:243)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
It always appears when the problem occurs. Here is full log from several launches, some reproducing the issue.

[enso-project-manager-2024-01-05.0.log](https://github.com/enso-org/enso/files/13841934/enso-project-manager-2024-01-05.0.log)

**Comment by hubertp** [comment]
[Kazam_screencast_00028.webm](https://github.com/enso-org/enso/assets/292128/6448b95a-6a21-4e3b-affa-633db18272e2)
Are these the right instructions @farmaazon ? This is what I'm getting after reloading.

**Comment by farmaazon** [comment]
This is what I get:

[Screencast from 2024-01-08 10-25-50.webm](https://github.com/enso-org/enso/assets/3919101/22b99b57-4fc4-4298-b9f3-a3f9cd8bca24)

I think I don't see login screen, because I'm already logged in.

You can try "continue without logging" option and then reopen same project.

Logs:

[enso-project-manager-2024-01-08.0.log](https://github.com/enso-org/enso/files/13858211/enso-project-manager-2024-01-08.0.log)

**Comment by hubertp** [comment]
https://github.com/enso-org/enso/assets/292128/689d52fe-1869-425f-9cdd-db616c5dd148

Still can't reproduce. When logged in. When logged out things become a bit unstable, yes.
(the video somehow doesn't show the nodes at the end, but they are there)

**Comment by hubertp** [comment]
Did more tweaks and looks like I can reproduce now. Investigating.
