### ISSUE TITLE
Invalid editions property leads to cryptic failure

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8843]
Trying out a project reported in #8801 leads to a cryptic failure from cli
```
[WARN] [2024-01-24T11:48:07+01:00] [org.enso.editions.updater.EditionUpdater] Failed to fetch editions from [https://editions.release.enso.org/enso]: {}
com.typesafe.config.ConfigException$Missing: merge of String: 1,reference.conf @ jar:file:///..././built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/../component/runtime.jar!/reference.conf: 11,version.conf @ jar:file:///..././built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/../component/runtime.jar!/version.conf: 1: No configuration setting found for key 'akka.http'
	at org.enso.runtime/com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:157)
	at org.enso.runtime/com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:175)
	at org.enso.runtime/com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:181)
	at org.enso.runtime/com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:189)
	at org.enso.runtime/com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:194)
	at org.enso.runtime/com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:269)
	at org.enso.runtime/com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:275)
	at org.enso.runtime/com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:42)
	at org.enso.runtime/akka.http.scaladsl.Http$.createExtension(Http.scala:1111)
	at org.enso.runtime/akka.http.scaladsl.Http$.createExtension(Http.scala:845)
	at org.enso.runtime/akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1165)
	at org.enso.runtime/akka.actor.ExtensionId.apply(Extension.scala:78)
	at org.enso.runtime/akka.actor.ExtensionId.apply$(Extension.scala:77)
	at org.enso.runtime/akka.http.scaladsl.Http$.apply(Http.scala:1106)
	at org.enso.runtime/akka.http.scaladsl.Http$.apply(Http.scala:845)
	at org.enso.runtime/akka.actor.ExtensionId.apply(Extension.scala:84)
	at org.enso.runtime/akka.actor.ExtensionId.apply$(Extension.scala:84)
	at org.enso.runtime/akka.http.scaladsl.Http$.apply(Http.scala:1105)
	at org.enso.runtime/org.enso.downloader.http.HTTPDownload$.runRequest(HTTPDownload.scala:213)
	at org.enso.runtime/org.enso.downloader.http.HTTPDownload$.fetchString(HTTPDownload.scala:61)
	at org.enso.runtime/org.enso.editions.updater.EditionUpdater.$anonfun$downloadEditionRepositoryManifest$1(EditionUpdater.scala:70)
	at org.enso.runtime/scala.util.Try$.apply(Try.scala:210)
	at org.enso.runtime/org.enso.editions.updater.EditionUpdater.downloadEditionRepositoryManifest(EditionUpdater.scala:67)
	at org.enso.runtime/org.enso.editions.updater.EditionUpdater.$anonfun$fetchManifests$4(EditionUpdater.scala:106)
	at org.enso.runtime/scala.Option.flatMap(Option.scala:283)
	at org.enso.runtime/org.enso.editions.updater.EditionUpdater.$anonfun$fetchManifests$2(EditionUpdater.scala:100)
	at org.enso.runtime/scala.collection.immutable.List.flatMap(List.scala:293)
	at org.enso.runtime/scala.collection.immutable.List.flatMap(List.scala:79)
	at org.enso.runtime/org.enso.editions.updater.EditionUpdater.$anonfun$fetchManifests$1(EditionUpdater.scala:99)
	at org.enso.runtime/scala.util.Try$.apply(Try.scala:210)
	at org.enso.runtime/org.enso.editions.updater.EditionUpdater.fetchManifests(EditionUpdater.scala:99)
	at org.enso.runtime/org.enso.editions.updater.EditionUpdater.$anonfun$downloadEdition$1(EditionUpdater.scala:37)
	at org.enso.runtime/scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.enso.runtime/scala.util.Try$.apply(Try.scala:210)
	at org.enso.runtime/org.enso.editions.updater.EditionUpdater.downloadEdition(EditionUpdater.scala:37)
	at org.enso.runtime/org.enso.editions.updater.UpdatingEditionProvider.findEditionForName(UpdatingEditionProvider.scala:35)
	at org.enso.runtime/org.enso.editions.EditionResolver.resolveParent(EditionResolver.scala:155)
	at org.enso.runtime/org.enso.editions.EditionResolver.resolveEdition(EditionResolver.scala:39)
	at org.enso.runtime/org.enso.editions.EditionResolver.resolve(EditionResolver.scala:29)
	at org.enso.runtime/org.enso.editions.updater.EditionManager.resolveEdition(EditionManager.scala:26)
	at org.enso.runtime/org.enso.interpreter.runtime.DefaultPackageRepository$.initializeRepository(DefaultPackageRepository.scala:652)
	at org.enso.runtime/org.enso.interpreter.runtime.DefaultPackageRepository.initializeRepository(DefaultPackageRepository.scala)
	at org.enso.runtime/org.enso.interpreter.runtime.EnsoContext.initialize(EnsoContext.java:183)
	at org.enso.runtime/org.enso.interpreter.EnsoLanguage.initializeContext(EnsoLanguage.java:156)
	at org.enso.runtime/org.enso.interpreter.EnsoLanguage.initializeContext(EnsoLanguage.java:64)
	at org.graalvm.truffle/com.oracle.truffle.api.TruffleLanguage$Env.postInit(TruffleLanguage.java:3772)
	at org.graalvm.truffle/com.oracle.truffle.api.LanguageAccessor$LanguageImpl.postInitEnv(LanguageAccessor.java:288)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureInitialized(PolyglotLanguageContext.java:771)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.getBindings(PolyglotContextImpl.java:1402)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.getBindings(PolyglotContextDispatch.java:95)
	at org.graalvm.polyglot/org.graalvm.polyglot.Context.getBindings(Context.java:563)
	at org.enso.IsolatedClassLoader//org.enso.polyglot.PolyglotContext.getTopScope(PolyglotContext.scala:37)
	at org.enso.IsolatedClassLoader//org.enso.runner.Main$.runPackage(Main.scala:764)
	at org.enso.IsolatedClassLoader//org.enso.runner.Main$.run(Main.scala:650)
	at org.enso.IsolatedClassLoader//org.enso.runner.Main$.runMain(Main.scala:1213)
	at org.enso.IsolatedClassLoader//org.enso.runner.Main$.$anonfun$main$8(Main.scala:1094)
	at org.enso.IsolatedClassLoader//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at org.enso.IsolatedClassLoader//org.enso.runner.Main$.withProfiling(Main.scala:1290)
	at org.enso.IsolatedClassLoader//org.enso.runner.Main$.$anonfun$main$7(Main.scala:1094)
	at org.enso.IsolatedClassLoader//org.enso.runner.Main$.$anonfun$main$7$adapted(Main.scala:1094)
	at org.enso.IsolatedClassLoader//scala.util.Either.fold(Either.scala:189)
	at org.enso.IsolatedClassLoader//org.enso.runner.Main$.main(Main.scala:1094)
	at org.enso.IsolatedClassLoader//org.enso.runner.Main.main(Main.scala)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.enso.runtime/org.enso.EngineRunnerBootLoader.main(EngineRunnerBootLoader.java:46)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.enso.runtime/org.enso.EngineRunnerBootLoader.main(EngineRunnerBootLoader.java:46)
Caused by: org.graalvm.polyglot.PolyglotException: org.enso.editions.EditionResolutionError$CannotLoadEdition: Cannot load edition [2024.1.1-nightly.2024.1.18]: The edition was not found.
	at org.enso.runtime/org.enso.editions.EditionResolver.$anonfun$resolveParent$1(EditionResolver.scala:157)
	at org.enso.runtime/scala.util.Either$LeftProjection.map(Either.scala:614)
```

**Comment by JaroslavTulach** [comment]
We shouldn't be using `UpdatingEditionProvider` since
- #10408

e.g. this is fixed.
