### ISSUE TITLE
No persistance for `Shadowed$FunctionParam`.

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8896]
In project [Unbooked_Seats.zip](https://github.com/enso-org/enso/files/14095597/Unbooked_Seats.zip), I have a lot of these failures:
```
[ERROR] [2024-01-30T10:18:58+01:00] [enso.org.enso.interpreter.caches.ModuleCache] Failed to save cache for local.Unbooked_Seats.Main.
java.io.IOException: No persistance for org.enso.compiler.core.ir.expression.warnings.Shadowed$FunctionParam
	at org.enso.runtime/org.enso.persist.PerMap.searchSupertype(PerMap.java:74)
	at org.enso.runtime/org.enso.persist.PerMap.searchSupertype(PerMap.java:67)
	at org.enso.runtime/org.enso.persist.PerMap.searchSupertype(PerMap.java:67)
	at org.enso.runtime/org.enso.persist.PerMap.forType(PerMap.java:84)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:80)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:127)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:207)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:195)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:147)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:122)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistDiagnosticStorage.writeObject(IrPersistance.java:409)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistDiagnosticStorage.writeObject(IrPersistance.java:401)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:147)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:122)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistDefinitionArgument_Specified.writeObject(PersistDefinitionArgument_Specified.java:32)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistDefinitionArgument_Specified.writeObject(PersistDefinitionArgument_Specified.java:4)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:147)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:88)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:127)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:207)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:195)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:147)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:122)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistFunction_Lambda.writeObject(PersistFunction_Lambda.java:25)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistFunction_Lambda.writeObject(PersistFunction_Lambda.java:4)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:147)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:88)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:127)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaSeq.writeObject(IrPersistance.java:358)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaSeq.writeObject(IrPersistance.java:347)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:147)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:122)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistMethod_Explicit.writeObject(PersistMethod_Explicit.java:27)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistMethod_Explicit.writeObject(PersistMethod_Explicit.java:4)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:147)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeIndirect(PerGenerator.java:88)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeObject(PerGenerator.java:127)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:207)
	at org.enso.runtime/org.enso.compiler.core.ir.IrPersistance$PersistScalaList.writeObject(IrPersistance.java:195)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:147)
	at org.enso.runtime/org.enso.persist.PerGenerator$ReferenceOutput.writeInline(PerGenerator.java:122)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistModule.writeObject(PersistModule.java:28)
	at org.enso.runtime/org.enso.compiler.core.ir.PersistModule.writeObject(PersistModule.java:4)
	at org.enso.runtime/org.enso.persist.Persistance.writeInline(Persistance.java:147)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeObject(PerGenerator.java:64)
	at org.enso.runtime/org.enso.persist.PerGenerator.writeObject(PerGenerator.java:42)
	at org.enso.runtime/org.enso.persist.Persistance.write(Persistance.java:186)
	at org.enso.runtime/org.enso.interpreter.caches.ModuleCache.serialize(ModuleCache.java:152)
	at org.enso.runtime/org.enso.interpreter.caches.ModuleCache.serialize(ModuleCache.java:25)
	at org.enso.runtime/org.enso.interpreter.caches.Cache.saveCacheTo(Cache.java:126)
	at org.enso.runtime/org.enso.interpreter.caches.Cache.lambda$save$0(Cache.java:88)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at org.enso.runtime/org.enso.interpreter.caches.Cache.save(Cache.java:84)
	at org.enso.runtime/org.enso.interpreter.runtime.TruffleCompilerContext.saveCache(TruffleCompilerContext.java:184)
	at org.enso.runtime/org.enso.interpreter.runtime.SerializationManager.$anonfun$doSerializeModule$1(SerializationManager.scala:611)
	at org.enso.runtime/org.enso.interpreter.runtime.SerializationManager.$anonfun$doSerializeModule$1$adapted(SerializationManager.scala:591)
	at org.enso.runtime/org.enso.interpreter.runtime.SerializationManager.serializeModule(SerializationManager.scala:138)
	at org.enso.runtime/org.enso.interpreter.instrument.job.SerializeModuleJob.lambda$run$0(SerializeModuleJob.java:44)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.enso.runtime/org.enso.interpreter.instrument.job.SerializeModuleJob.run(SerializeModuleJob.java:32)
	at org.enso.runtime/org.enso.interpreter.instrument.job.SerializeModuleJob.run(SerializeModuleJob.java:10)
	at org.enso.runtime/org.enso.interpreter.instrument.execution.JobExecutionEngine.$anonfun$runInternal$1(JobExecutionEngine.scala:124)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.access$001(PolyglotThread.java:53)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$1.execute(PolyglotThread.java:106)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.executeImpl(PolyglotThread.java:140)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread$ThreadSpawnRootNode.execute(PolyglotThread.java:131)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.executeRootNode(OptimizedCallTarget.java:746)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.profiledPERoot(OptimizedCallTarget.java:669)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callBoundary(OptimizedCallTarget.java:602)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.doInvoke(OptimizedCallTarget.java:586)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.callIndirect(OptimizedCallTarget.java:519)
	at org.graalvm.truffle.runtime/com.oracle.truffle.runtime.OptimizedCallTarget.call(OptimizedCallTarget.java:500)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotThread.run(PolyglotThread.java:102)
```

Full log attached in 
[enso-project-manager-2024-01-30.0.log](https://github.com/enso-org/enso/files/14095602/enso-project-manager-2024-01-30.0.log)

**Comment by JaroslavTulach** [comment]
There was a discussion once about persisting errors. We certainly don't want to persist files with errors. I am not completely sure, but we probably don't want to persist even files with warnings. As such the failure reported by this issue may be accurate - maybe it's just _too verbosely logged_ (but it is not easy to differentiate between `IR` with/without errors/warnings).
