### ISSUE TITLE
Bundled application cannot load parser on M1

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#8903]
Getting this error in the [2024.1.30 nightly](https://github.com/enso-org/enso/releases/tag/2024.1.1-nightly.2024.1.30).

```
Caused by: java.lang.IllegalStateException: Cannot load parser from /Applications/Enso.app/Contents/Resources/enso/dist/2024.1.1-nightly.2024.1.30/component/libenso_parser.dylib
    at org.enso.runtime/org.enso.syntax2.Parser.<clinit>(Parser.java:30)
    ... 39 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /Applications/Enso.app/Contents/Resources/enso/dist/2024.1.1-nightly.2024.1.30/component/libenso_parser.dylib: dlopen(/Applications/Enso.app/Contents/Resources/enso/dist/2024.1.1-nightly.2024.1.30/component/libenso_parser.dylib, 0x0001): tried: '/Applications/Enso.app/Contents/Resources/enso/dist/2024.1.1-nightly.2024.1.30/component/libenso_parser.dylib' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
    at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
    at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
    at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
    at java.base/java.lang.Runtime.load0(Runtime.java:852)
    at java.base/java.lang.System.load(System.java:2021)
    at org.enso.runtime/org.enso.syntax2.Parser.<clinit>(Parser.java:26)
    ... 39 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: Can't load library: /./target/rust/debug/libenso_parser.dylib
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2422)
```

[enso-project-manager-2024-01-30.0.log](https://github.com/enso-org/enso/files/14100730/enso-project-manager-2024-01-30.0.log)

**Comment by jdunkerley** [comment]
Haven't seen mac issues other than signing in a while
