### ISSUE TITLE
Defining extension methods on an unresolved type returns an error with `<Unknown source>`

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#9084]
Kind of a follow up to #8976 - when working on #9067 @AdRiley encountered a similar issue where an error was reported without a location making it very hard to find where the problem was.

After narrowing it down, we can see the following repro:
```
Unknown_Type.foo = 42

main = 0
```

### Actual behavior

```
<Unknown source>: error: The name `Unknown_Type` could not be found.
Aborting due to 1 errors and 0 warnings.
Execution finished with an error: Compilation aborted due to errors.
```

### Expected behavior

The error should include a location, so that in a bigger project one can find the location of the issue:

```
X:\NBO\enso\test.enso:1:1-12: error: The name `Unknown_Type` could not be found.
    1 | Unknown_Type.foo = 42
      | ^~~~~~~~~~~~
```

**Comment by JaroslavTulach** [comment]
This is the stacktrace that allocates the error without location:
```
java.lang.Exception: Stack trace
  | => eat java.base/java.lang.Thread.dumpStack(Thread.java:2209)
        at org.enso.runtime/org.enso.compiler.core.ir.expression.errors.Resolution.<init>(Resolution.scala:27)
        at org.enso.runtime/org.enso.compiler.pass.resolve.MethodDefinitions$.resolveType(MethodDefinitions.scala:190)
        at org.enso.runtime/org.enso.compiler.pass.resolve.MethodDefinitions$.$anonfun$runModule$3(MethodDefinitions.scala:61)
        at org.enso.runtime/scala.Option.map(Option.scala:242)
        at org.enso.runtime/org.enso.compiler.pass.resolve.MethodDefinitions$.$anonfun$runModule$2(MethodDefinitions.scala:61)
        at org.enso.runtime/scala.collection.immutable.List.map(List.scala:246)
        at org.enso.runtime/org.enso.compiler.pass.resolve.MethodDefinitions$.runModule(MethodDefinitions.scala:57)
        at org.enso.runtime/org.enso.compiler.pass.PassManager.$anonfun$runPassesOnModule$2(PassManager.scala:101)
        at org.enso.runtime/scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:183)
        at org.enso.runtime/scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:179)
        at org.enso.runtime/scala.collection.immutable.List.foldLeft(List.scala:79)
        at org.enso.runtime/org.enso.compiler.pass.PassManager.runPassesOnModule(PassManager.scala:92)
        at org.enso.runtime/org.enso.compiler.Compiler.runGlobalTypingPasses(Compiler.scala:833)
        at org.enso.runtime/org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$8(Compiler.scala:328)
        at org.enso.runtime/org.enso.compiler.Compiler.$anonfun$runCompilerPipeline$8$adapted(Compiler.scala:313)
        at org.enso.runtime/scala.collection.immutable.List.foreach(List.scala:333)
        at org.enso.runtime/org.enso.compiler.Compiler.runCompilerPipeline(Compiler.scala:313)
        at org.enso.runtime/org.enso.compiler.Compiler.go$1(Compiler.scala:234)
        at org.enso.runtime/org.enso.compiler.Compiler.runInternal(Compiler.scala:241)
        at org.enso.runtime/org.enso.compiler.Compiler.run(Compiler.scala:132)
        at org.enso.runtime/org.enso.interpreter.runtime.Module.compile(Module.java:392)
        at org.enso.runtime/org.enso.interpreter.runtime.Module.compileScope(Module.java:319)
```
