### ISSUE TITLE
Use SnakeYAML for YAML parsing (instead of circe)

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9113]
Follow up on https://github.com/enso-org/enso/issues/8692 and a [related](#9089) PR.

We use a lot of `circe` which has a high startup cost upfront due to class loading. Behind the scenes `circe` uses `SnakeYAML` engine for YAML parsing and we could potentially cut some startup time by using it directly with Java classes ([won't work](https://stackoverflow.com/questions/52395899/how-can-i-load-my-yaml-file-into-a-case-class) with plain Scala case classes).

**Comment by JaroslavTulach** [comment]
In addition to startup cost, we should also investigate independence on `java.desktop` JDK module. Alas SnakeYAML seems to require `java.desktop`:
```bash
enso$ rm -rf jdk; ~/bin/graalvm/bin/jlink --output jdk --add-modules java.net.http,jdk.unsupported,java.sql,jdk.management,jdk.jfr; ./jdk/bin/java --list-modules

# remove Python, JavaScript, regex:

enso$ rm ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/component/python-* ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/component/js-language-24.0.0.jar ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/component/icu4j-24.0.0.jar ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/component/regex-24.0.0.jar ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/component/bc*

enso$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run test/Base_Tests/Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.enso.runtime/org.enso.EngineRunnerBootLoader.main(EngineRunnerBootLoader.java:46)
Caused by: java.lang.NoClassDefFoundError: java/beans/IntrospectionException
        at org.yaml.snakeyaml.constructor.BaseConstructor.getPropertyUtils(BaseConstructor.java:645)
        at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:60)
        at org.yaml.snakeyaml.Yaml.<init>(Yaml.java:82)
        at io.circe.yaml.Parser.$anonfun$parseSingle$1(Parser.scala:39)
        at io.circe.yaml.parser.package$.parse(package.scala:18)
        at org.enso.pkg.Config$.fromYaml(Config.scala:273)
        at scala.util.Using$.apply(Using.scala:113)
        at org.enso.pkg.PackageManager.readConfig$1(Package.scala:340)
        at org.enso.pkg.PackageManager.loadPackage(Package.scala:346)
        at org.enso.runner.Main.run(Main.java:694)
```
Isn't there some other, more modern library that would work with _JavaBeans_ dependency?

**Comment by hubertp** [comment]
> Isn't there some other, more modern library that would work with _JavaBeans_ dependency?

Looks like [YamlBeans](https://github.com/EsotericSoftware/yamlbeans) is the only alternative.

**Comment by JaroslavTulach** [comment]
Looks like [SnakeYML is ready to run on Android](https://github.com/snakeyaml/snakeyaml/blob/1db25c2fd0fe2ac64fd743f14ff3c2d743353ad3/src/main/java/org/yaml/snakeyaml/introspector/PropertyUtils.java#L52) and avoid usage of `java.beans` package altogether. As such it should run without `java.desktop` too - it is just a __matter of configuring__ it.

Note: _Of course, such a configuration may require changes in upstream project to allow it_, but maybe not. The construction stack is:
```
"main"
	at org.yaml.snakeyaml.introspector.PropertyUtils.<init>(PropertyUtils.java:45)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getPropertyUtils(BaseConstructor.java:645)
	at org.yaml.snakeyaml.constructor.BaseConstructor.addTypeDescription(BaseConstructor.java:664)
	at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:134)
	at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:79)
	at org.yaml.snakeyaml.constructor.Constructor.<init>(Constructor.java:60)
	at org.yaml.snakeyaml.Yaml.<init>(Yaml.java:82)
	at io.circe.yaml.Parser.$anonfun$parseSingle$1(Parser.scala:39)
	at io.circe.yaml.Parser$$Lambda/0x00007fdb0c433680.apply
	at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:391)
	at io.circe.yaml.Parser.parseSingle(Parser.scala:39)
	at io.circe.yaml.Parser.parse(Parser.scala:29)
	at io.circe.yaml.parser.package$.parse(package.scala:18)
	at org.enso.distribution.config.GlobalConfigurationManager$(GlobalConfigurationManager.scala:88)
	at org.enso.distribution.config.GlobalConfigurationManager.getConfig(GlobalConfigurationManager.scala:28)
	at org.enso.editions.updater.EditionManager$.makeEditionProvider(EditionManager.scala:55)
```
if we remove `io.circe.yaml`, then we need to invoke `Yaml(BaseConstructor constructor)`  ourselves and provide instance of `PropertyUtils` that would have `setBeanAccess` to `FIELD`.

**Comment by JaroslavTulach** [comment]
The pull request
 - #9866 

comes with a workaround around current limitations of  SnakeYaml. There is a PR updating the upstream project
- https://github.com/snakeyaml/snakeyaml/pull/12

once it is integrated we'll have to update to new version of SnakeYaml (probably 2.x). I am not sure whether `io.circe` can work with 2.x versions or if they require 1.x version. Should there be any incompatibilities, then the simplest solution to using latest SnakeYaml with the [fix](https://github.com/snakeyaml/snakeyaml/pull/12) is to get rid of `io.circe`.

**Comment by JaroslavTulach** [comment]
[SnakeYaml fix](https://github.com/snakeyaml/snakeyaml/pull/12#issuecomment-2116599522) got merged:

> It will be delivered in version 2.3
> https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes

Please:
- update to SnakeYaml 2.3 
- and/or remove `io.circe`
- remove the [copied files](https://github.com/enso-org/enso/pull/9866#discussion_r1600903108) from our repository


<blockquote><div><strong><a href="https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes">snakeyaml / snakeyaml / wiki / Changes — Bitbucket</a></strong></div></blockquote>

**Comment by hubertp** [comment]
I've been doing more profiling and experimenting with replacing circe yaml parsing. But I guess for now we can stay with snakeYAML only that we will need to write encoders/decoders on our own.
But circe-yaml has to go:
![Screenshot from 2024-06-13 14-31-13](https://github.com/enso-org/enso/assets/292128/c813532d-8ff3-4e60-9be1-aa9ed91b6ce5)
![Screenshot from 2024-06-14 09-42-17](https://github.com/enso-org/enso/assets/292128/34bf65b8-1494-443e-a65b-9906c69bdb6c)

As one can easily see, SnakeYAML takes only a fraction of the whole circe parsing.

**Comment by hubertp** [comment]
I wlll create a separate ticket for 2.3 SnakeYAML upgrade.

**Comment by JaroslavTulach** [comment]
> using Java collections (Scala collections are problematic/not easily supported).

+1
