### ISSUE TITLE
Random CI failures: `edgeInteractions.spec.ts:59:1 › Conditional ports`

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#9459]
We have new tests failures on develop:

1. https://github.com/enso-org/enso/actions/runs/8323669986/job/22773724306#step:8:846

```
 edgeInteractions.spec.ts:59:1 › Conditional ports: Disabled ───────────────────────────────────

Error: expect(locator('.ComponentBrowser')).toExist()

  73 |   await expect(conditionalPort).not.toHaveClass(/isTarget/)
  74 |   await conditionalPort.click()
> 75 |   await expect(locate.componentBrowser(page)).toExist()
     |                                               ^
  76 |   await page.keyboard.press('Escape')
  77 | })
  78 |

    at /runner/_work/enso/enso/app/gui2/e2e/edgeInteractions.spec.ts:75:47
```

2. Similar one in: https://github.com/enso-org/enso/actions/runs/8320836548/job/22766152091#step:8:704
```
 edgeInteractions.spec.ts:79:1 › Conditional ports: Enabled ────────────────────────────────────

Test timeout of 60000ms exceeded.

Error: locator.click: Test timeout of 60000ms exceeded.
Call log:
  - waiting for locator('.GraphNode').filter({ has: locator('.binding').and(getByText('filtered')) }).locator('.WidgetPort').filter({ hasText: /^filter$/ })
  -   locator resolved to <div data-h="23d2" data-v-75c00215="" data-v-006ec768…>…</div>
  - attempting click action
  -   waiting for element to be visible, enabled and stable
  -     element is not stable - waiting...
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   performing click action
  -   <html lang="en">…</html> intercepts pointer events
  - retrying click action, attempt #1
  -   waiting for element to be visible, enabled and stable
  - element was detached from the DOM, retrying


  90 |   await conditionalPort.hover()
  91 |   await expect(conditionalPort).toHaveClass(/isTarget/)
> 92 |   await conditionalPort.click()
     |                         ^
  93 |   await expect(node.locator('.WidgetToken')).toHaveText(['final'])
  94 |
  95 |   await page.keyboard.up('Meta')

    at /runner/_work/enso/enso/app/gui2/e2e/edgeInteractions.spec.ts:92:25
```

**Comment by kazcw** [comment]
I can't reproduce these failures on my machine. They're all consistent with one root cause: The output-port click may not be initiating edge creation. We should add a check after all output port clicks that a disconnected edge exists (that would narrow down the failure in these cases). If that is the cause, we need to make output-port-clicking reliable in CI. The current approach is a bit hacky; it would be nice to use a Locator but there's a comment that we've had trouble with that.
