### ISSUE TITLE
Failing test: Component browser handling of overridden record-mode

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#9478]
https://github.com/enso-org/enso/actions/runs/8328687799/job/22789224099?pr=9406#step:8:717

```
1) componentBrowser.spec.ts:267:1 › Component browser handling of overridden record-mode ─────────

  Error: Timed out 5000ms waiting for expect(locator).toBeVisible()

  Locator: locator('.GraphNode').filter({ has: locator('.binding').and(getByText('data')) }).getByTestId('recordingOverriddenButton')
  Expected: visible
  Received: hidden
  Call log:
    - expect.toBeVisible with timeout 5000ms
    - waiting for locator('.GraphNode').filter({ has: locator('.binding').and(getByText('data')) }).getByTestId('recordingOverriddenButton')


    279 |   await page.mouse.move(100, 80)
    280 |   await page.waitForTimeout(MENU_UNHOVER_CLOSE_DELAY)
  > 281 |   await expect(recordModeIndicator).toBeVisible()
        |                                     ^
    282 |   await locate.graphNodeIcon(node).hover()
    283 |   await expect(recordModeToggle).toHaveClass(/recording-overridden/)
    284 |   // Ensure editing in the component browser doesn't display the override expression.

      at /runner/_work/enso/enso/app/gui2/e2e/componentBrowser.spec.ts:281:37

  attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
  test-results/componentBrowser-Component-browser-handling-of-overridden-record-mode/trace.zip
  Usage:

      npx playwright show-trace test-results/componentBrowser-Component-browser-handling-of-overridden-record-mode/trace.zip

  ────────────────────────────────────────────────────────────────────────────────────────────────

2) edgeInteractions.spec.ts:79:1 › Conditional ports: Enabled ────────────────────────────────────

  Test timeout of 60000ms exceeded.

  Error: locator.click: Test timeout of 60000ms exceeded.
  Call log:
    - waiting for locator('.GraphNode').filter({ has: locator('.binding').and(getByText('filtered')) }).locator('.WidgetPort').filter({ hasText: /^filter$/ })
    -   locator resolved to <div data-h="cc11" data-v-75c00215="" data-v-006ec768…>…</div>
    - attempting click action
    -   waiting for element to be visible, enabled and stable
    -   element is visible, enabled and stable
    -   scrolling into view if needed
    -   done scrolling
    -   performing click action
    -   <html lang="en">…</html> intercepts pointer events
    - retrying click action, attempt #1
    -   waiting for element to be visible, enabled and stable
    - element was detached from the DOM, retrying


    90 |   await conditionalPort.hover()
    91 |   await expect(conditionalPort).toHaveClass(/isTarget/)
  > 92 |   await conditionalPort.click()
       |                         ^
    93 |   await expect(node.locator('.WidgetToken')).toHaveText(['final'])
    94 |
    95 |   await page.keyboard.up('Meta')

      at /runner/_work/enso/enso/app/gui2/e2e/edgeInteractions.spec.ts:92:25

  attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
  test-results/edgeInteractions-Conditional-ports-Enabled/trace.zip
  Usage:

      npx playwright show-trace test-results/edgeInteractions-Conditional-ports-Enabled/trace.zip

  ────────────────────────────────────────────────────────────────────────────────────────────────

Slow test file: componentBrowser.spec.ts (2.2m)
Slow test file: edgeInteractions.spec.ts (1.6m)
Slow test file: widgets.spec.ts (1.0m)
Slow test file: collapsingAndEntering.spec.ts (46.2s)
Consider splitting slow test files to speed up parallel execution
2 failed
  componentBrowser.spec.ts:267:1 › Component browser handling of overridden record-mode ──────────
  edgeInteractions.spec.ts:79:1 › Conditional ports: Enabled ─────────────────────────────────────
100 passed (7.7m)
```

Reported in https://discord.com/channels/401396655599124480/1219381831615381547/1219381831615381547

**Comment by farmaazon** [comment]
The issue is worked around, but we should make closer investigation and possibly report a bug to playwright. For now, I lower the priority and put it back to backlog.

**Comment by farmaazon** [comment]
The test in the title is now skipped, but similar problem exists in "Previewing visualization"
