### ISSUE TITLE
Compiler Internal Error on new project in 2024.4.12 package

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9687]
### Discord username

farmaazon

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I created a new project and added `Data.read` from suggestion database. 

![Screenshot from 2024-04-12 15-47-01](https://github.com/enso-org/enso/assets/3919101/479accd6-7f61-4ae1-a2ac-9f90b828d9e9)

### Expected behaviour

The project loads, run and Data.read loads data.

### Logs

Logs from today. The last couple of project opens caused one of these issues.

[enso-project-manager-2024-04-12.0.log](https://github.com/enso-org/enso/files/14959587/enso-project-manager-2024-04-12.0.log)

### Enso Version

2024.4.12

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Garuda

**Comment by jdunkerley** [comment]
Doesn't seem to happen on the Windows installed version.

**Comment by Akirathan** [comment]
I cannot reproduce it as well on Ubuntu 23.10. `enso-linux-x86_64-2024.1.1-nightly.2024.4.12.AppImage` works just fine.

**Comment by Akirathan** [comment]
@farmaazon Maybe `rm -rf $HOME/.local/share/enso/cache` will help?

**Comment by JaroslavTulach** [comment]
There is `ClassNotFoundException` in the [log](https://github.com/enso-org/enso/files/14959587/enso-project-manager-2024-04-12.0.log):
```
[DEBUG] [2024-04-12T15:32:58+02:00] [enso.org.enso.compiler.Compiler] Generating code for module [Standard.Google_Api.Main].
[WARN] [2024-04-12T15:32:58+02:00] [enso.org.enso.interpreter.runtime.EnsoContext] null
java.lang.ClassNotFoundException: com.google.api.client.googleapis.auth.oauth2.GoogleCredential
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at org.enso.runtime/org.enso.interpreter.runtime.HostClassLoader.loadClass(HostClassLoader.java:66)
	at org.enso.runtime/org.enso.interpreter.runtime.HostClassLoader.loadClass(HostClassLoader.java:42)
	at org.enso.runtime/org.enso.interpreter.runtime.EnsoContext.lookupHostSymbol(EnsoContext.java:553)
	at org.enso.runtime/org.enso.interpreter.runtime.EnsoContext.lookupJavaClass(EnsoContext.java:531)
	at org.enso.runtime/org.enso.interpreter.runtime.IrToTruffle.$anonfun$processModule$8(IrToTruffle.scala:234)
	at org.enso.runtime/org.enso.interpreter.runtime.IrToTruffle.$anonfun$processModule$8$adapted(IrToTruffle.scala:232)
	at org.enso.runtime/scala.collection.immutable.List.foreach(List.scala:333)
	at org.enso.runtime/org.enso.interpreter.runtime.IrToTruffle.processModule(IrToTruffle.scala:232)
```
I see nothing suspicious prior to that exception.

### Is the `GoogleCredential` class available on your disk?

I can see the `GoogleCredential` class is at:
```
$ unzip -v ./distribution/lib/Standard/Google_Api/0.0.0-dev/polyglot/java/google-api-client-2.2.0.jar | grep oauth2.GoogleCredential.class
   16384  Defl:N     5944  64% 2023-01-26 16:08 74edb495  com/google/api/client/googleapis/auth/oauth2/GoogleCredential.class
$ sha256sum ./distribution/lib/Standard/Google_Api/0.0.0-dev/polyglot/java/google-api-client-2.2.0.jar
58eca9fb0a869391689ffc828b3bd0b19ac76042ff9fab4881eddf7fde76903f  ./distribution/lib/Standard/Google_Api/0.0.0-dev/polyglot/java/google-api-client-2.2.0.jar
```
simple explanation of the error would be: the class isn't present in your installation. Can you verify that? Btw. `0.0.0-dev` is likely different in case of downloaded daily build.

**Comment by farmaazon** [comment]
There _is_ google-api-client jar on 4.12 package:
```
58eca9fb0a869391689ffc828b3bd0b19ac76042ff9fab4881eddf7fde76903f  /tmp/.mount_enso-lG9kqWY/resources/enso/dist/2024.1.1-nightly.2024.4.12/lib/Standard/Google_Api/2024.1.1-nightly.2024.4.12/polyglot/java/google-api-client-2.2.0.jar
```
The checksum matches.

**Comment by farmaazon** [comment]
> @farmaazon Maybe `rm -rf $HOME/.local/share/enso/cache` will help?

It didn't help for "Class not found error"

However, today, even before removing cache, I cannot reproduce `Data.read` error today. I will remove it from this issue then (it was likely some strange setup on my side)

**Comment by jdunkerley** [comment]
Believe was an NI issue - resolved.
